import type { Agency, Service, Source, VerificationStatus } from "@/lib/types";

const checked = "2026-09-28";

export const agencies: Agency[] = [
  { slug:"nis", name:"Nigeria Immigration Service", shortName:"NIS", description:"Passport and immigration services.", website:"https://immigration.gov.ng" },
  { slug:"nimc", name:"National Identity Management Commission", shortName:"NIMC", description:"National Identification Number enrolment and modification services.", website:"https://nimc.gov.ng" },
  { slug:"frsc", name:"Federal Road Safety Corps", shortName:"FRSC", description:"Nigeria driver's licence services and road-safety processes.", website:"https://frsc.gov.ng" },
  { slug:"cac", name:"Corporate Affairs Commission", shortName:"CAC", description:"Business names, companies, incorporated trustees and corporate compliance.", website:"https://www.cac.gov.ng" },
  { slug:"jamb", name:"Joint Admissions and Matriculation Board", shortName:"JAMB", description:"UTME, Direct Entry, CAPS and admission services.", website:"https://www.jamb.gov.ng" },
  { slug:"waec", name:"West African Examinations Council Nigeria", shortName:"WAEC", description:"WASSCE results, certificates and confirmation services.", website:"https://www.waecnigeria.org" },
  { slug:"neco", name:"National Examinations Council", shortName:"NECO", description:"NECO results, result tokens and verification services.", website:"https://www.neco.gov.ng" },
  { slug:"nysc", name:"National Youth Service Corps", shortName:"NYSC", description:"Mobilisation, registration, relocation and certificate services.", website:"https://www.nysc.gov.ng" },
  { slug:"npc", name:"National Population Commission", shortName:"NPC", description:"Birth registration, attestation and certificate services.", website:"https://www.nationalpopulation.gov.ng" },
  { slug:"nrs", name:"Nigeria Revenue Service", shortName:"NRS", description:"Federal taxpayer registration and self-service tax processes.", website:"https://www.nrs.gov.ng" },
];

const source = (label:string, agency:string, url:string, published?:string): Source => ({
  label, agency, url, published, lastChecked: checked,
});

const S = {
  nisPassports: source("NIS Passports", "Nigeria Immigration Service", "https://immigration.gov.ng/passports/"),
  nisFees: source("NIS passport fee review", "Nigeria Immigration Service", "https://immigration.gov.ng/nigeria-immigration-service-announces-upward-review-of-nigerian-standard-passport-fees/", "2025-08-28"),
  nimcFees: source("NIMC Fees", "National Identity Management Commission", "https://nimc.gov.ng/fees"),
  nimcHome: source("NIMC official website", "National Identity Management Commission", "https://nimc.gov.ng/"),
  frscFaq: source("Nigeria Driver's Licence FAQ", "Federal Road Safety Corps", "https://nigeriadriverslicence.frsc.gov.ng/faq"),
  cacBusiness: source("CAC Business Name Registration", "Corporate Affairs Commission", "https://www.cac.gov.ng/services/business-name"),
  cacCompany: source("CAC Company Registration", "Corporate Affairs Commission", "https://www.cac.gov.ng/services/company-registration"),
  cacTrustee: source("CAC Incorporated Trustees", "Corporate Affairs Commission", "https://www.cac.gov.ng/services/incorporated-trustees"),
  cacTimeline: source("CAC Revised Service Timelines", "Corporate Affairs Commission", "https://www.cac.gov.ng/services/service-timelines"),
  cacPortal: source("CAC Company Registration Portal", "Corporate Affairs Commission", "https://icrp.cac.gov.ng/"),
  jambFaq: source("JAMB FAQ", "Joint Admissions and Matriculation Board", "https://www.jamb.gov.ng/FAQ"),
  jambManual: source("2026 UTME Training Manual", "Joint Admissions and Matriculation Board", "https://www.jamb.gov.ng/PDFs/2026/2026%20TRAINING%20MANUAL%20%20final.pdf", "2026"),
  jambCaps: source("JAMB CAPS", "Joint Admissions and Matriculation Board", "https://jamb.gov.ng/caps"),
  waecResult: source("WAEC Direct Result Checker", "West African Examinations Council Nigeria", "https://www.waecdirect.org/"),
  waecFaq: source("WAEC Nigeria FAQ", "West African Examinations Council Nigeria", "https://www.waecnigeria.org/faq"),
  waecConfirm: source("WAEC Confirmation of Result Requirements", "West African Examinations Council Nigeria", "https://www.waecnigeria.org/article/requirements-confirmation-result-school-candidates"),
  waecDigital: source("WAEC Digital Certificate Platform", "West African Examinations Council", "https://portal.waec.org/account/register"),
  necoResult: source("NECO Results Portal", "National Examinations Council", "https://results.neco.gov.ng/"),
  necoVerify: source("NECO e-Verify", "National Examinations Council", "https://everify.neco.gov.ng/index.php"),
  necoPay: source("NECO Payment Portal", "National Examinations Council", "https://payments.neco.gov.ng/"),
  nyscPortal: source("Official NYSC Portal", "National Youth Service Corps", "https://portal.nysc.org.ng/nysc/"),
  nyscLocal: source("NYSC Registration Requirements", "National Youth Service Corps", "https://platforms.nysc.gov.ng/mobreg.html"),
  nyscForeign: source("NYSC Foreign-Trained Requirements", "National Youth Service Corps", "https://nysc.gov.ng/foreignmobreg.html"),
  nyscMobilise: source("NYSC Corps Mobilization", "National Youth Service Corps", "https://www.nysc.gov.ng/corpmob.html"),
  nyscCns: source("NYSC Certificate of National Service", "National Youth Service Corps", "https://www.nysc.gov.ng/certcollectcns.html"),
  nyscExempt: source("NYSC Certificate of Exemption", "National Youth Service Corps", "https://www.nysc.gov.ng/certcollectexp.html"),
  npcFaq: source("NPC Self-Service FAQ", "National Population Commission", "https://www.nationalpopulation.gov.ng/FAQs"),
  npcVital: source("NPC Vital Registration FAQ", "National Population Commission", "https://www.nationalpopulation.gov.ng/faq-vitalreg"),
  npcAttest: source("NPC Birth Attestation Self-Service", "National Population Commission", "https://attestation.nationalpopulation.gov.ng/"),
  nrsRegister: source("NRS Taxpayer Registration", "Nigeria Revenue Service", "https://selfservice.nrs.gov.ng/registration"),
  nrsPortal: source("NRS Taxpayer Self-Service Portal", "Nigeria Revenue Service", "https://selfservice.nrs.gov.ng/"),
};

type GuideInput = Omit<Service, "lastVerified" | "sources" | "searchTerms" | "related"> & {
  sources: Source[];
  searchTerms?: string[];
  related?: string[];
};

const guide = (g:GuideInput): Service => ({
  ...g,
  lastVerified: checked,
  searchTerms: g.searchTerms ?? [g.shortTitle, g.title, g.category],
  related: g.related ?? [],
});

const review = (
  slug:string, title:string, shortTitle:string, category:string, agencySlug:string, officialPortal:string, sources:Source[],
): Service => guide({
  slug, title, shortTitle, summary:"This guide is in the verification queue and is not published publicly yet.",
  category, agencySlug, feeLabel:"Review pending", status:"review", officialPortal,
  requirements:["Requirements are being checked against current official sources."],
  steps:["Editorial verification is required before publication."],
  notes:["Review-pending guides are excluded from public search, service directories and sitemaps."],
  sources,
});

const published: Service[] = [
  guide({
    slug:"passport-renewal", title:"How to renew a Nigerian passport", shortTitle:"Passport renewal",
    summary:"Current fees, core requirements and the official NIS application route for passport reissue.",
    category:"Immigration", agencySlug:"nis", feeLabel:"₦100,000 / ₦200,000",
    feeNote:"For applications in Nigeria: 32-page 5-year passport ₦100,000; 64-page 10-year passport ₦200,000. Bank charges are excluded.",
    status:"verified", officialPortal:"https://passport.gov.ng",
    requirements:["NIN slip","Current passport booklet","Supporting identity/civil documents required by NIS for the application type"],
    steps:["Start on the official NIS passport portal.","Complete the online application and official payment.","Attend the selected passport office for the required biometric/enrolment step."],
    notes:["Use the official portal rather than a payment link sent by an unknown agent."], sources:[S.nisPassports,S.nisFees],
    related:["first-nigerian-passport","passport-change-of-data"],
  }),
  guide({
    slug:"first-nigerian-passport", title:"How to apply for your first Nigerian passport", shortTitle:"First Nigerian passport",
    summary:"A source-linked starter checklist for a fresh Nigerian standard passport application.",
    category:"Immigration", agencySlug:"nis", feeLabel:"₦100,000 / ₦200,000",
    feeNote:"For applications in Nigeria: 32-page 5-year passport ₦100,000; 64-page 10-year passport ₦200,000. Bank charges are excluded.",
    status:"verified", officialPortal:"https://passport.gov.ng",
    requirements:["NIN slip","Birth certificate from NPC or declaration of age","State/local government of origin evidence where required"],
    steps:["Open the official NIS passport portal.","Complete the fresh application and payment.","Attend the chosen passport office for biometrics/enrolment."],
    notes:["Fresh applications and reissues can have different processing steps."], sources:[S.nisPassports,S.nisFees],
    related:["passport-renewal"],
  }),
  guide({
    slug:"passport-change-of-data", title:"How to change data on a Nigerian passport", shortTitle:"Passport change of data",
    summary:"NIS requirements for correction of errors and other approved data changes on a passport.",
    category:"Immigration", agencySlug:"nis", feeLabel:"Administrative charge applies",
    feeNote:"NIS instructs applicants to complete the online application and pay the non-refundable administrative charge shown in the official process.",
    status:"verified", officialPortal:"https://passport.gov.ng",
    requirements:["Current passport data page","Application letter stating the reason for the change","Supporting civil documents relevant to the requested correction","Court affidavit and newspaper publication where NIS requires them"],
    steps:["Complete the passport application online.","Upload the supporting documents required for the change.","Attend the selected passport office on the scheduled date with payment and appointment slips."],
    notes:["Applicants are required to appear in person for photograph and biometric capture."], sources:[S.nisPassports],
    related:["passport-renewal"],
  }),
  guide({
    slug:"nin-date-of-birth-modification", title:"How to change your date of birth on NIN", shortTitle:"NIN date-of-birth correction",
    summary:"NIMC currently presents conflicting official fee information for date-of-birth modification, so GovGuide shows the conflict rather than guessing.",
    category:"Identity", agencySlug:"nimc", feeLabel:"Official sources require re-check",
    feeNote:"NIMC's live fee information has not been sufficiently consistent for GovGuide to present one amount as definitive.",
    status:"conflict", officialPortal:"https://nimc.gov.ng",
    requirements:["Existing NIN","Supporting civil documents for the requested correction","Payment only through the currently approved NIMC channel"],
    steps:["Check the live NIMC fee/process page immediately before payment.","Follow the official NIMC modification route.","Keep payment and submission evidence."],
    notes:["This guide remains conflict-marked until current NIMC sources are internally consistent."], sources:[S.nimcFees,S.nimcHome],
  }),
  guide({
    slug:"new-drivers-licence", title:"How to get a new Nigerian driver's licence", shortTitle:"New driver's licence",
    summary:"Official FRSC entry steps and currently listed licence fees for fresh applicants.",
    category:"Driving", agencySlug:"frsc", feeLabel:"From ₦7,000",
    feeNote:"FRSC lists Class A at ₦7,000 for 3 years or ₦11,000 for 5 years; other classes at ₦15,000 for 3 years or ₦21,000 for 5 years. Payment-channel charges may apply.",
    status:"verified", officialPortal:"https://nigeriadriverslicence.frsc.gov.ng",
    requirements:["Complete required training at an accredited driving school","Obtain the driving-school certificate number needed for a fresh application"],
    steps:["Complete accredited driving-school training.","Start the fresh application on the official driver's licence portal.","Pay the applicable fee and complete the required capture/process."],
    notes:["Fees vary by class and validity period."], sources:[S.frscFaq], related:["renew-drivers-licence","replace-lost-drivers-licence"],
  }),
  guide({
    slug:"renew-drivers-licence", title:"How to renew a Nigerian driver's licence", shortTitle:"Driver's licence renewal",
    summary:"The official FRSC renewal route and current licence fee bands.",
    category:"Driving", agencySlug:"frsc", feeLabel:"From ₦7,000",
    feeNote:"FRSC lists Class A at ₦7,000 for 3 years or ₦11,000 for 5 years; other classes at ₦15,000 for 3 years or ₦21,000 for 5 years.",
    status:"verified", officialPortal:"https://nigeriadriverslicence.frsc.gov.ng",
    requirements:["Existing driver's licence number","Details requested by the official renewal workflow"],
    steps:["Choose DL Application on the official portal.","Select Renewal of Driver's Licence.","Complete the form, payment and required capture/collection steps."],
    notes:["Use Renewal if the existing licence has expired."], sources:[S.frscFaq], related:["new-drivers-licence","replace-lost-drivers-licence"],
  }),
  guide({
    slug:"replace-lost-drivers-licence", title:"How to replace a lost or stolen Nigerian driver's licence", shortTitle:"Replace lost driver's licence",
    summary:"FRSC's official reissue route for an existing licence that is lost or stolen.",
    category:"Driving", agencySlug:"frsc", feeLabel:"Licence fee depends on class/validity",
    status:"verified", officialPortal:"https://nigeriadriverslicence.frsc.gov.ng",
    requirements:["Existing driver's licence number"],
    steps:["Open DL Application on the official portal.","Select Reissue of Driver's Licence.","Provide the existing licence number and complete the process shown by FRSC."],
    notes:["FRSC's FAQ directs lost/stolen licence holders to the Reissue option."], sources:[S.frscFaq], related:["renew-drivers-licence"],
  }),
  guide({
    slug:"upgrade-drivers-licence-class", title:"How to add or remove classes on a Nigerian driver's licence", shortTitle:"Upgrade driver's licence class",
    summary:"How FRSC says to change licence classes using renewal or reissue.",
    category:"Driving", agencySlug:"frsc", feeLabel:"Depends on licence class",
    status:"verified", officialPortal:"https://nigeriadriverslicence.frsc.gov.ng",
    requirements:["Existing driver's licence number"],
    steps:["Use Reissue if the licence is still valid or Renewal if it has expired.","Enter the existing licence number.","Use the application option to add or remove permitted classes."],
    notes:["The application form controls which class changes are permitted."], sources:[S.frscFaq],
  }),
  guide({
    slug:"cac-business-name-registration", title:"How to register a business name with CAC", shortTitle:"CAC business name registration",
    summary:"Official CAC steps for checking a name, completing registration and receiving electronic registration documents.",
    category:"Business", agencySlug:"cac", feeLabel:"See current CAC fee schedule",
    status:"verified", officialPortal:"https://icrp.cac.gov.ng/",
    requirements:["Proposed business name","Proprietor details","Supporting registration documents requested by CAC"],
    steps:["Check name availability.","Reserve the name where required.","Complete the online pre-registration form and upload documents.","Pay the official filing fee.","Download the electronic certificate/Certified Extract when approved."],
    notes:["CAC states proprietors can register business names without a lawyer, chartered accountant or chartered secretary."], sources:[S.cacBusiness,S.cacPortal],
  }),
  guide({
    slug:"cac-company-registration", title:"How to register a company with CAC", shortTitle:"CAC company registration",
    summary:"The current CAC process for name search, reservation, digital pre-registration, payment and registration documents.",
    category:"Business", agencySlug:"cac", feeLabel:"Depends on company/share structure",
    status:"verified", officialPortal:"https://icrp.cac.gov.ng/",
    requirements:["Proposed company name","Company and officer details","Supporting documents required for the chosen company type"],
    steps:["Perform a preliminary name search.","Reserve the selected name.","Complete digital pre-registration and upload supporting documents.","Pay filing and statutory stamp duty charges through the integrated process.","Download the electronic certificate and Certified Extract after approval."],
    notes:["CAC publishes a 24-working-hour service timeline for company registration once relevant documents are complete and any query is resolved."], sources:[S.cacCompany,S.cacTimeline],
  }),
  guide({
    slug:"cac-incorporated-trustee-registration", title:"How to register an incorporated trustee with CAC", shortTitle:"Incorporated trustee registration",
    summary:"Official CAC steps and core supporting documents for incorporated trustees.",
    category:"Business", agencySlug:"cac", feeLabel:"See current CAC fee schedule",
    status:"verified", officialPortal:"https://icrp.cac.gov.ng/",
    requirements:["Reserved proposed name","Organisation constitution","Trustee names, addresses and IDs","Minutes appointing trustees","Trustee declaration forms"],
    steps:["Reserve the proposed name.","Complete CAC-IT01 online.","Upload supporting documents.","Pay the applicable fee.","Receive registration documents after approval."],
    notes:["CAC lists 24 working hours as its current new-registration timeline for Incorporated Trustees once documents are complete."], sources:[S.cacTrustee,S.cacTimeline],
  }),
  guide({
    slug:"cac-name-reservation", title:"How CAC name reservation works", shortTitle:"CAC name reservation",
    summary:"Start a company, business-name or trustee registration by checking and reserving an available name.",
    category:"Business", agencySlug:"cac", feeLabel:"See current CAC fee schedule",
    timeline:"CAC currently lists 4 working hours for availability/name search and 6 working hours for name substitution.",
    status:"verified", officialPortal:"https://icrp.cac.gov.ng/",
    requirements:["A proposed entity name"],
    steps:["Search for an available name in CAC's registration system.","Reserve the chosen name.","Use the resulting reservation/availability details to continue registration."],
    notes:["Restricted names can require additional consent."], sources:[S.cacCompany,S.cacTimeline,S.cacPortal],
  }),
  guide({
    slug:"cac-annual-returns", title:"How to file CAC annual returns", shortTitle:"CAC annual returns",
    summary:"Where annual returns sit in CAC's compliance process and the current published service timeline.",
    category:"Business", agencySlug:"cac", feeLabel:"Fee varies by entity and filing",
    timeline:"CAC currently lists 24 working hours for company annual returns.",
    status:"verified", officialPortal:"https://icrp.cac.gov.ng/",
    requirements:["Registered entity details","Required annual-return information for the entity type"],
    steps:["Sign in to the official CAC registration portal.","Open the applicable annual-return filing.","Complete the filing and pay the official fee shown in the portal."],
    notes:["CAC's portal currently carries a public notice about annual returns for business names and ongoing system upgrades."], sources:[S.cacPortal,S.cacTimeline],
  }),
  guide({
    slug:"jamb-profile-code", title:"How to generate a JAMB profile code", shortTitle:"JAMB profile code",
    summary:"The official SMS format JAMB publishes for generating a profile code with NIN.",
    category:"Education", agencySlug:"jamb", feeLabel:"SMS/network charge may apply",
    status:"verified", officialPortal:"https://www.jamb.gov.ng",
    requirements:["11-digit NIN","A phone number/SIM that will remain tied to the candidate's JAMB transactions"],
    steps:["Type NIN, a space, then the 11-digit NIN.","Send the message to 55019 or 66019.","Keep the returned profile code and the SIM used."],
    notes:["JAMB states that the phone number becomes tied to the candidate's bio-data and future transactions."], sources:[S.jambFaq,S.jambManual],
    related:["jamb-2026-utme-registration","jamb-retrieve-profile-code"],
  }),
  guide({
    slug:"jamb-2026-utme-registration", title:"How much is JAMB UTME registration in 2026?", shortTitle:"2026 JAMB registration",
    summary:"Official 2026 JAMB e-PIN figures and the registration flow published by JAMB.",
    category:"Education", agencySlug:"jamb", feeLabel:"₦7,200 UTME only / ₦8,700 with mock",
    feeNote:"JAMB's 2026 training manual states UTME only ₦7,200, UTME with mock ₦8,700, and Direct Entry e-PIN ₦5,700.",
    status:"verified", officialPortal:"https://www.jamb.gov.ng",
    requirements:["NIN","JAMB profile code","Active candidate phone number","e-PIN"],
    steps:["Generate the profile code using the official SMS format.","Purchase the e-PIN through an approved JAMB channel.","Take the e-PIN to a JAMB-accredited CBT centre for registration."],
    notes:["JAMB describes its UTME/DE registration as cashless; use approved channels and accredited centres."], sources:[S.jambManual,S.jambFaq],
    related:["jamb-profile-code"],
  }),
  guide({
    slug:"jamb-retrieve-profile-code", title:"How to retrieve a lost JAMB profile code", shortTitle:"Retrieve JAMB profile code",
    summary:"The official JAMB RESEND method for retrieving a lost profile code.",
    category:"Education", agencySlug:"jamb", feeLabel:"SMS/network charge may apply",
    status:"verified", officialPortal:"https://www.jamb.gov.ng",
    requirements:["The same mobile number originally used for the profile"],
    steps:["Send RESEND from the same mobile number to 55019 or 66019.","Keep the returned profile details securely."],
    notes:["JAMB also uses RESEND to refresh a prior-year profile code for a new registration cycle."], sources:[S.jambFaq],
    related:["jamb-profile-code"],
  }),
  guide({
    slug:"jamb-retrieve-lost-epin", title:"How to retrieve a lost JAMB UTME e-PIN", shortTitle:"Retrieve lost JAMB e-PIN",
    summary:"JAMB's published SMS command for retrieving a lost UTME e-PIN.",
    category:"Education", agencySlug:"jamb", feeLabel:"SMS/network charge may apply",
    status:"verified", officialPortal:"https://www.jamb.gov.ng",
    requirements:["The unique mobile number linked to the candidate profile"],
    steps:["Send UTMEPIN from the linked phone number to 55019 or 66019.","Use the returned e-PIN for the official registration process."],
    notes:["Do not buy a replacement e-PIN from an unofficial reseller simply because the original SMS was lost."], sources:[S.jambFaq],
  }),
  guide({
    slug:"jamb-caps", title:"How JAMB CAPS works for admission", shortTitle:"JAMB CAPS",
    summary:"What JAMB's Central Admissions Processing System is designed to do in the tertiary admission process.",
    category:"Education", agencySlug:"jamb", feeLabel:"No separate fee stated on CAPS overview",
    status:"verified", officialPortal:"https://jamb.gov.ng/caps",
    requirements:["JAMB candidate/admission profile details"],
    steps:["Use JAMB's official CAPS/e-Facility route.","Review the admission information presented for your profile.","Follow only the official acceptance or other admission actions available to you."],
    notes:["JAMB describes CAPS as the system used to automate and streamline admissions into tertiary institutions."], sources:[S.jambCaps],
  }),
  guide({
    slug:"waec-check-result", title:"How to check a WAEC result online", shortTitle:"Check WAEC result",
    summary:"The fields WAEC Direct requires to check a WASSCE result online.",
    category:"Education", agencySlug:"waec", feeLabel:"Requires a valid WAEC result-checker e-PIN",
    status:"verified", officialPortal:"https://www.waecdirect.org/",
    requirements:["WAEC examination number","Examination year","Examination type","e-PIN voucher number/PIN","Serial number where requested"],
    steps:["Open WAEC Direct.","Enter the examination number and year.","Choose the exam type.","Enter the e-PIN/PIN and serial details.","Submit to view the result."],
    notes:["WAEC Direct states that a new result-checker card is required after the allowable uses on a card are exhausted."], sources:[S.waecResult],
  }),
  guide({
    slug:"waec-digital-certificate", title:"How to access a WAEC digital certificate", shortTitle:"WAEC digital certificate",
    summary:"WAEC's digital certificate platform allows candidates to access soft copies of original certificates.",
    category:"Education", agencySlug:"waec", feeLabel:"Platform charges may apply",
    status:"verified", officialPortal:"https://portal.waec.org/account/register",
    requirements:["Candidate details required by WAEC's Digital Certificate Platform","An account under Certificate Access"],
    steps:["Open the WAEC Digital Certificate Platform.","Create a Certificate Access candidate account.","Follow the platform steps to locate and access the certificate."],
    notes:["WAEC says Certificate Confirmation accounts are intended for institutions and organisations, while Certificate Access is for candidates."], sources:[S.waecDigital],
  }),
  guide({
    slug:"waec-collect-certificate", title:"How to collect a WAEC certificate", shortTitle:"Collect WAEC certificate",
    summary:"Where school and private candidates collect WAEC certificates.",
    category:"Education", agencySlug:"waec", feeLabel:"Collection process depends on candidate type",
    status:"verified", officialPortal:"https://www.waecnigeria.org",
    requirements:["Candidate/examination details","Any identification or collection requirements requested by the school or WAEC office"],
    steps:["School candidates should contact the school where they sat the examination.","Private candidates should use the WAEC office responsible for the state where they sat the examination."],
    notes:["WAEC states that its certificates do not expire."], sources:[S.waecFaq],
  }),
  guide({
    slug:"waec-confirm-result-nigeria", title:"How to confirm a WAEC result for an institution in Nigeria", shortTitle:"WAEC result confirmation in Nigeria",
    summary:"WAEC's published requirements and current administrative fee for local result confirmation.",
    category:"Education", agencySlug:"waec", feeLabel:"₦19,500 administrative charge",
    feeNote:"WAEC's current FAQ/requirements page lists ₦19,500 per result/recipient for institutions within Nigeria, plus other required items/courier costs.",
    status:"verified", officialPortal:"https://www.waecnigeria.org/article/requirements-confirmation-result-school-candidates",
    requirements:["Copy of certificate or online result printout","Sworn affidavit","Two recent passport photographs","Two 9x4 envelopes","WAEC scratch card as specified by WAEC"],
    steps:["Prepare the documents WAEC lists for confirmation.","Pay the applicable WAEC administrative charge and other required costs.","WAEC sends confirmed results directly to the requesting institution/establishment."],
    notes:["Confirmed results are not handed to candidates."], sources:[S.waecConfirm,S.waecFaq],
  }),
  guide({
    slug:"waec-lost-certificate", title:"What to do if a WAEC certificate is lost or damaged", shortTitle:"Lost WAEC certificate",
    summary:"WAEC does not simply reprint lost certificates; it provides other official routes such as statement/confirmation or attestation.",
    category:"Education", agencySlug:"waec", feeLabel:"Fee depends on requested service",
    status:"verified", officialPortal:"https://www.waecnigeria.org",
    requirements:["Candidate and examination details","Documents required for the particular statement, confirmation or attestation route"],
    steps:["Contact WAEC through the appropriate official channel.","Choose the applicable statement, confirmation or attestation process.","Provide the documents and fee WAEC requests."],
    notes:["WAEC's FAQ states that lost certificates are not replaced with a duplicate certificate in the ordinary way."], sources:[S.waecFaq],
  }),
  guide({
    slug:"neco-check-result", title:"How to check a NECO result online", shortTitle:"Check NECO result",
    summary:"The official NECO Results Portal process using exam year/type, token and registration number.",
    category:"Education", agencySlug:"neco", feeLabel:"Requires a NECO result token",
    status:"verified", officialPortal:"https://results.neco.gov.ng/",
    requirements:["Examination year","Examination type","Result token","Registration number"],
    steps:["Open the official NECO Results Portal.","Select the examination year and type.","Enter the token and registration number.","Choose Check my result."],
    notes:["The official portal includes a purchase-token option."], sources:[S.necoResult],
  }),
  guide({
    slug:"neco-purchase-result-token", title:"How to purchase a NECO result token", shortTitle:"NECO result token",
    summary:"The official result portal provides token purchase for candidates who do not already have one.",
    category:"Education", agencySlug:"neco", feeLabel:"Current token price shown in NECO purchase flow",
    status:"verified", officialPortal:"https://results.neco.gov.ng/",
    requirements:["Payment details required by the official token purchase flow"],
    steps:["Open the official NECO Results Portal.","Choose Purchase token.","Complete the official account/payment process shown by NECO."],
    notes:["Use the token on the same official result-checking portal."], sources:[S.necoResult],
  }),
  guide({
    slug:"neco-e-verify", title:"How to verify or confirm a NECO result with e-Verify", shortTitle:"NECO e-Verify",
    summary:"NECO's official e-Verify workflow for individual result verification/confirmation.",
    category:"Education", agencySlug:"neco", feeLabel:"Payment token required",
    status:"verified", officialPortal:"https://everify.neco.gov.ng/index.php",
    requirements:["NECO e-Verify account","Candidate examination details","Payment token/RRR"],
    steps:["Create/sign in to the e-Verify account.","Generate and pay for the verification token.","Validate the payment.","Submit the application with the candidate details.","Download the generated report when available."],
    notes:["NECO says the report can also be sent to the provided recipient email."], sources:[S.necoVerify],
  }),
  guide({
    slug:"neco-payment", title:"How to make an official NECO service payment", shortTitle:"NECO service payment",
    summary:"NECO's payment portal explains how to use a payment-item code and retain evidence of payment.",
    category:"Education", agencySlug:"neco", feeLabel:"Depends on NECO service",
    status:"verified", officialPortal:"https://payments.neco.gov.ng/",
    requirements:["Correct NECO payment item code","Payer/service details"],
    steps:["Get the correct payment-item code from NECO.","Select the payment item on the official payment portal.","Complete the payment form and select the payment method.","Keep evidence of payment."],
    notes:["NECO warns users to verify the payment details before paying and states refunds are not applicable once payment is completed."], sources:[S.necoPay],
  }),
  guide({
    slug:"nysc-registration-local", title:"How NYSC registration works for locally trained graduates", shortTitle:"NYSC registration",
    summary:"Core NYSC registration conditions for locally trained prospective corps members.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"Portal payment applies to optional/portal services as shown by NYSC",
    status:"verified", officialPortal:"https://portal.nysc.org.ng/nysc/",
    requirements:["Functional email address","Nigerian GSM phone number","Correct matriculation number","Name on the Senate/Academic Board approved list"],
    steps:["Confirm eligibility/senate-list status.","Open the official NYSC portal during an active registration window.","Complete biometric-enabled online registration.","Download the documents made available in your dashboard."],
    notes:["NYSC says locally trained graduates whose names are not on the approved Senate/Academic Board list cannot register."], sources:[S.nyscLocal,S.nyscPortal],
  }),
  guide({
    slug:"nysc-foreign-trained-registration", title:"How NYSC registration works for foreign-trained Nigerian graduates", shortTitle:"NYSC foreign-trained registration",
    summary:"Official academic-document and physical-verification requirements for foreign-trained graduates.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"Use official NYSC portal for any applicable payment",
    status:"verified", officialPortal:"https://portal.nysc.org.ng/nysc/",
    requirements:["Original first degree or HND certificate","Complete official transcript","O'level certificate","International passport and other documents required by NYSC"],
    steps:["Register on the official NYSC portal.","Upload the credentials required by NYSC.","Attend physical verification at the venue/date shown in the dashboard.","Keep original credentials available until verification is complete."],
    notes:["NYSC states that downloaded certificates/transcripts, statements of result and attestation letters are not accepted for this route."], sources:[S.nyscForeign,S.nyscPortal],
  }),
  guide({
    slug:"nysc-revalidation", title:"When and how to use NYSC revalidation", shortTitle:"NYSC revalidation",
    summary:"Revalidation is for people previously deployed in a batch who did not report to orientation camp.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"Use the active NYSC portal process",
    status:"verified", officialPortal:"https://portal.nysc.org.ng/nysc/",
    requirements:["Prior NYSC deployment details"],
    steps:["Open the official NYSC portal during the applicable registration window.","Choose the Revalidation option.","Complete the online process shown in the portal."],
    notes:["NYSC distinguishes revalidation from remobilization."], sources:[S.nyscPortal],
  }),
  guide({
    slug:"nysc-remobilization", title:"When and how to use NYSC remobilization", shortTitle:"NYSC remobilization",
    summary:"NYSC describes remobilization as the route for corps members who absconded and are ready to return.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"Use the active NYSC portal process",
    status:"verified", officialPortal:"https://portal.nysc.org.ng/nysc/",
    requirements:["Prior NYSC mobilisation/service details"],
    steps:["Open the official NYSC portal.","Choose Remobilization when the application window is available.","Complete the required application shown by NYSC."],
    notes:["Do not confuse remobilization with revalidation for someone who never reported to camp."], sources:[S.nyscPortal],
  }),
  guide({
    slug:"nysc-relocation", title:"How NYSC relocation works", shortTitle:"NYSC relocation",
    summary:"NYSC's official description of online relocation and concessional grounds.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"Use the official NYSC portal process",
    status:"verified", officialPortal:"https://portal.nysc.org.ng/nysc/",
    requirements:["NYSC service details","Supporting evidence where applying on marital or health grounds"],
    steps:["Use the NYSC online relocation route when eligible.","Submit the application and supporting evidence required for the stated ground.","Track the recommendation/outcome through the official process."],
    notes:["NYSC states relocation is processed electronically and describes marital and health grounds among concessional cases."], sources:[S.nyscMobilise],
  }),
  guide({
    slug:"nysc-lost-discharge-certificate", title:"What to do if an NYSC discharge certificate is lost", shortTitle:"Lost NYSC discharge certificate",
    summary:"NYSC's official requirements after loss of a Certificate of National Service.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"NYSC does not reprint lost/burnt certificates",
    status:"verified", officialPortal:"https://www.nysc.gov.ng/certcollectcns.html",
    requirements:["Police extract/report","Court affidavit","Letter of introduction from the state of service","Copy of the lost certificate where available"],
    steps:["Prepare the documents NYSC lists for loss of certificate.","Contact the relevant NYSC certification channel.","Follow the confirmation route provided by NYSC."],
    notes:["NYSC states lost or burnt Certificates of National Service are not reprinted; Letters of Confirmation are issued instead."], sources:[S.nyscCns],
  }),
  guide({
    slug:"nysc-lost-exemption-certificate", title:"What to do if an NYSC exemption certificate is lost", shortTitle:"Lost NYSC exemption certificate",
    summary:"Requirements NYSC lists for loss of a Certificate of Exemption.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"NYSC does not reprint lost/burnt certificates",
    status:"verified", officialPortal:"https://www.nysc.gov.ng/certcollectexp.html",
    requirements:["Letter of notification/request","Police extract/report","Court affidavit","Copy of the lost certificate where available","Foreign-trained applicants also need passport data-page copy"],
    steps:["Prepare the listed documents.","Route the request through the appropriate NYSC channel for home- or foreign-trained graduates.","Follow NYSC's confirmation process."],
    notes:["NYSC says Letters of Confirmation are issued instead of reprinting lost or burnt exemption certificates."], sources:[S.nyscExempt],
  }),
  guide({
    slug:"npc-birth-attestation", title:"How to apply for NPC birth attestation as an adult", shortTitle:"NPC birth attestation",
    summary:"NPC's self-service birth-attestation route for people aged 18 and above.",
    category:"Civil records", agencySlug:"npc", feeLabel:"USD 80 convenience fee shown by NPC self-service",
    status:"verified", officialPortal:"https://attestation.nationalpopulation.gov.ng/",
    requirements:["Age 18 or above","Court sworn affidavit","Valid email address","Active phone number","NIN verification where applicable"],
    steps:["Open the official NPC attestation self-service.","Complete identity/NIN verification as applicable.","Provide the requested registration details and face capture.","Complete the official payment/application flow.","Use the payment reference to check status/download when approved."],
    notes:["NPC's portal says an applicant can apply for attestation only once, so information should be checked carefully before submission."], sources:[S.npcAttest,S.npcFaq],
  }),
  guide({
    slug:"npc-child-birth-registration", title:"How NPC birth registration works for a child", shortTitle:"NPC child birth registration",
    summary:"NPC's current age range and stated requirements for child birth registration.",
    category:"Civil records", agencySlug:"npc", feeLabel:"Check current NPC self-service portal",
    status:"verified", officialPortal:"https://www.nationalpopulation.gov.ng",
    requirements:["Child aged 0 to 17","Child's NIN where applicable to the current process","Parent's attestation number as stated by NPC"],
    steps:["Create/sign in to the NPC self-service account.","Choose the birth-registration service.","Provide the child/parent details required by NPC.","Complete the official workflow shown in the portal."],
    notes:["NPC states birth registration is for ages 0–17, while birth attestation is for people aged 18 and above."], sources:[S.npcFaq,S.npcVital],
  }),
  guide({
    slug:"npc-digital-birth-certificate-reissuance", title:"How to get a digital version of an old NPC birth certificate", shortTitle:"Digital birth certificate reissuance",
    summary:"NPC directs holders of old birth certificates to its Certificate Reissuance service.",
    category:"Civil records", agencySlug:"npc", feeLabel:"Check current NPC self-service portal",
    status:"verified", officialPortal:"https://www.nationalpopulation.gov.ng",
    requirements:["NPC self-service account","NIN-linked account setup as required by NPC","Existing birth record details"],
    steps:["Create/sign in to the NPC self-service account.","Choose Certificate Reissuance.","Link/verify NIN as required.","Complete the digital certificate request."],
    notes:["This route is for reissuing an existing record, not creating a new birth record."], sources:[S.npcFaq,S.npcVital],
  }),
  guide({
    slug:"npc-birth-certificate-reprint", title:"How to reprint an NPC birth certificate", shortTitle:"NPC certificate reprint",
    summary:"NPC's self-service FAQ points existing record holders to the Certificate Reprint module.",
    category:"Civil records", agencySlug:"npc", feeLabel:"Reprint payment required",
    status:"verified", officialPortal:"https://www.nationalpopulation.gov.ng",
    requirements:["NPC self-service account","Existing record/reference details"],
    steps:["Sign in to the NPC self-service dashboard.","Open Certificate Reprint.","Complete the payment and reprint process shown by NPC."],
    notes:["NPC's FAQ distinguishes reprint from certificate reissuance."], sources:[S.npcFaq,S.npcVital],
  }),
  guide({
    slug:"nrs-individual-tax-registration", title:"How to register as an individual taxpayer with NRS", shortTitle:"NRS individual taxpayer registration",
    summary:"The official NRS self-service registration route includes an Individuals category for people with NIN and non-resident persons.",
    category:"Tax", agencySlug:"nrs", feeLabel:"No registration fee stated on NRS self-service page",
    status:"verified", officialPortal:"https://selfservice.nrs.gov.ng/registration",
    requirements:["NIN for the individual route where applicable","Details requested by the NRS registration flow"],
    steps:["Open the NRS taxpayer registration page.","Choose Individuals.","Complete the registration fields and identity steps requested by NRS."],
    notes:["Use the federal NRS route only for taxes/services under NRS jurisdiction; state tax obligations can involve the relevant state authority."], sources:[S.nrsRegister],
  }),
  guide({
    slug:"nrs-corporate-tax-registration", title:"How to register a corporate taxpayer with NRS", shortTitle:"NRS corporate taxpayer registration",
    summary:"NRS provides a Corporate registration category for entities incorporated with CAC under CAMA.",
    category:"Tax", agencySlug:"nrs", feeLabel:"No registration fee stated on NRS self-service page",
    status:"verified", officialPortal:"https://selfservice.nrs.gov.ng/registration",
    requirements:["CAC-incorporated business/entity details","Information requested by the NRS corporate registration flow"],
    steps:["Open the NRS taxpayer registration page.","Choose Corporate.","Complete the registration process shown by NRS."],
    notes:["The NRS portal separately lists Corporate, Individuals, Non-Resident and Free Trade Zone registration categories."], sources:[S.nrsRegister],
  }),
  guide({
    slug:"nrs-tax-clearance-certificate", title:"Where to access tax clearance on the NRS portal", shortTitle:"NRS tax clearance",
    summary:"NRS lists Tax Clearance among the services available from its taxpayer self-service portal.",
    category:"Tax", agencySlug:"nrs", feeLabel:"Depends on tax position/obligations",
    status:"verified", officialPortal:"https://selfservice.nrs.gov.ng/",
    requirements:["Registered NRS taxpayer account","Compliance information required by the NRS portal"],
    steps:["Sign in through the official NRS self-service portal.","Open the Tax Clearance service.","Follow the portal instructions for the taxpayer account."],
    notes:["The portal also provides self tax filing, payments, refunds, assessments and tax-wallet functions."], sources:[S.nrsPortal],
  }),,
  guide({
    slug:"cac-status-report", title:"How to obtain a CAC status report", shortTitle:"CAC status report",
    summary:"CAC lists status reports among its post-registration services and currently describes the service timeline as instant.",
    category:"Business", agencySlug:"cac", feeLabel:"See current CAC fee schedule",
    timeline:"CAC currently lists Status Report as an instant service.",
    status:"verified", officialPortal:"https://icrp.cac.gov.ng/",
    requirements:["Registered entity details requested by the CAC portal"],
    steps:["Sign in to the official CAC portal.","Open the relevant post-registration/status-report service.","Complete the request and official payment shown by CAC."],
    notes:["Use the current portal fee displayed for the entity/request type."], sources:[S.cacTimeline,S.cacPortal],
  }),
  guide({
    slug:"cac-certified-true-copy", title:"How to request a CAC Certified True Copy", shortTitle:"CAC Certified True Copy",
    summary:"CAC publishes Certified True Copy services among its post-registration processes.",
    category:"Business", agencySlug:"cac", feeLabel:"See current CAC fee schedule",
    timeline:"CAC currently lists Certified True Copy of Certificates under a 12-working-hour post-registration timeline.",
    status:"verified", officialPortal:"https://icrp.cac.gov.ng/",
    requirements:["Registered entity details","The document/certificate for which a certified copy is requested"],
    steps:["Sign in to the CAC registration portal.","Choose the applicable post-registration Certified True Copy service.","Complete the request and official payment."],
    notes:["Timelines assume a complete application and resolution of any CAC query."], sources:[S.cacTimeline,S.cacPortal],
  }),
  guide({
    slug:"jamb-direct-entry-2026", title:"How much is JAMB Direct Entry registration in 2026?", shortTitle:"2026 JAMB Direct Entry",
    summary:"JAMB's 2026 training manual states the Direct Entry e-PIN amount and uses the same profile-code foundation as its registration process.",
    category:"Education", agencySlug:"jamb", feeLabel:"₦5,700 e-PIN",
    feeNote:"JAMB's 2026 UTME training manual lists the Direct Entry e-PIN at ₦5,700.",
    status:"verified", officialPortal:"https://www.jamb.gov.ng",
    requirements:["NIN","JAMB profile code","Active phone number used for the candidate profile","Direct Entry eligibility/documents required by JAMB"],
    steps:["Create or refresh the JAMB profile code.","Purchase the Direct Entry e-PIN through an approved channel.","Complete registration through the JAMB process/accredited centre specified for the exercise."],
    notes:["Use JAMB's current-year instructions because registration windows and documentary checks can change."], sources:[S.jambManual,S.jambFaq],
  }),
  guide({
    slug:"jamb-reset-profile-password", title:"How to reset a JAMB profile password", shortTitle:"Reset JAMB password",
    summary:"JAMB publishes an SMS method for resetting a lost or forgotten profile password.",
    category:"Education", agencySlug:"jamb", feeLabel:"SMS/network charge may apply",
    status:"verified", officialPortal:"https://www.jamb.gov.ng",
    requirements:["The same mobile number tied to the JAMB profile","The email address on the profile"],
    steps:["From the linked mobile number, type PASSWORD, a space, then the email address.","Send the message to 55019 or 66019.","Use the returned/reset credentials as directed by JAMB."],
    notes:["The request should come from the phone number linked to the candidate profile."], sources:[S.jambFaq],
  }),
  guide({
    slug:"waec-correct-certificate-error", title:"How to request correction of an error on a WAEC certificate", shortTitle:"Correct WAEC certificate error",
    summary:"WAEC explains different submission routes for school and private candidates requesting certificate amendments.",
    category:"Education", agencySlug:"waec", feeLabel:"A fee may apply if the error came from the candidate",
    status:"verified", officialPortal:"https://www.waecnigeria.org",
    requirements:["Original certificate","Evidence supporting the requested correction","School-principal route for school candidates or direct WAEC request for private candidates"],
    steps:["School candidates should route the request through the school principal.","Private candidates should submit the amendment request directly to WAEC.","Include the original certificate and supporting documents requested by WAEC."],
    notes:["WAEC says amendments are charged where the error originated from the candidate; otherwise the correction is free."], sources:[S.waecFaq],
  }),
  guide({
    slug:"waec-result-confirmation-overseas", title:"How to confirm a WAEC result for an overseas institution", shortTitle:"WAEC overseas result confirmation",
    summary:"WAEC publishes requirements for sending confirmed results directly to overseas institutions, but one current page contains an apparent fee-text inconsistency.",
    category:"Education", agencySlug:"waec", feeLabel:"Official WAEC pages need fee confirmation",
    feeNote:"WAEC's FAQ states ₦39,000 per result/recipient for overseas institutions, while another current WAEC requirements page contains an inconsistent figure. Confirm the live payable amount with WAEC before payment.",
    status:"conflict", officialPortal:"https://www.waecnigeria.org/article/requirements-confirmation-result-school-candidates",
    requirements:["Copy of certificate or online result printout","Sworn affidavit","Two recent passport photographs","Two 9x4 envelopes","WAEC scratch card as specified by WAEC"],
    steps:["Prepare WAEC's listed confirmation documents.","Confirm the current overseas administrative charge directly with WAEC.","Complete the official process and courier arrangements."],
    notes:["WAEC sends confirmed results directly to the institution/establishment rather than handing them to the candidate."], sources:[S.waecConfirm,S.waecFaq],
  }),
  guide({
    slug:"neco-institution-verification", title:"How institutions verify NECO results with e-Verify", shortTitle:"NECO institution verification",
    summary:"NECO e-Verify supports institutional single/bulk verification and API integration.",
    category:"Education", agencySlug:"neco", feeLabel:"Verification payment/token required",
    status:"verified", officialPortal:"https://everify.neco.gov.ng/index.php",
    requirements:["Institution e-Verify account","Candidate examination details","Payment token/RRR as applicable"],
    steps:["Create or sign in to the institution e-Verify account.","Generate/validate the required payment token.","Submit the candidate verification request or use the supported institutional/API route."],
    notes:["NECO states that institutions can carry out single or bulk verification and can integrate through its e-Verify API."], sources:[S.necoVerify],
  }),
  guide({
    slug:"nysc-senate-list", title:"How to check the NYSC senate list", shortTitle:"NYSC senate list",
    summary:"The official NYSC portal provides a Senate List check for prospective corps members.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"No separate fee stated for the list check",
    status:"verified", officialPortal:"https://portal.nysc.org.ng/nysc/",
    requirements:["Institution/graduation details requested by the NYSC check"],
    steps:["Open the official NYSC portal.","Choose Check Senate List.","Enter the requested details and review the result."],
    notes:["NYSC states locally trained graduates must appear on the Senate/Academic Board Approved Result list to access registration."], sources:[S.nyscPortal,S.nyscLocal],
  }),
  guide({
    slug:"nysc-call-up-letter", title:"How to access an NYSC call-up letter", shortTitle:"NYSC call-up letter",
    summary:"NYSC explains that successful mobilisation produces a call-up number and subsequently a call-up letter.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"Portal printing/subscription rules apply",
    status:"verified", officialPortal:"https://portal.nysc.org.ng/nysc/",
    requirements:["Successful NYSC registration/mobilisation","Access to the candidate NYSC dashboard"],
    steps:["Complete NYSC registration and mobilisation.","Sign in to the official NYSC portal when deployment documents are released.","Download/print the call-up letter if your registration route provides online printing."],
    notes:["NYSC says those who do not subscribe for online call-up-letter printing collect through their institutions where applicable."], sources:[S.nyscPortal,S.nyscMobilise],
  }),
  guide({
    slug:"nysc-exemption-certificate", title:"How NYSC exemption certificates are issued and collected", shortTitle:"NYSC exemption certificate",
    summary:"NYSC determines exemption classification during registration and publishes collection/correction rules.",
    category:"Youth service", agencySlug:"nysc", feeLabel:"No general certificate fee stated on NYSC guidance",
    status:"verified", officialPortal:"https://www.nysc.gov.ng/certcollectexp.html",
    requirements:["NYSC registration/classification as exempted","Identification required for collection","For foreign graduates, physical presence at the communicated collection process"],
    steps:["Complete NYSC registration so exemption status can be determined.","Follow the collection instructions communicated by NYSC for the relevant service batch.","Present the required identification in person where NYSC requires it."],
    notes:["NYSC says foreign graduates collect exemption certificates at the Directorate Headquarters at the stipulated time and must be physically present."], sources:[S.nyscExempt],
  }),
  guide({
    slug:"npc-check-attestation-status", title:"How to check NPC birth-attestation status", shortTitle:"NPC attestation status",
    summary:"NPC's attestation service uses the payment reference to check status and download an approved certificate.",
    category:"Civil records", agencySlug:"npc", feeLabel:"No extra status-check fee stated",
    status:"verified", officialPortal:"https://attestation.nationalpopulation.gov.ng/",
    requirements:["Payment reference from the birth-attestation application"],
    steps:["Open the official NPC birth-attestation service.","Choose Check Status.","Enter the payment reference.","Download the certificate when the application has been successfully completed/approved."],
    notes:["NPC says the status feature works after the birth-attestation process has been successfully completed."], sources:[S.npcAttest,S.npcVital],
  }),
  guide({
    slug:"nrs-self-tax-filing", title:"Where to file tax through NRS self-service", shortTitle:"NRS self tax filing",
    summary:"NRS lists Self Tax Filing as a service in its federal taxpayer self-service portal.",
    category:"Tax", agencySlug:"nrs", feeLabel:"Tax liability depends on the taxpayer",
    status:"verified", officialPortal:"https://selfservice.nrs.gov.ng/",
    requirements:["Registered NRS taxpayer account","Tax information/documents required for the filing period"],
    steps:["Sign in to the official NRS self-service portal.","Open Self Tax Filing.","Complete the filing workflow for the taxpayer account."],
    notes:["The portal also provides assessments, payments, tax clearance and other taxpayer functions."], sources:[S.nrsPortal],
  }),
  guide({
    slug:"nrs-tax-payment", title:"Where to make a federal tax payment through NRS", shortTitle:"NRS tax payment",
    summary:"NRS includes secure Payments among the services in its taxpayer self-service portal.",
    category:"Tax", agencySlug:"nrs", feeLabel:"Amount depends on the taxpayer's liability/assessment",
    status:"verified", officialPortal:"https://selfservice.nrs.gov.ng/",
    requirements:["Registered NRS taxpayer account","Relevant assessment/liability details"],
    steps:["Sign in to the official NRS self-service portal.","Open Payments.","Review the taxpayer liability/payment details and use the official payment route."],
    notes:["Confirm that the liability belongs to the correct taxpayer/account before paying."], sources:[S.nrsPortal],
  }),
  guide({
    slug:"nrs-refund-tracking", title:"How to track a tax refund on the NRS portal", shortTitle:"NRS refund tracking",
    summary:"NRS lists Refunds among the functions in its taxpayer self-service portal.",
    category:"Tax", agencySlug:"nrs", feeLabel:"No tracking fee stated on the portal overview",
    status:"verified", officialPortal:"https://selfservice.nrs.gov.ng/",
    requirements:["Registered NRS taxpayer account","Existing refund request/details where applicable"],
    steps:["Sign in to the official NRS self-service portal.","Open Refunds.","Review or track the refund request shown for the taxpayer account."],
    notes:["Refund eligibility and processing depend on the underlying tax record."], sources:[S.nrsPortal],
  }),
  guide({
    slug:"passport-change-marital-status", title:"How to change Nigerian passport data after a change in marital status", shortTitle:"Passport marital-status change",
    summary:"NIS publishes a specific change-of-data route for marital-status-related passport updates.",
    category:"Immigration", agencySlug:"nis", feeLabel:"Official application/administrative charges apply",
    status:"verified", officialPortal:"https://passport.gov.ng",
    requirements:["Birth certificate from NPC or High Court declaration of age","State-of-origin certificate","Application letter","Marriage certificate","Court affidavit","Newspaper publication","Current passport data page"],
    steps:["Complete the passport application online.","Upload the documents NIS lists for marital-status change.","Submit payment and appointment slips at the selected passport office on the appointment date.","Attend in person with the current passport booklet for biometrics."],
    notes:["Nigerians in the diaspora are directed to the nearest Nigerian Embassy, High Commission or Consulate."], sources:[S.nisPassports],
  }),
  guide({
    slug:"passport-name-change", title:"How to add, delete, replace or rearrange names on a Nigerian passport", shortTitle:"Passport name change",
    summary:"NIS groups replacement, addition, deletion and rearrangement of names under its passport change-of-data guidance.",
    category:"Immigration", agencySlug:"nis", feeLabel:"Non-refundable administrative charge applies",
    status:"verified", officialPortal:"https://passport.gov.ng",
    requirements:["Birth certificate from NPC or High Court declaration of age","Application letter","Newspaper publication","State-of-origin certificate","Court affidavit","Current passport data page"],
    steps:["Complete the official passport application.","Pay the administrative charge shown by NIS.","Upload the supporting documents.","Attend the chosen passport office with the current passport booklet for biometrics."],
    notes:["The exact supporting evidence should match the requested name change."], sources:[S.nisPassports],
  }),
  guide({
    slug:"official-nigerian-passport", title:"Who is eligible for a Nigerian official passport?", shortTitle:"Nigerian official passport",
    summary:"NIS publishes eligibility categories and supporting requirements for the blue official passport.",
    category:"Immigration", agencySlug:"nis", feeLabel:"Official-process fee depends on NIS/government route",
    status:"verified", officialPortal:"https://immigration.gov.ng/passports/",
    requirements:["Letter of application/introduction from the applicant's organisation","Two passport photographs","Last promotion letter or letter of appointment","Valid official identity card","Evidence of age","INEC/State Electoral Commission return certificate where applicable"],
    steps:["Confirm that the applicant falls within an NIS-listed eligible official category.","Prepare the organisation and identity documents.","Follow the official NIS application channel for official passports."],
    notes:["Eligibility is restricted to the government/public-office categories published by NIS."], sources:[S.nisPassports],
  }),
  guide({
    slug:"passport-application-abroad", title:"How Nigerians abroad apply for or renew a Nigerian passport", shortTitle:"Passport application abroad",
    summary:"NIS directs Nigerians in the diaspora to submit passport applications through the nearest Nigerian Embassy, High Commission or Consulate.",
    category:"Immigration", agencySlug:"nis", feeLabel:"Diaspora fees/process depend on the relevant mission and passport route",
    status:"verified", officialPortal:"https://passportintl.immigration.gov.ng",
    requirements:["Passport application documents for the relevant fresh/renewal/change-of-data route","Mission-specific appointment/submission requirements"],
    steps:["Use the NIS international passport application route.","Complete the relevant online application.","Follow the nearest Nigerian mission's instructions for submission, appointment and biometrics."],
    notes:["Do not assume Nigeria-local passport fees apply to an application processed abroad."], sources:[S.nisPassports],
  })
];

const reviewQueue: Service[] = [
  review("lost-nigerian-passport","What to do if a Nigerian passport is lost","Lost Nigerian passport","Immigration","nis","https://passport.gov.ng",[S.nisPassports]),
  review("nin-enrolment","How to enrol for NIN","NIN enrolment","Identity","nimc","https://nimc.gov.ng",[S.nimcHome]),
  review("nin-slip-reissue","How to reissue a NIN slip","NIN slip reissue","Identity","nimc","https://nimc.gov.ng",[S.nimcHome]),
  review("nin-name-modification","How to change a name on NIN","NIN name modification","Identity","nimc","https://nimc.gov.ng",[S.nimcHome,S.nimcFees]),
  review("nin-phone-modification","How to change a phone number on NIN","NIN phone modification","Identity","nimc","https://nimc.gov.ng",[S.nimcHome,S.nimcFees]),
  review("nin-address-modification","How to change an address on NIN","NIN address modification","Identity","nimc","https://nimc.gov.ng",[S.nimcHome,S.nimcFees]),
  review("cac-status-report","How to obtain a CAC status report","CAC status report","Business","cac","https://icrp.cac.gov.ng/",[S.cacTimeline,S.cacPortal]),
  review("cac-certified-true-copy","How to request CAC certified true copies","CAC certified true copy","Business","cac","https://icrp.cac.gov.ng/",[S.cacTimeline,S.cacPortal]),
  review("jamb-direct-entry-2026","How JAMB Direct Entry registration works in 2026","2026 JAMB Direct Entry","Education","jamb","https://www.jamb.gov.ng",[S.jambManual,S.jambFaq]),
  review("jamb-reset-profile-password","How to reset a JAMB profile password","Reset JAMB password","Education","jamb","https://www.jamb.gov.ng",[S.jambFaq]),
  review("jamb-print-result","How to print a JAMB result slip","JAMB result slip","Education","jamb","https://efacility.jamb.gov.ng",[S.jambFaq]),
  review("jamb-admission-letter","How to print a JAMB admission letter","JAMB admission letter","Education","jamb","https://efacility.jamb.gov.ng",[S.jambCaps]),
  review("waec-correct-certificate-error","How to correct an error on a WAEC certificate","Correct WAEC certificate error","Education","waec","https://www.waecnigeria.org",[S.waecFaq]),
  review("waec-result-confirmation-overseas","How to confirm WAEC results for an overseas institution","WAEC overseas confirmation","Education","waec","https://www.waecnigeria.org",[S.waecConfirm,S.waecFaq]),
  review("waec-withheld-result-complaint","How to lodge a WAEC withheld-result complaint","WAEC withheld result complaint","Education","waec","https://www.waecnigeria.org",[S.waecFaq]),
  review("neco-institution-verification","How institutions verify NECO results","NECO institution verification","Education","neco","https://everify.neco.gov.ng",[S.necoVerify]),
  review("neco-certificate-service","How to request NECO certificate-related services","NECO certificate service","Education","neco","https://www.neco.gov.ng",[S.necoPay]),
  review("nysc-senate-list","How to check the NYSC senate list","NYSC senate list","Youth service","nysc","https://portal.nysc.org.ng/nysc/",[S.nyscPortal,S.nyscLocal]),
  review("nysc-call-up-letter","How to access an NYSC call-up letter","NYSC call-up letter","Youth service","nysc","https://portal.nysc.org.ng/nysc/",[S.nyscPortal,S.nyscMobilise]),
  review("nysc-correct-date-of-birth","How NYSC date-of-birth correction works","NYSC DOB correction","Youth service","nysc","https://portal.nysc.org.ng/nysc/",[S.nyscPortal]),
  review("nysc-correct-course-of-study","How NYSC course-of-study correction works","NYSC course correction","Youth service","nysc","https://portal.nysc.org.ng/nysc/",[S.nyscPortal]),
  review("nysc-exemption-certificate","How NYSC exemption certificates are issued","NYSC exemption certificate","Youth service","nysc","https://www.nysc.gov.ng",[S.nyscExempt]),
  review("npc-modify-birth-record","How to modify an NPC birth record","NPC record modification","Civil records","npc","https://www.nationalpopulation.gov.ng",[S.npcFaq]),
  review("npc-check-attestation-status","How to check NPC birth-attestation status","NPC attestation status","Civil records","npc","https://attestation.nationalpopulation.gov.ng",[S.npcAttest,S.npcVital]),
  review("nrs-self-tax-filing","How to file tax through NRS self-service","NRS self tax filing","Tax","nrs","https://selfservice.nrs.gov.ng/",[S.nrsPortal]),
  review("nrs-tax-payment","How to make a payment through NRS self-service","NRS tax payment","Tax","nrs","https://selfservice.nrs.gov.ng/",[S.nrsPortal]),
  review("nrs-refund-tracking","How to track an NRS tax refund","NRS refund tracking","Tax","nrs","https://selfservice.nrs.gov.ng/",[S.nrsPortal]),
];

const publishedSlugs = new Set(published.map((service) => service.slug));
export const services: Service[] = [...published, ...reviewQueue.filter((service) => !publishedSlugs.has(service.slug))];
export const publicServices = services.filter((service) => service.status !== "review");

export const categories = [
  { name:"Identity", description:"NIN and identity record services." },
  { name:"Immigration", description:"Passports and immigration processes." },
  { name:"Driving", description:"Driver's licence services." },
  { name:"Business", description:"CAC registration and corporate filings." },
  { name:"Education", description:"JAMB, WAEC and NECO services." },
  { name:"Youth service", description:"NYSC mobilisation and certificate services." },
  { name:"Civil records", description:"Birth registration and certificate services." },
  { name:"Tax", description:"Federal taxpayer self-service." },
];

export function getAgency(slug:string) { return agencies.find((agency) => agency.slug === slug); }
export function getService(slug:string) { return services.find((service) => service.slug === slug); }
export function getPublicService(slug:string) { return publicServices.find((service) => service.slug === slug); }
export function getServicesByAgency(slug:string, includeReview = false) {
  return (includeReview ? services : publicServices).filter((service) => service.agencySlug === slug);
}
export function getServicesByStatus(status:VerificationStatus) { return services.filter((service) => service.status === status); }
