export type EntertainmentPlatform = "Netflix" | "YouTube" | "Prime Video" | "Kava" | "Cinema";

export type WatchLink = {
  platform: EntertainmentPlatform;
  label: string;
  href: string;
  access: "subscription" | "full-movie" | "rent-or-buy" | "subscription-or-rent" | "cinema";
  lastChecked: string;
  note: string;
  publisher?: string;
  publisherUrl?: string;
};

export type TrailerLink = {
  label: string;
  href: string;
  platform: "YouTube";
  lastChecked: string;
  publisher?: string;
  publisherUrl?: string;
};

export type EntertainmentImageUsageBasis =
  | "press-kit-permission"
  | "direct-permission"
  | "licensed"
  | "creative-commons";

export type EntertainmentArtwork = {
  url: string;
  sourceUrl: string;
  credit: string;
  usageBasis: EntertainmentImageUsageBasis;
  licenseNote: string;
  lastChecked: string;
  status: "approved";
};

export type EntertainmentTitle = {
  slug: string;
  title: string;
  year: number;
  format: "movie";
  genres: string[];
  languages: string[];
  synopsis: string;
  cast: string[];
  featuredCast?: string[];
  directors?: string[];
  runtimeMinutes?: number;
  trailer?: TrailerLink;
  artwork?: EntertainmentArtwork;
  featured?: boolean;
  watchLinks: WatchLink[];
};

export const entertainmentTitles: EntertainmentTitle[] = [
  {
    slug: "agbara-nla-the-return",
    title: "Agbara Nla: The Return",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Faith", "Fantasy", "Nollywood"],
    languages: ["Yoruba", "English"],
    synopsis: "Olaboye and Olatomi leave city life for Muwonleru, where their mission confronts the dark influence of herbalist Isawuru and forces the community into a spiritual battle over faith, sacrifice and restoration.",
    cast: ["Mike Bamiloye", "Yemi Adepoju", "Mosiko Remilekun Adesina", "Omolara Ayoola", "Gloria Bamiloye"],
    directors: ["Damilola Mike-Bamiloye", "Joshua Bamiloye"],
    runtimeMinutes: 157,
    featured: true,
    watchLinks: [
      {
        platform: "Cinema",
        label: "See current Silverbird showtimes",
        href: "https://silverbirdcinemas.com/movie/agbara-nla-the-return/",
        access: "cinema",
        lastChecked: "2026-10-04",
        note: "Silverbird lists the film in Nigerian cinemas. Showtime and location availability can change."
      }
    ]
  },
  {
    slug: "first-lady-2026",
    title: "First Lady",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Political", "Nollywood"],
    languages: ["English"],
    synopsis: "Adunola, the First Lady of Lagos State, appears to have status and influence but is privately consumed by her desire for a child, and a long-awaited pregnancy threatens her marriage, reputation and carefully controlled public life.",
    cast: ["Fehintola Olulana", "Desmond Elliot", "Ibrahim Suleiman", "Ngozi Nwosu", "Jaiye Kuti", "Abiola Segun-Williams", "Oluwakemi Iyanda"],
    directors: ["Yinka Akanbi"],
    watchLinks: [
      {
        platform: "Cinema",
        label: "Check the distributor release page",
        href: "https://www.tntheatrical.com/post/desmond-elliot-ibrahim-suleiman-and-fehintola-olulana-lead-new-political-drama-first-lady-in-cinem",
        access: "cinema",
        lastChecked: "2026-10-04",
        note: "Tribe Nation Theatrical Distribution lists the West African cinema release for 16 October 2026."
      }
    ]
  },
  {
    slug: "anikulapo",
    title: "Aníkúlápó",
    year: 2022,
    format: "movie",
    genres: ["Drama", "Period", "Nollywood"],
    languages: ["Yoruba", "English"],
    synopsis: "After an affair with a queen leads to his death, a traveller encounters a mystical bird with the power to give him another life.",
    cast: ["Kunle Remi", "Bimbo Ademoye", "Hakeem Kae-Kazim"],
    directors: ["Kunle Afolayan"],
    trailer: {
      label: "Watch the official trailer",
      href: "https://www.youtube.com/watch?v=rXIKrHPaB-o",
      platform: "YouTube",
      lastChecked: "2026-09-29",
    },
    featured: true,
    watchLinks: [
      {
        platform: "Netflix",
        label: "Watch on Netflix",
        href: "https://www.netflix.com/ng/title/81392197",
        access: "subscription",
        lastChecked: "2026-09-29",
        note: "Official Netflix title page. Availability and plan requirements can change.",
      },
    ],
  },
  {
    slug: "oloture",
    title: "Òlòtūré",
    year: 2020,
    format: "movie",
    genres: ["Drama", "Social issues", "Nollywood"],
    languages: ["English"],
    synopsis: "A journalist goes undercover in Lagos while investigating human trafficking and encounters a dangerous world of exploitation.",
    cast: ["Sharon Ooja", "Omoni Oboli", "Blossom Chukwujekwu"],
    directors: ["Kenneth Gyang"],
    featured: true,
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=2UnCt9cKwS0",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [
      {
        platform: "Netflix",
        label: "Watch on Netflix",
        href: "https://www.netflix.com/ng/title/81300126",
        access: "subscription",
        lastChecked: "2026-09-29",
        note: "Official Netflix title page. Availability and plan requirements can change.",
      },
    ],
  },
  {
    slug: "blood-vessel",
    title: "Blood Vessel",
    year: 2023,
    format: "movie",
    genres: ["Thriller", "Drama", "Nollywood"],
    languages: ["Ijaw", "English"],
    synopsis: "Six people fleeing a community devastated by oil pollution stow away on a mysterious ship and discover new dangers onboard.",
    cast: ["Adaobi Dibor", "David Ezekiel", "Sylvester Ekanem"],
    featured: true,
    watchLinks: [
      {
        platform: "Netflix",
        label: "Watch on Netflix",
        href: "https://www.netflix.com/title/81676887",
        access: "subscription",
        lastChecked: "2026-09-29",
        note: "Official Netflix title page. Regional availability can change.",
      },
    ],
  },
  {
    slug: "the-black-book",
    title: "The Black Book",
    year: 2023,
    format: "movie",
    genres: ["Thriller", "Action", "Crime"],
    languages: ["English"],
    synopsis: "After his son is framed for kidnapping, a grieving deacon confronts a corrupt police gang while trying to clear his son's name.",
    cast: ["Richard Mofe-Damijo", "Ade Laoye", "Sam Dede"],
    featured: true,
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=6PPH4SOm9gk",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [
      {
        platform: "Netflix",
        label: "Watch on Netflix",
        href: "https://www.netflix.com/title/81698992",
        access: "subscription",
        lastChecked: "2026-09-29",
        note: "Official Netflix title page. Regional availability can change.",
      },
    ],
  },
  {
    slug: "ijogbon",
    title: "Ìjọ̀gbọ̀n",
    year: 2023,
    format: "movie",
    genres: ["Drama", "Teen", "Nollywood"],
    languages: ["Yoruba", "English"],
    synopsis: "Four teenagers from a rural South West Nigerian village find a pouch of uncut diamonds and quickly discover that others are searching for the same bounty.",
    cast: ["Fawaz Aina", "Ebiesuwa Oluwaseyi", "Ruby Akubueze"],
    directors: ["Kunle Afolayan"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=ocOjEtqq_Nw",
      platform: "YouTube",
      lastChecked: "2026-09-29",
    },
    watchLinks: [
      {
        platform: "Netflix",
        label: "Watch on Netflix",
        href: "https://www.netflix.com/ng/title/81671712",
        access: "subscription",
        lastChecked: "2026-09-29",
        note: "Official Netflix Nigeria title page.",
      },
    ],
  },
  {
    slug: "a-lagos-love-story",
    title: "A Lagos Love Story",
    year: 2025,
    format: "movie",
    genres: ["Romance", "Comedy", "Nollywood"],
    languages: ["English"],
    synopsis: "An aspiring Lagos event planner is pushed into the orbit of a rising Afrobeats star and finds her professional assignment becoming personal.",
    cast: ["Jemima Osunde", "Mike Afolarin", "Susan Pwajok"],
    directors: ["Chinaza Onuzo"],
    runtimeMinutes: 104,
    featured: true,
    watchLinks: [
      {
        platform: "Prime Video",
        label: "Open on Prime Video",
        href: "https://www.primevideo.com/detail/0QKNHEFWV4SEKZ4OFQFAYWKWCN",
        access: "subscription-or-rent",
        lastChecked: "2026-09-29",
        note: "Official Prime Video title page. The exact subscription, rental or purchase option can depend on region.",
      },
    ],
  },
  {
    slug: "pieces-that-fit",
    title: "Pieces That Fit",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A woman rebuilding her life after abuse and loss finds an unexpected path toward healing while living and working around people carrying their own grief.",
    cast: ["Micheal Dappa", "Ekama Etim-Inyang", "Ehis Perfect", "Floyd Igbo"],
    watchLinks: [
      {
        platform: "YouTube",
        label: "Watch the full movie on YouTube",
        href: "https://www.youtube.com/watch?v=W0YCyyBMyAw",
        access: "full-movie",
        lastChecked: "2026-09-29",
        note: "Full movie published by Omoni Oboli TV.",
      },
    ],
  },
  {
    slug: "what-love-is",
    title: "What Love Is",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A contemporary romance about trust, uncertainty and relationship pressure, led by Maurice Sam and Erica Nlewedim.",
    cast: ["Maurice Sam", "Erica Nlewedim"],
    featured: true,
    watchLinks: [
      {
        platform: "YouTube",
        label: "Watch the full movie on YouTube",
        href: "https://www.youtube.com/watch?v=ORIBBpN7YMs",
        access: "full-movie",
        lastChecked: "2026-09-29",
        note: "Full movie published by verified Maurice Sam TV.",
      },
    ],
  },
  {
    slug: "irreplaceable",
    title: "Irreplaceable",
    year: 2024,
    format: "movie",
    genres: ["Romance", "Family", "Nollywood"],
    languages: ["English"],
    synopsis: "A responsible teenager tries to find her mother a partner, pulling a school rival into a plan that changes how they think about love and family.",
    cast: ["John Ekanem", "Emmanuel Nse", "Angel Unigwe", "Betcy Amilo", "Rejoice Rejme"],
    featured: true,
    watchLinks: [
      {
        platform: "YouTube",
        label: "Watch the full movie on YouTube",
        href: "https://www.youtube.com/watch?v=a-TfeLSnveE",
        access: "full-movie",
        lastChecked: "2026-09-29",
        note: "Full movie published by Omoni Oboli TV on its official YouTube channel.",
      },
    ],
  },
  {
    slug: "plus-one",
    title: "Plus One",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A pretend relationship arranged for a family gathering becomes more complicated when the connection starts to feel real.",
    cast: ["Saga Adeolu", "Sophia Chisom", "Ayo Adesanya", "Symon Oko"],
    featured: true,
    watchLinks: [
      {
        platform: "YouTube",
        label: "Watch the full movie on YouTube",
        href: "https://www.youtube.com/watch?v=fY28a7s3ThU",
        access: "full-movie",
        lastChecked: "2026-09-29",
        note: "Full movie published by Omoni Oboli TV on its official YouTube channel.",
      },
    ],
  },

  {
    slug: "jagun-jagun",
    title: "Jagun Jagun",
    year: 2023,
    format: "movie",
    genres: ["Action", "Drama", "Period", "Nollywood"],
    languages: ["Yoruba", "English"],
    synopsis: "A young man joins an elite warrior school to pursue power, only to collide with a ruthless warlord and a dangerous love story.",
    cast: ["Femi Adebayo", "Lateef Adedimeji", "Odunlade Adekola", "Ibrahim Yekini Itele", "Bukunmi Oluwashina", "Adebayo Salami", "Fathia Balogun", "Muyiwa Ademola", "Yinka Quadri", "Debo Adedayo"],
    featuredCast: ["Femi Adebayo", "Lateef Adedimeji", "Odunlade Adekola"],
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81681240", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "lionheart",
    title: "Lionheart",
    year: 2018,
    format: "movie",
    genres: ["Drama", "Comedy", "Nollywood"],
    languages: ["English"],
    synopsis: "When her father falls ill, Adaeze takes on the family transport business and must prove herself in a male-dominated environment.",
    cast: ["Genevieve Nnaji", "Nkem Owoh", "Pete Edochie", "Onyeka Onwenu", "Kanayo O. Kanayo"],
    featuredCast: ["Genevieve Nnaji", "Nkem Owoh", "Pete Edochie"],
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81030789", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "swallow",
    title: "Swallow",
    year: 2021,
    format: "movie",
    genres: ["Drama", "Social issues", "Nollywood"],
    languages: ["English"],
    synopsis: "Under pressure in 1980s Lagos, a young woman is drawn into drug smuggling and must deal with the consequences.",
    cast: ["Eniola 'Niyola' Akinbo", "Ijeoma Grace Agu", "Deyemi Okanlawon", "Chioma Chukwuka Akpotha", "Eniola Badmus", "Kevin Ikeduba", "Mercy Aigbe"],
    featuredCast: ["Eniola 'Niyola' Akinbo", "Deyemi Okanlawon", "Chioma Chukwuka Akpotha"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=WH19OJ7k270",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81392180", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "man-of-god",
    title: "Man of God",
    year: 2022,
    format: "movie",
    genres: ["Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A man who rejected a strict religious upbringing struggles to reconcile the life he chose with the faith he left behind.",
    cast: ["Akah Nnani", "Osas Ighodaro", "Atlanta Bridget Johnson", "Dorcas Shola Fapson", "Jude Chukwuka", "Ayo Mogaji", "Olumide Oworu", "Patrick Doyle", "Eucharia Anunobi", "Mawuli Gavor"],
    featuredCast: ["Akah Nnani", "Osas Ighodaro", "Olumide Oworu"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=E5ugUvUTFpE",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81572291", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "citation",
    title: "Citation",
    year: 2020,
    format: "movie",
    genres: ["Drama", "Social issues", "Nollywood"],
    languages: ["English"],
    synopsis: "A university student challenges the academic establishment after reporting sexual misconduct by a respected professor.",
    cast: ["Temi Otedola", "Jimmy Jean-Louis", "Joke Silva", "Gabriel Afolayan", "Adjetey Anang", "Ini Edo", "Sadiq Daba", "Yomi Fash-Lanso", "Bukunmi Oluwashina"],
    featuredCast: ["Temi Otedola", "Joke Silva", "Ini Edo"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=1eMAYynMc1w",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81294345", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "glamour-girls",
    title: "Glamour Girls",
    year: 2022,
    format: "movie",
    genres: ["Drama", "Social issues", "Nollywood"],
    languages: ["English"],
    synopsis: "A group of women enter a world of wealth and high-end escorts, but violence and theft put their lives and ambitions at risk.",
    cast: ["Nse Ikpe-Etim", "Sharon Ooja", "Joselyn Dumas", "Toke Makinwa", "Segilola Ogidan", "James Gardiner"],
    featuredCast: ["Nse Ikpe-Etim", "Sharon Ooja", "Joselyn Dumas"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=XnyuqAJ9_kI",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81478629", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix title page." }],
  },
  {
    slug: "elesin-oba",
    title: "Ẹlẹṣin Ọba: The King's Horseman",
    year: 2022,
    format: "movie",
    genres: ["Drama", "Period", "Nollywood"],
    languages: ["Yoruba", "English"],
    synopsis: "Following the death of a king, the royal horseman faces a sacred duty whose disruption sets tragedy in motion.",
    cast: ["Odunlade Adekola", "Shaffy Bello", "Deyemi Okanlawon", "Omowunmi Dada", "Jide Kosoko", "Olawale 'Brymo' Olofooro"],
    featuredCast: ["Odunlade Adekola", "Shaffy Bello", "Deyemi Okanlawon"],
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81332042", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "a-naija-christmas",
    title: "A Naija Christmas",
    year: 2021,
    format: "movie",
    genres: ["Comedy", "Romance", "Family", "Nollywood"],
    languages: ["English"],
    synopsis: "Three brothers compete to fulfil their mother's Christmas wish, turning the festive season into a chaotic race for love and approval.",
    cast: ["Rachel Oniga", "Kunle Remi", "Segilola Ogidan", "Efa Iwara", "Linda Osifo", "Mercy Johnson Okojie", "Lateef Adedimeji"],
    featuredCast: ["Rachel Oniga", "Kunle Remi", "Mercy Johnson Okojie"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=0pzE10-3nzI",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81434660", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "chief-daddy",
    title: "Chief Daddy",
    year: 2018,
    format: "movie",
    genres: ["Comedy", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "After a wealthy patriarch dies unexpectedly, his relatives, friends and staff scramble over the fortune he leaves behind.",
    cast: ["Taiwo Obileye", "Joke Silva", "Falz", "Dakore Egbuson-Akande", "Funke Akindele", "Zainab Balogun", "Shaffy Bello", "Ini Edo", "Mawuli Gavor"],
    featuredCast: ["Joke Silva", "Funke Akindele", "Falz"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=S00tp6ZnLhk",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81074015", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "chief-daddy-2",
    title: "Chief Daddy 2 - Going for Broke",
    year: 2021,
    format: "movie",
    genres: ["Comedy", "Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "The Beecroft family returns to fight over Chief Daddy's inheritance while a determined company executive complicates their plans.",
    cast: ["Shaffy Bello", "Funke Akindele", "Joke Silva", "Kate Henshaw-Nuttal", "Rahama Sadau", "Mawuli Gavor", "Beverly Naya", "Falz"],
    featuredCast: ["Shaffy Bello", "Funke Akindele", "Joke Silva"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=9OG-NzwzOYQ",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81323628", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "king-of-boys",
    title: "King of Boys",
    year: 2018,
    format: "movie",
    genres: ["Crime", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A powerful businesswoman's political ambitions collide with her underworld connections, triggering a brutal struggle for power.",
    cast: ["Sola Sobowale", "Adesua Etomi", "Remilekun 'Reminisce' Safaru", "Tobechukwu 'iLLbliss' Ejiofor", "Toni Tones", "Jide Kosoko", "Sharon Ooja"],
    featuredCast: ["Sola Sobowale", "Adesua Etomi", "Remilekun 'Reminisce' Safaru"],
    trailer: {
      label: "Watch the official trailer",
      href: "https://www.youtube.com/watch?v=cF-FQLKaUCk",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "Kemi Adetiba Visuals",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81172721", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "merry-men-3",
    title: "Merry Men 3: Nemesis",
    year: 2023,
    format: "movie",
    genres: ["Thriller", "Crime", "Nollywood"],
    languages: ["English"],
    synopsis: "After a devastating loss, a wealthy group of friends set out for revenge against the people they hold responsible.",
    cast: ["Ramsey Nouah", "Chidi Mokeme", "Iretiola Doyle", "Ayo Makun", "Ufuoma McDermott", "Uchemba Williams", "Nadia Buari", "Segun Arinze"],
    featuredCast: ["Ramsey Nouah", "Chidi Mokeme", "Iretiola Doyle"],
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81689059", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "house-of-gaa",
    title: "House of Ga'a",
    year: 2024,
    format: "movie",
    genres: ["Action", "Drama", "Period", "Nollywood"],
    languages: ["Yoruba", "English"],
    synopsis: "At the height of the Oyo Empire, Bashorun Ga'a rises above the kings he helps install until power and family turn against him.",
    cast: ["Femi Branch", "Mike Afolarin", "Funke Akindele", "Femi Adebayo", "Ibrahim Chatta", "Toyin Abraham", "Bimbo Manuel", "Lateef Adedimeji"],
    featuredCast: ["Femi Branch", "Mike Afolarin", "Funke Akindele"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=I6uNj0Zlak8",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81681233", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "hijack-93",
    title: "Hijack '93",
    year: 2024,
    format: "movie",
    genres: ["Drama", "Thriller", "Historical", "Nollywood"],
    languages: ["English"],
    synopsis: "Four men hijack an aircraft in a politically charged attempt to challenge a military-backed government.",
    cast: ["Nancy Isime", "Sharon Ooja", "Jemima Osunde", "Idia Aisien", "Efa Iwara", "John Dumelo"],
    featuredCast: ["Nancy Isime", "Sharon Ooja", "Jemima Osunde"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=rNJzWqKUlwM",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81676888", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "afamefuna",
    title: "Áfàméfùnà: An Nwa Boi Story",
    year: 2023,
    format: "movie",
    genres: ["Drama", "Nollywood"],
    languages: ["Igbo"],
    synopsis: "A successful man questioned after a friend's death looks back on their complicated history inside the Igbo apprenticeship system.",
    cast: ["Stan Nze", "Kanayo O. Kanayo", "Alexx Ekubo", "Atlanta Bridget Johnson", "Segun Arinze", "Chuks Joseph"],
    featuredCast: ["Stan Nze", "Kanayo O. Kanayo", "Alexx Ekubo"],
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81730157", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "the-set-up",
    title: "The Set Up",
    year: 2019,
    format: "movie",
    genres: ["Crime", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A con artist recruits a young woman into a scheme targeting a wealthy heiress, but personal vendettas quickly complicate the plan.",
    cast: ["Adesua Etomi", "Jim Iyke", "Dakore Egbuson-Akande", "Ayoola Ayolola", "Tina Mba", "Joke Silva", "Kehinde Bankole"],
    featuredCast: ["Adesua Etomi", "Jim Iyke", "Dakore Egbuson-Akande"],
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81270837", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix title page." }],
  },

  {
    slug: "amina",
    title: "Amina",
    year: 2021,
    format: "movie",
    genres: ["Drama", "Action", "Period", "Nollywood"],
    languages: ["English"],
    synopsis: "In 16th-century Zazzau, a gifted warrior uses her military skill and strategy to defend her family's kingdom.",
    cast: ["Lucy Ameh", "Ali Nuhu", "Clarion Chukwura", "Chris Gbakann", "Yakubu Mohammed", "Habiba Ummi Mohammed"],
    featuredCast: ["Lucy Ameh", "Ali Nuhu", "Clarion Chukwura"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=RW87asYGq7g",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81450071", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "tokunbo",
    title: "Tòkunbọ̀",
    year: 2024,
    format: "movie",
    genres: ["Crime", "Drama", "Thriller", "Nollywood"],
    languages: ["English"],
    synopsis: "An ex-car smuggler is given only hours to deliver a government official's daughter to her captor or risk losing his own family.",
    cast: ["Gideon Okeke", "Funlola Aofiyebi-Raimi", "Darasimi Nadi", "Norbert Young", "Ivie Okujaye", "Adunni Ade", "Chidi Mokeme", "Majid Michel"],
    featuredCast: ["Gideon Okeke", "Funlola Aofiyebi-Raimi", "Chidi Mokeme"],
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81729081", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },
  {
    slug: "lisabi-the-uprising",
    title: "Lísàbí: The Uprising",
    year: 2024,
    format: "movie",
    genres: ["Drama", "Period", "Historical", "Nollywood"],
    languages: ["Yoruba", "English"],
    synopsis: "A Yoruba folk hero leads a rebellion against an oppressive empire in a fight for freedom that changes the course of his people.",
    cast: ["Lateef Adedimeji", "Adebimpe Oyebade", "Ibrahim Yekini Itele", "Gabriel Afolayan", "Olumide Oworu", "Kevin Ikeduba"],
    featuredCast: ["Lateef Adedimeji", "Adebimpe Oyebade", "Ibrahim Yekini Itele"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=EyjesbX13vM",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{ platform: "Netflix", label: "Watch on Netflix", href: "https://www.netflix.com/ng/title/81789163", access: "subscription", lastChecked: "2026-09-29", note: "Official Netflix Nigeria title page." }],
  },

  {
    slug: "love-in-every-word",
    title: "Love in Every Word",
    year: 2025,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "Two people from very different worlds meet unexpectedly and must decide whether love can survive ambition, cultural differences and personal fears.",
    cast: ["Uzor Arukwe", "Bambam", "Osereme Inegbenebor", "Daniel Rocky", "Thelma Nwosu", "Amanda Iriekpen", "Susan Jimah"],
    featuredCast: ["Uzor Arukwe", "Bambam", "Osereme Inegbenebor"],
    watchLinks: [{ platform: "YouTube", label: "Watch the full movie on YouTube", href: "https://www.youtube.com/watch?v=bslcx4LRFL0", access: "full-movie", lastChecked: "2026-09-29", note: "Full movie published by Omoni Oboli TV.", publisher: "Omoni Oboli TV", publisherUrl: "https://www.youtube.com/@OmoniOboliTV" }],
  },
  {
    slug: "after-a-night-in-july",
    title: "After a Night in July",
    year: 2025,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A rushed marriage following an unexpected pregnancy is tested by sleepless nights, career pressure, money problems, old wounds and broken trust.",
    cast: ["Uche Montana", "Eso Dike", "Perpetual Ukadike", "Eyiyemi Olivia Rogbinyin"],
    featuredCast: ["Uche Montana", "Eso Dike", "Perpetual Ukadike"],
    watchLinks: [{ platform: "YouTube", label: "Watch the full movie on YouTube", href: "https://www.youtube.com/watch?v=W0p847uOcC0", access: "full-movie", lastChecked: "2026-09-29", note: "Full movie published by Omoni Oboli TV.", publisher: "Omoni Oboli TV", publisherUrl: "https://www.youtube.com/@OmoniOboliTV" }],
  },
  {
    slug: "the-long-way-home",
    title: "The Long Way Home",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A contemporary relationship drama about love, distance and difficult choices, built around an unexpected emotional journey home.",
    cast: ["Uche Montana", "Maurice Sam", "Nadia Buari"],
    featuredCast: ["Uche Montana", "Maurice Sam", "Nadia Buari"],
    watchLinks: [{ platform: "YouTube", label: "Watch the full movie on YouTube", href: "https://www.youtube.com/watch?v=tYp-UskX0cM", access: "full-movie", lastChecked: "2026-09-29", note: "Full movie published by verified Uche Montana TV.", publisher: "Uche Montana TV", publisherUrl: "https://www.youtube.com/@UchemontanaTV" }],
  },
  {
    slug: "monica-2",
    title: "Monica 2",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "The continuation of Monica's story brings new relationship pressure, family complications and emotional choices.",
    cast: ["Uche Montana", "Blessing Onwukwe", "Joseph Momodu"],
    featuredCast: ["Uche Montana", "Blessing Onwukwe", "Joseph Momodu"],
    watchLinks: [{ platform: "YouTube", label: "Watch the full movie on YouTube", href: "https://www.youtube.com/watch?v=7jteLIoNDaQ", access: "full-movie", lastChecked: "2026-09-29", note: "Full movie published by verified Uche Montana TV.", publisher: "Uche Montana TV", publisherUrl: "https://www.youtube.com/@UchemontanaTV" }],
  },
  {
    slug: "the-merger",
    title: "The Merger",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "Two people drawn together by a complicated situation discover that a relationship they never planned may become impossible to ignore.",
    cast: ["Uche Montana", "Timini Egbuson"],
    featuredCast: ["Uche Montana", "Timini Egbuson"],
    watchLinks: [{ platform: "YouTube", label: "Watch the full movie on YouTube", href: "https://www.youtube.com/watch?v=Vzg7hNXk7lo", access: "full-movie", lastChecked: "2026-09-29", note: "Full movie published by verified Uche Montana TV.", publisher: "Uche Montana TV", publisherUrl: "https://www.youtube.com/@UchemontanaTV" }],
  },
  {
    slug: "never-let-go",
    title: "Never Let Go",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "An emotional romance about heartbreak, second chances and the effort required to hold on when a relationship starts falling apart.",
    cast: ["Maurice Sam", "Nadia Buari"],
    featuredCast: ["Maurice Sam", "Nadia Buari"],
    watchLinks: [{ platform: "YouTube", label: "Watch the full movie on YouTube", href: "https://www.youtube.com/watch?v=q5Vg0jUMl-s", access: "full-movie", lastChecked: "2026-09-29", note: "Full movie published by verified Maurice Sam TV.", publisher: "Maurice Sam TV", publisherUrl: "https://www.youtube.com/@mauricesamtv" }],
  },
  {
    slug: "just-before-forever",
    title: "Just Before Forever",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "Love, difficult choices and unexpected turns push three people toward decisions that could change what forever means to them.",
    cast: ["Maurice Sam", "Uche Montana", "Pamela Okoye"],
    featuredCast: ["Maurice Sam", "Uche Montana", "Pamela Okoye"],
    watchLinks: [{ platform: "YouTube", label: "Watch the full movie on YouTube", href: "https://www.youtube.com/watch?v=WIQUH0YSZAs", access: "full-movie", lastChecked: "2026-09-29", note: "Full movie published by verified Maurice Sam TV.", publisher: "Maurice Sam TV", publisherUrl: "https://www.youtube.com/@mauricesamtv" }],
  },
  {
    slug: "a-turn-of-events",
    title: "A Turn of Events",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "A relationship is forced to adapt when unexpected changes, difficult choices and questions of trust alter the course of two lives.",
    cast: ["Maurice Sam", "Sarian Martin"],
    featuredCast: ["Maurice Sam", "Sarian Martin"],
    watchLinks: [{ platform: "YouTube", label: "Watch the full movie on YouTube", href: "https://www.youtube.com/watch?v=negcmBrWxm0", access: "full-movie", lastChecked: "2026-09-29", note: "Full movie published by Maurice Sam TV.", publisher: "Maurice Sam TV", publisherUrl: "https://www.youtube.com/@mauricesamtv" }],
  },
  {
    slug: "a-sunday-affair",
    title: "A Sunday Affair",
    year: 2023,
    format: "movie",
    genres: ["Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "Lifelong best friends Uche and Toyin fall for the same complicated man, putting their friendship under pressure as a painful revelation changes what each of them wants.",
    cast: ["Dakore Egbuson-Akande", "Nse Ikpe-Etim", "Oris Erhuero", "Alexx Ekubo", "Uzor Osimkpa", "Hilda Dokubo"],
    featuredCast: ["Dakore Egbuson-Akande", "Nse Ikpe-Etim", "Oris Erhuero"],
    trailer: {
      label: "Watch the official Netflix trailer",
      href: "https://www.youtube.com/watch?v=U7cnzv1zdPg",
      platform: "YouTube",
      lastChecked: "2026-09-29",
      publisher: "AfricaOnNetflix",
      publisherUrl: "https://www.youtube.com/@AfricaOnNetflix",
    },
    watchLinks: [{
      platform: "Netflix",
      label: "Watch on Netflix",
      href: "https://www.netflix.com/ng/title/81462490",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Official Netflix Nigeria title page. Availability and plan requirements can change.",
    }],
  },
  {
    slug: "adire",
    title: "Adire",
    year: 2023,
    format: "movie",
    genres: ["Drama", "Social issues", "Nollywood"],
    languages: ["English"],
    synopsis: "A woman leaves sex work behind, moves to a small town and starts a lingerie business, drawing the hostility of a powerful preacher's wife.",
    cast: ["Kehinde Bankole", "Funlola Aofiyebi-Raimi", "Femi Branch", "Yvonne Jegede", "Yemi Blaq", "Ibrahim Chatta"],
    featuredCast: ["Kehinde Bankole", "Funlola Aofiyebi-Raimi", "Femi Branch"],
    watchLinks: [{
      platform: "Netflix",
      label: "Watch on Netflix",
      href: "https://www.netflix.com/ng/title/81730156",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Official Netflix title page. Availability can vary by account and region.",
    }],
  },
  {
    slug: "breaded-life",
    title: "Breaded Life",
    year: 2021,
    format: "movie",
    genres: ["Drama", "Comedy", "Nollywood"],
    languages: ["English"],
    synopsis: "When everyone in his privileged life suddenly forgets him, a wealthy young man turns to the only person who still recognizes him: a local bread seller.",
    cast: ["Bimbo Ademoye", "Timini Egbuson", "Tina Mba", "Bisola Aiyeola", "Bolanle Ninalowo", "Jide Kosoko"],
    featuredCast: ["Bimbo Ademoye", "Timini Egbuson", "Tina Mba"],
    watchLinks: [{
      platform: "Netflix",
      label: "Watch on Netflix",
      href: "https://www.netflix.com/ng/title/81591160",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Official Netflix title page. Availability can vary by account and region.",
    }],
  },
  {
    slug: "a-tribe-called-judah",
    title: "A Tribe Called Judah",
    year: 2023,
    format: "movie",
    genres: ["Comedy", "Drama", "Crime", "Nollywood"],
    languages: ["English"],
    synopsis: "A mother and her sons face a family medical crisis, pushing the brothers toward a risky plan that becomes far more dangerous when real criminals enter the picture.",
    cast: ["Funke Akindele", "Jidekene Achufusi", "Uzee Usman", "Timini Egbuson", "Tobi Makinde", "Olumide Oworu", "Nse Ikpe-Etim", "Uzor Arukwe"],
    featuredCast: ["Funke Akindele", "Jidekene Achufusi", "Uzee Usman"],
    directors: ["Funke Akindele", "Adeola Owu", "Oladele Rasheed"],
    runtimeMinutes: 134,
    watchLinks: [{
      platform: "Prime Video",
      label: "Open on Prime Video",
      href: "https://www.primevideo.com/detail/0T4CUFXFYX8QO6MWW0OV62S11J",
      access: "subscription-or-rent",
      lastChecked: "2026-09-29",
      note: "Official Prime Video title page. The exact subscription, rental or purchase option can depend on region.",
    }],
  },
  {
    slug: "sin-first-blood",
    title: "Sin: First Blood",
    year: 2025,
    format: "movie",
    genres: ["Thriller", "Action", "Crime", "Nollywood"],
    languages: ["English"],
    synopsis: "A glamorous Lagos nightclub owner is forced to rebuild after her husband's arrest, then faces pressure from a cartel that wants her to take over his criminal operation.",
    cast: ["Jim Iyke", "Toni Tones", "Leiba Love"],
    featuredCast: ["Jim Iyke", "Toni Tones", "Leiba Love"],
    runtimeMinutes: 113,
    watchLinks: [{
      platform: "Prime Video",
      label: "Watch on Prime Video",
      href: "https://www.primevideo.com/detail/0KXCFQNLM0K54DL96DZ76BWDCK",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Official Prime Video title page. Regional availability and plan requirements can change.",
    }],
  },
  {
    slug: "payday",
    title: "PayDay",
    year: 2018,
    format: "movie",
    genres: ["Comedy", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A broke young man racing to find money before payday is pulled into a chaotic chain of neighbourhood trouble, ambition and unexpected opportunity.",
    cast: ["Baaj Adebule", "Victor Ebiye", "Orwi Manny Ameh", "Zack Orji", "Bisola Aiyeola", "Meg Otanwa", "Segilola Ogidan", "Mawuli Gavor"],
    featuredCast: ["Baaj Adebule", "Bisola Aiyeola", "Mawuli Gavor"],
    directors: ["Cheta Chukwu"],
    runtimeMinutes: 110,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/payday",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "big-love",
    title: "Big Love",
    year: 2023,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "Two people drawn strongly to each other navigate family reservations, friends' opinions and their own histories as commitment becomes harder to avoid.",
    cast: ["Timini Egbuson", "Bimbo Ademoye", "Shaffy Bello", "Jaiye Kuti", "Seyi Awolowo", "Kalu Ikeagwu", "Teniola Aladese", "Deza the Great"],
    featuredCast: ["Timini Egbuson", "Bimbo Ademoye", "Shaffy Bello"],
    directors: ["Biodun Stephen"],
    runtimeMinutes: 102,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/big-love",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "benevolence",
    title: "Benevolence",
    year: 2016,
    format: "movie",
    genres: ["Drama", "Romance", "Faith-based", "Nollywood"],
    languages: ["English"],
    synopsis: "Two women face unemployment, difficult relationships and tests of faith while trying to build more stable lives.",
    cast: ["Kalu Ikeagwu", "Ijeoma Peters", "Tahiru Magari Bairu", "Tessy Brown", "Lola Elegbede", "Seyi Fasuyi", "Onyeka Fiaka", "Tim Godfrey"],
    featuredCast: ["Kalu Ikeagwu", "Ijeoma Peters", "Tim Godfrey"],
    directors: ["Doris Chinasa Ariole"],
    runtimeMinutes: 113,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/benevolence",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "levi",
    title: "Levi",
    year: 2019,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A man returning to a relationship shaped by the past discovers that time and distance have made the possibility of a second chance more complicated.",
    cast: ["Ramsey Nouah", "Joseph Benjamin", "Nancy Isime", "Deyemi Okanlawon", "Lydia Forson", "Bimbo Manuel", "Lisa Omorodion", "Nneoma Okoro", "Bolaji Ogunmola"],
    featuredCast: ["Ramsey Nouah", "Nancy Isime", "Deyemi Okanlawon"],
    directors: ["Okechukwu Oku"],
    runtimeMinutes: 93,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/levi",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "okanjuwa",
    title: "Okanjuwa",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Comedy", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "Three Lagos couples balance relationships, ambitions and everyday pressures as greed and desire begin to test their values and loyalty.",
    cast: ["Kunle Remi", "Tomike Adeoye", "Uzor Arukwe", "Omowunmi Dada", "Kamo State", "Ruby Okezie", "Femi Adebayo", "Blessing Obasi"],
    featuredCast: ["Kunle Remi", "Uzor Arukwe", "Omowunmi Dada"],
    directors: ["Zulu Oyibo"],
    runtimeMinutes: 105,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/okanjuwa-1",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "the-stand-up",
    title: "The Stand Up",
    year: 2022,
    format: "movie",
    genres: ["Comedy", "Drama", "Inspirational", "Nollywood"],
    languages: ["English"],
    synopsis: "A naturally funny man gets a chance at Lagos stand-up comedy while simultaneously trying to raise money to resolve a serious family debt.",
    cast: ["Richard Mofe-Damijo", "Ayo Makun", "Paul Olope", "Anita Asuoha", "Mofe Duncan", "Eso Dike", "Adaobi Dibor", "Jide Kosoko", "Daniel Abua"],
    featuredCast: ["Richard Mofe-Damijo", "Ayo Makun", "Mofe Duncan"],
    directors: ["Jide Oyegbile"],
    runtimeMinutes: 112,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/the-stand-up",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },

  {
    slug: "ajosepo",
    title: "Ajosepo",
    year: 2023,
    format: "movie",
    genres: ["Romance", "Drama", "Comedy", "Nollywood"],
    languages: ["English"],
    synopsis: "On the eve of a wedding, a family secret threatens to derail the celebration as relatives scramble to contain the fallout.",
    cast: ["Yemi Solade", "Timini Egbuson", "Mike Afolarin", "Tomike Adeoye", "Mercy Aigbe", "Bisola Aiyeola", "Muyiwa Ademola", "Ibrahim Yekini", "Ronke Oshodi Oke"],
    featuredCast: ["Timini Egbuson", "Mike Afolarin", "Mercy Aigbe"],
    directors: ["Kayode Kasum"],
    runtimeMinutes: 129,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/ajosepo",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "ajosepo-the-gathering",
    title: "Ajosepo: The Gathering",
    year: 2026,
    format: "movie",
    genres: ["Comedy", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A new wedding reunites an extended family, bringing old grudges, fresh scandals and another chaotic search for forgiveness.",
    cast: ["Timini Egbuson", "Bolaji Ogunmola", "Toyin Abraham", "Mercy Aigbe", "Mike Afolarin", "Tomike Adeoye", "Ronke Oshodi-Oke", "Yemi Solade", "Odunlade Adekola"],
    featuredCast: ["Timini Egbuson", "Bolaji Ogunmola", "Toyin Abraham"],
    directors: ["Kayode Kasum"],
    runtimeMinutes: 112,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/ajosepo-2-the-gathering",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "a-mama-deola-wedding-story",
    title: "A Mama Deola Wedding Story",
    year: 2026,
    format: "movie",
    genres: ["Comedy", "Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "A determined mother takes on debt to fund a lavish wedding, only for family tensions, class conflict and an old act of kindness to reshape the celebration.",
    cast: ["Folagbade Banks", "Omowunmi Dada", "Rotimi Salami", "Shaffy Bello", "Bukky Wright", "Iya Rainbow", "Erica Nlewedim", "Toyin Adegbola", "Femi Adebayo", "Blessing Obasi"],
    featuredCast: ["Omowunmi Dada", "Shaffy Bello", "Femi Adebayo"],
    directors: ["Femi Adebayo"],
    runtimeMinutes: 120,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/a-mama-deola-wedding-story",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "tenis-big-day",
    title: "Teni's Big Day",
    year: 2023,
    format: "movie",
    genres: ["Comedy", "Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A newly engaged magazine editor plans her dream wedding while family interference, an unwelcome ex and hidden debt threaten to unravel it.",
    cast: ["Nancy Isime", "Enyinna Nwigwe", "Erica Nlewedim", "Uche Montana", "Kachi Nnochiri", "IK Ogbonna", "Nosa Rex", "Keppy Ekpenyong-Bassey"],
    featuredCast: ["Nancy Isime", "Erica Nlewedim", "Uche Montana"],
    directors: ["Desmond Elliot"],
    runtimeMinutes: 85,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/teni-s-big-day",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "devil-in-agbada",
    title: "Devil in Agbada",
    year: 2021,
    format: "movie",
    genres: ["Thriller", "Political drama", "Nollywood"],
    languages: ["English"],
    synopsis: "Three women form an alliance and train themselves to bring down a ruthless politician after the justice system fails them.",
    cast: ["Linda Osifo", "Efe Irele", "Erica Nlewedim", "Uzor Arukwe", "Akin Lewis", "Uche Jombo", "Alexx Ekubo", "Nosa Rex", "Etinosa Idemudia", "Desmond Elliot"],
    featuredCast: ["Linda Osifo", "Efe Irele", "Erica Nlewedim"],
    directors: ["Umanu Elijah"],
    runtimeMinutes: 118,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/devil-in-agbada",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "three-wise-men",
    title: "Three Wise Men",
    year: 2016,
    format: "movie",
    genres: ["Comedy", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "Three lifelong friends enter retirement with fresh pensions and big plans, only for romance, family conflict and fraud to turn their celebration upside down.",
    cast: ["Richard Mofe-Damijo", "Victor Olaotan", "Zack Orji", "Sola Sobowale", "Ebele Okaro", "Kanayo O. Kanayo", "Chiwetalu Agu", "Tony Umez", "Alexx Ekubo", "Ireti Doyle"],
    featuredCast: ["Richard Mofe-Damijo", "Zack Orji", "Sola Sobowale"],
    directors: ["Pat Ogbere Imobhio"],
    runtimeMinutes: 95,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/three-wise-men",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "palava",
    title: "Palava!",
    year: 2022,
    format: "movie",
    genres: ["Comedy", "Family", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A highlife legend's milestone birthday reunion brings together a fractured family just as secrets, divorce, paternity questions and a kidnapping plot collide.",
    cast: ["Richard Mofe-Damijo", "Bisola Aiyeola", "Linda Ejiofor", "Jemima Osunde", "Gideon Okeke", "Iyabo Ojo", "Beverly Naya", "Mercy Aigbe", "Beverly Osu", "Neo Akpofure", "Eniola Badmus", "Chinedu Ikedieze"],
    featuredCast: ["Richard Mofe-Damijo", "Bisola Aiyeola", "Jemima Osunde"],
    directors: ["Niyi Akinmolayan"],
    runtimeMinutes: 107,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/palava",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "strangers",
    title: "Strangers",
    year: 2022,
    format: "movie",
    genres: ["Coming of age", "Drama", "Nollywood"],
    languages: ["English", "Yoruba"],
    synopsis: "A boy in a remote Yoruba village survives a life-threatening illness through the help of strangers, setting him on a long path toward becoming a doctor.",
    cast: ["Lateef Adedimeji", "Bimbo Oshin", "Bolaji Ogunmola", "Debbie Felix", "Femi Adebayo", "Bimbo Akintola", "Jide Kosoko", "Chris Iheuwa", "Nonso Odogwu"],
    featuredCast: ["Lateef Adedimeji", "Bolaji Ogunmola", "Femi Adebayo"],
    directors: ["Biodun Stephen"],
    runtimeMinutes: 118,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/strangers",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "ori-rebirth",
    title: "ORI: Rebirth",
    year: 2025,
    format: "movie",
    genres: ["Family", "Drama", "Supernatural", "Nollywood"],
    languages: ["Yoruba", "English"],
    synopsis: "After surviving a crash and losing her memory, a woman pieces together a hidden royal identity while family conflict and ancestral expectations close in.",
    cast: ["Adebayo Salami", "Jide Kosoko", "Muyiwa Ademola", "Saidi Balogun", "Fathia Balogun Williams"],
    featuredCast: ["Adebayo Salami", "Jide Kosoko", "Muyiwa Ademola"],
    directors: ["Muyiwa Ademola", "Adebayo Tijani", "Tope Adebayo Salami"],
    runtimeMinutes: 120,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/ori-the-rebirth",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },

  {
    slug: "love-in-a-pandemic",
    title: "Love in a Pandemic",
    year: 2023,
    format: "movie",
    genres: ["Romance", "Comedy", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "During the Lagos lockdown, a wrong-number call becomes an unexpected connection that complicates an already uncertain relationship.",
    cast: ["Nancy Isime", "Deyemi Okanlawon", "Teniola Aladese", "Ronke Odusanya", "Uche Montana", "Eso Dike"],
    featuredCast: ["Nancy Isime", "Deyemi Okanlawon", "Uche Montana"],
    directors: ["Akay Mason"],
    runtimeMinutes: 89,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/love-in-pandemic",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "ghost-and-the-tout",
    title: "Ghost and the Tout",
    year: 2018,
    format: "movie",
    genres: ["Comedy", "Supernatural", "Mystery", "Nollywood"],
    languages: ["English"],
    synopsis: "A fearless street hustler begins seeing ghosts and is drawn into solving the murder of a wealthy man who refuses to leave her alone.",
    cast: ["Toyin Abraham", "Sambasa Nzeribe", "Rachael Okonkwo", "Omowunmi Dada", "Chioma Chukwuka Akpotha"],
    featuredCast: ["Toyin Abraham", "Sambasa Nzeribe", "Omowunmi Dada"],
    directors: ["Charles Uwagbai"],
    runtimeMinutes: 102,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/ghost-and-the-tout",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "ghost-and-the-tout-too",
    title: "Ghost and the Tout Too",
    year: 2021,
    format: "movie",
    genres: ["Comedy", "Supernatural", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "Isla's reputation as a ghost whisperer grows when a woman in a coma urgently needs help exposing the truth before time runs out.",
    cast: ["Toyin Abraham", "Mercy Johnson", "Osas Ighodaro", "Patience Ozokwo", "Iyabo Ojo", "Odunlade Adekola", "Ini Edo", "Ali Nuhu", "Deyemi Okanlawon"],
    featuredCast: ["Toyin Abraham", "Mercy Johnson", "Osas Ighodaro"],
    directors: ["Michael Akinrogunde"],
    runtimeMinutes: 112,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/ghost-and-the-tout-too",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "love-and-new-notes",
    title: "Love and New Notes",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Thriller", "Nollywood"],
    languages: ["English"],
    synopsis: "A young man desperate to provide for his pregnant fiancée makes one risky financial decision that threatens the future they are building together.",
    cast: ["Timini Egbuson", "Sophie Alakija", "Odunlade Adekola", "Eniola Badmus", "Ayoola Akinyoola", "Tolu Babs Omish", "Toluwani George"],
    featuredCast: ["Timini Egbuson", "Sophie Alakija", "Odunlade Adekola"],
    directors: ["Kayode Kasum"],
    runtimeMinutes: 116,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/love-and-new-notes",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "the-cartel",
    title: "The Cartel",
    year: 2025,
    format: "movie",
    genres: ["Crime", "Thriller", "Action", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A woman goes undercover inside a violent criminal network after her brother is framed for murder and the justice system fails him.",
    cast: ["Ramsey Nouah", "Broda Shaggi", "Chika Ike", "Nkechi Blessing", "Bolanle Ninalowo", "Eniola Badmus", "Antar Laniyan", "Jide Kosoko", "Tina Mba", "Uzor Arukwe"],
    featuredCast: ["Ramsey Nouah", "Chika Ike", "Uzor Arukwe"],
    directors: ["Elvis Chucks"],
    runtimeMinutes: 114,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/cartel",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "iyalode",
    title: "Iyalode",
    year: 2025,
    format: "movie",
    genres: ["Yoruba epic", "Drama", "Action", "Nollywood"],
    languages: ["Yoruba"],
    synopsis: "A fearless woman fights through palace intrigue, betrayal and rigid expectations to claim the highest female title in a powerful Yoruba kingdom.",
    cast: ["Toyin Abraham", "Bukky Wright", "Kehinde Bankole", "Gabriel Afolayan", "Ibrahim Chatta", "Muyiwa Ademola", "Wale Ojo"],
    featuredCast: ["Toyin Abraham", "Kehinde Bankole", "Muyiwa Ademola"],
    directors: ["Adebayo Tijani"],
    runtimeMinutes: 132,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/iyalode",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "ijakumo",
    title: "Ijakumo",
    year: 2022,
    format: "movie",
    genres: ["Thriller", "Supernatural", "Satire", "Nollywood"],
    languages: ["English", "Yoruba"],
    synopsis: "A woman returns to expose the fraudulent megachurch empire built by the man who betrayed her family decades earlier.",
    cast: ["Toyin Abraham", "Kunle Remi", "Lolade Okusanya", "Bimbo Akintola", "Olumide Oworu", "Lilian Afegbai", "Eso Dike", "Antar Laniyan", "Segun Arinze", "Kolawole Ajeyemi"],
    featuredCast: ["Toyin Abraham", "Kunle Remi", "Bimbo Akintola"],
    directors: ["Adebayo Tijani", "Steve Sodiya"],
    runtimeMinutes: 118,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/ijakumo",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "kesari-the-king",
    title: "Kesari: The King",
    year: 2023,
    format: "movie",
    genres: ["Yoruba epic", "Crime", "Drama", "Action", "Nollywood"],
    languages: ["Yoruba"],
    synopsis: "A seemingly untouchable criminal kingpin faces a determined police task force and a young recruit whose arrival begins to expose the limits of his power.",
    cast: ["Femi Adebayo", "Debo Adedayo", "Odunlade Adekola", "Boma Akpore", "Femi Branch", "Kevin Ikeduba", "Yvonne Jegede", "Bolaji Ogunmola", "Deyemi Okanlawon", "Adebayo Salami", "Ibrahim Yekini"],
    featuredCast: ["Femi Adebayo", "Odunlade Adekola", "Deyemi Okanlawon"],
    directors: ["Itele D Icon", "Tope Adebayo Salami"],
    runtimeMinutes: 100,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/kesari",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },
  {
    slug: "confusion-na-wa",
    title: "Confusion Na Wa",
    year: 2013,
    format: "movie",
    genres: ["Dark comedy", "Crime", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A stolen phone exposes a web of affairs, corruption, blackmail and desperation as several lives collide over one chaotic night.",
    cast: ["Ramsey Nouah", "OC Ukeje", "Ali Nuhu", "Tunde Aladese", "Gold Ikponmwosa", "Nathaniel Deme", "Yanchat Sankey", "Lisa Pam Tok", "Toyin Alabi", "Yewande Iruemiobe"],
    featuredCast: ["Ramsey Nouah", "OC Ukeje", "Ali Nuhu"],
    directors: ["Kenneth Gyang"],
    runtimeMinutes: 106,
    watchLinks: [{
      platform: "Kava",
      label: "Watch on Kava",
      href: "https://watch.kava.tv/confusion-na-wa",
      access: "subscription",
      lastChecked: "2026-09-29",
      note: "Licensed Kava title page. Kava supports offline downloads for eligible content inside its service.",
      publisher: "Kava",
      publisherUrl: "https://kava.tv/",
    }],
  },

  {
    slug: "millionaire-until-morning",
    title: "Millionaire Until Morning",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "Facing a marriage she does not want, Ndidi is unexpectedly offered another path by Harrison, a wealthy man whose intervention forces both of them to confront what being chosen and loved really means.",
    cast: ["Chris Attoh", "Sophia Chisom", "Chimsom Chuka", "Thelma Chukwunwem"],
    featuredCast: ["Chris Attoh", "Sophia Chisom", "Chimsom Chuka"],
    runtimeMinutes: 144,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=pG_962LtEf8",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Omoni Oboli TV.",
      publisher: "Omoni Oboli TV",
      publisherUrl: "https://www.youtube.com/@OmoniOboliTV",
    }],
  },
  {
    slug: "bowale",
    title: "Bowale",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "After three decades in prison for a crime he did not commit, a man gets an unexpected chance to rebuild his life when a successful businesswoman hires him as her driver.",
    cast: ["BamBam Olawumi", "Bobby Ekpe", "Jude Chukwuka"],
    featuredCast: ["BamBam Olawumi", "Bobby Ekpe", "Jude Chukwuka"],
    directors: ["Biodun Stephen"],
    runtimeMinutes: 121,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=GrxitJ4fHT8",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by BIODUNSTEPHEN TV.",
      publisher: "BIODUNSTEPHEN TV",
      publisherUrl: "https://www.youtube.com/@biodunstephentv",
    }],
  },
  {
    slug: "love-and-legacy-2026",
    title: "Love and Legacy",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "After a disastrous first impression, Ene must prove to Chinwe that she is the right woman for Chinwe's brother Obinna, turning family expectations into a test of love and character.",
    cast: ["Uche Jombo", "Omeche Oko", "Victory Michael"],
    featuredCast: ["Uche Jombo", "Omeche Oko", "Victory Michael"],
    runtimeMinutes: 138,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=JPYw9dHdlWU",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Uche Jombo TV.",
      publisher: "Uche Jombo TV",
    }],
  },
  {
    slug: "where-love-lives",
    title: "Where Love Lives",
    year: 2025,
    format: "movie",
    genres: ["Romance", "Comedy", "Nollywood"],
    languages: ["English"],
    synopsis: "A relationship-driven romantic comedy about love, commitment and the choices that determine whether two people can build a lasting life together.",
    cast: ["Uzor Arukwe", "Bimbo Ademoye", "Chioma Nwosu", "Osas Ighodaro"],
    featuredCast: ["Uzor Arukwe", "Bimbo Ademoye", "Osas Ighodaro"],
    runtimeMinutes: 146,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=we7pr8gDCn8",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Bimbo Ademoye TV.",
      publisher: "Bimbo Ademoye TV",
      publisherUrl: "https://www.youtube.com/@bimboademoyetv",
    }],
  },
  {
    slug: "sibe",
    title: "Sibe",
    year: 2026,
    format: "movie",
    genres: ["Comedy", "Nollywood"],
    languages: ["English"],
    synopsis: "An ensemble Nigerian comedy led by Bimbo Ademoye, Uche Montana, Uzor Arukwe and Deyemi Okanlawon, built around clashing personalities, relationships and escalating comic complications.",
    cast: ["Bimbo Ademoye", "Uche Montana", "Uzor Arukwe", "Deyemi Okanlawon"],
    featuredCast: ["Bimbo Ademoye", "Uche Montana", "Uzor Arukwe"],
    runtimeMinutes: 145,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=HAk97psM9h0",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Bimbo Ademoye TV.",
      publisher: "Bimbo Ademoye TV",
      publisherUrl: "https://www.youtube.com/@bimboademoyetv",
    }],
  },
  {
    slug: "monica",
    title: "Monica",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A contemporary Nigerian love story led by Uche Montana and John Ekanem, centered on an emotionally complicated relationship and the choices that shape it.",
    cast: ["Uche Montana", "John Ekanem"],
    featuredCast: ["Uche Montana", "John Ekanem"],
    runtimeMinutes: 123,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=-yVrN03f610",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Uche Montana TV.",
      publisher: "Uche Montana TV",
      publisherUrl: "https://www.youtube.com/@UchemontanaTV",
    }],
  },
  {
    slug: "fruit-covenant",
    title: "Fruit Covenant",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Faith", "Nollywood"],
    languages: ["English"],
    synopsis: "A spiritual drama about faith, promises and consequences as Adun makes a sacred covenant and must face the earthly and spiritual effects of that choice.",
    cast: ["Toyin Abraham Ajeyemi", "Olarotimi Fakunle", "Jumoke George", "Hejiwumi Akewi", "Miracle Ojorale"],
    featuredCast: ["Toyin Abraham Ajeyemi", "Olarotimi Fakunle", "Jumoke George"],
    directors: ["Sola Oyedele", "Toyin Abraham Ajeyemi"],
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=OLmUOAjZqOg",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Toyin Abraham TV.",
      publisher: "Toyin Abraham TV",
      publisherUrl: "https://www.youtube.com/@ToyinAbrahamTv1",
    }],
  },
  {
    slug: "man-of-the-year-2026",
    title: "Man of the Year",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Romance", "Sports", "Nollywood"],
    languages: ["English"],
    synopsis: "A fighter discovers that the harder battle is outside the ring when love, pride and destiny force him to prove his worth beyond strength and public recognition.",
    cast: ["Maurice Sam", "Sarian Martin"],
    featuredCast: ["Maurice Sam", "Sarian Martin"],
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=0OCFvXZyy8U",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by verified Maurice Sam TV.",
      publisher: "Maurice Sam TV",
      publisherUrl: "https://www.youtube.com/@mauricesamtv",
    }],
  },
  {
    slug: "a-place-with-you",
    title: "A Place With You",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "An emotional romantic drama about fate, healing and choosing love despite fear, led by Uche Montana and Chidi Dike.",
    cast: ["Uche Montana", "Chidi Dike"],
    featuredCast: ["Uche Montana", "Chidi Dike"],
    runtimeMinutes: 115,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=Ia47wPj0Z7o",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Uche Montana TV.",
      publisher: "Uche Montana TV",
      publisherUrl: "https://www.youtube.com/@UchemontanaTV",
    }],
  },
  {
    slug: "sister-agatha",
    title: "Sister Agatha",
    year: 2026,
    format: "movie",
    genres: ["Comedy", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "When a small church receives one sponsored ticket to a London crusade, a strict head usher and a Gen Z newcomer turn Sunday services into a comic struggle over who deserves the opportunity.",
    cast: ["Blessing Obasi", "Kiekie", "Michael Ejoor", "Kenzy Udosen"],
    featuredCast: ["Blessing Obasi", "Kiekie", "Michael Ejoor"],
    runtimeMinutes: 108,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=xK9YDX2G2NQ",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Blessing Obasi TV.",
      publisher: "Blessing Obasi TV",
    }],
  },
  {
    slug: "forever-found",
    title: "Forever Found",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A romantic drama about love, sacrifice, patience and self-worth as its characters try to hold on to what they want without losing themselves.",
    cast: ["Chinenye Nnebe", "John Ekanem", "Chioma Nwosu", "Amaka Ndukwe"],
    featuredCast: ["Chinenye Nnebe", "John Ekanem", "Chioma Nwosu"],
    runtimeMinutes: 108,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=JhgejieJRng",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by ENYINNA JONAS TV.",
      publisher: "ENYINNA JONAS TV",
    }],
  },
  {
    slug: "all-things-equal",
    title: "All Things Equal",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "Two independent people confront love, ambition, sacrifice and the strain of trying to build a partnership without surrendering their individual goals.",
    cast: ["Sarian Martin", "Daniel Etim Effiong"],
    featuredCast: ["Sarian Martin", "Daniel Etim Effiong"],
    runtimeMinutes: 95,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=hyTwvk_Q7Pc",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Sarian Martin TV.",
      publisher: "Sarian Martin TV",
    }],
  },
  {
    slug: "my-housemate",
    title: "My Housemate",
    year: 2026,
    format: "movie",
    genres: ["Romance", "Drama", "Nollywood"],
    languages: ["English"],
    synopsis: "A struggling musician and an unemployed professional are forced to share an apartment, turning constant clashes into friendship and attraction just as their former romantic lives return.",
    cast: ["Bolaji Ogunmola", "Nosa Rex"],
    featuredCast: ["Bolaji Ogunmola", "Nosa Rex"],
    runtimeMinutes: 81,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=i9xzI3A_jjE",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Bolaji Ogunmola TV.",
      publisher: "Bolaji Ogunmola TV",
      publisherUrl: "https://www.youtube.com/@bolajiogunmolatv",
    }],
  },
  {
    slug: "the-man-i-never-knew",
    title: "The Man I Never Knew",
    year: 2026,
    format: "movie",
    genres: ["Drama", "Romance", "Nollywood"],
    languages: ["English"],
    synopsis: "After a resort romance ends in abandonment and pregnancy, Mila rebuilds her life alone until the man from her past reappears years later and insists he does not know her.",
    cast: ["TooSweet Annan", "Chisom Agoawuike", "Mojoyin Fadaka"],
    featuredCast: ["TooSweet Annan", "Chisom Agoawuike", "Mojoyin Fadaka"],
    runtimeMinutes: 94,
    watchLinks: [{
      platform: "YouTube",
      label: "Watch the full movie on YouTube",
      href: "https://www.youtube.com/watch?v=qqrsv9jJJLo",
      access: "full-movie",
      lastChecked: "2026-09-30",
      note: "Full movie published by Royal Arts TV.",
      publisher: "Royal Arts TV",
      publisherUrl: "https://www.youtube.com/@RoyalArtsTV",
    }],
  },


  {
    slug: "behind-the-scenes",
    title: "Behind the Scenes",
    year: 2025,
    format: "movie",
    genres: ["Drama", "Family", "Nollywood"],
    languages: ["English", "Yoruba"],
    synopsis: "Real-estate mogul Ronke is known for giving freely to family and friends, but a crisis forces her to confront how much her generosity has cost her and who truly values her.",
    cast: ["Funke Akindele", "Scarlet Gomez", "Tobi Bakre", "Ibrahim Chatta", "Destiny Etiko", "Uche Montana"],
    featuredCast: ["Funke Akindele", "Scarlet Gomez", "Tobi Bakre"],
    directors: ["Tunde Olaoye", "Funke Akindele"],
    featured: true,
    trailer: {
      label: "Watch the official FilmOne trailer",
      href: "https://www.youtube.com/watch?v=WBn3OxmriX0",
      platform: "YouTube",
      lastChecked: "2026-10-02",
      publisher: "FilmOne NG",
      publisherUrl: "https://www.youtube.com/@FilmOneNG",
    },
    watchLinks: [{
      platform: "Netflix",
      label: "Open on Netflix",
      href: "https://www.netflix.com/ng/title/82741541",
      access: "subscription",
      lastChecked: "2026-10-02",
      note: "Official Netflix title page. Regional availability and plan requirements can change.",
    }],
  },
  {
    slug: "gingerrr",
    title: "Gingerrr",
    year: 2025,
    format: "movie",
    genres: ["Crime", "Drama", "Comedy", "Thriller", "Nollywood"],
    languages: ["English"],
    synopsis: "Four old friends form an uneasy alliance for a daring heist, but buried secrets and betrayals put both the plan and their chance at a new life at risk.",
    cast: ["Bukunmi Adeaga-Ilori", "Bisola Aiyeola", "Wumi Toriola", "Bolaji Ogunmola", "Odunlade Adekola", "Timini Egbuson"],
    featuredCast: ["Bukunmi Adeaga-Ilori", "Bisola Aiyeola", "Wumi Toriola"],
    directors: ["Yemi Morafa"],
    featured: true,
    watchLinks: [{
      platform: "Netflix",
      label: "Open on Netflix",
      href: "https://www.netflix.com/ng/title/82724198",
      access: "subscription",
      lastChecked: "2026-10-02",
      note: "Official Netflix title page. Regional availability and plan requirements can change.",
    }],
  },
  {
    slug: "oversabi-aunty",
    title: "Oversabi Aunty",
    year: 2025,
    format: "movie",
    genres: ["Comedy", "Drama", "Family", "Nollywood"],
    languages: ["English"],
    synopsis: "A self-righteous church usher is determined to solve everyone else's problems, but her interventions begin to destabilise her own family as her daughter's wedding approaches.",
    cast: ["Toyin Abraham", "Mike Ezuruonye", "Enioluwa Adeoluwa", "Jemima Osunde", "Tana Adelana", "Ngozi Ezeonu", "Efe Irele", "Toyin Afolayan", "Bianca Ugowanne"],
    featuredCast: ["Toyin Abraham", "Mike Ezuruonye", "Enioluwa Adeoluwa"],
    directors: ["Toyin Abraham"],
    runtimeMinutes: 127,
    featured: true,
    watchLinks: [{
      platform: "Netflix",
      label: "Open on Netflix",
      href: "https://www.netflix.com/ng/title/82741545",
      access: "subscription",
      lastChecked: "2026-10-04",
      note: "Official Netflix title page. Regional availability and plan requirements can change.",
    }],
  },
  {
    slug: "my-fathers-shadow",
    title: "My Father's Shadow",
    year: 2025,
    format: "movie",
    genres: ["Drama", "Family", "Independent"],
    languages: ["English", "Nigerian Pidgin", "Yoruba"],
    synopsis: "In Lagos in 1993, two young brothers spend a tense day with their estranged father, discovering more about him and the city while political unrest threatens their journey home.",
    cast: ["Ṣọpẹ Dìrísù", "Godwin Egbo", "Chibuike Marvellous Egbo"],
    featuredCast: ["Ṣọpẹ Dìrísù", "Godwin Egbo", "Chibuike Marvellous Egbo"],
    directors: ["Akinola Davies Jr."],
    runtimeMinutes: 94,
    featured: true,
    watchLinks: [{
      platform: "Netflix",
      label: "Open on Netflix",
      href: "https://www.netflix.com/ng/title/83115708",
      access: "subscription",
      lastChecked: "2026-10-02",
      note: "Official Netflix title page. Availability can vary by territory even when the title appears in regional charts.",
    }],
  },

];

export const entertainmentPlatforms = ["Netflix", "YouTube", "Prime Video", "Kava"] as const;

export function getEntertainmentTitle(slug: string) {
  return entertainmentTitles.find((item) => item.slug === slug);
}

export function getEntertainmentGenres() {
  return [...new Set(entertainmentTitles.flatMap((item) => item.genres))].sort();
}

export function getPlatformCount(platform: EntertainmentPlatform) {
  return entertainmentTitles.filter((item) => item.watchLinks.some((link) => link.platform === platform)).length;
}


export function canDisplayEntertainmentArtwork(title: EntertainmentTitle) {
  const artwork = title.artwork;
  return Boolean(
    artwork &&
    artwork.status === "approved" &&
    artwork.url &&
    artwork.sourceUrl &&
    artwork.credit &&
    artwork.licenseNote &&
    artwork.lastChecked &&
    ["press-kit-permission", "direct-permission", "licensed", "creative-commons"].includes(artwork.usageBasis),
  );
}

export function getFeaturedCast(title: EntertainmentTitle) {
  return (title.featuredCast?.length ? title.featuredCast : title.cast).slice(0, 3);
}
