import type { ExplorePlace } from "@/lib/explore-places";

// Official NCMM museum directory. These are real locations, not claims of live exhibitions.
// Do not create separate thin SEO pages for these; attach to the canonical city/state guide.
export const ncmmMuseumPlaces: ExplorePlace[] = [
  {
    slug: "national-museum-esie",
    guideSlug: "kwara-highlights",
    name: "National Museum Esie",
    kind: "attraction",
    area: "Esie, Irepodun",
    address: "Esie Museum Road, Esie, Kwara State, Nigeria",
    summary: "Nigeria's first museum, opened in 1945, known for its soapstone figures. An important heritage stop outside Ilorin.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Esie Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["museum","Esie","heritage"]
  },
  {
    slug: "national-museum-unity-enugu",
    guideSlug: "enugu",
    name: "National Museum of Unity, Enugu",
    kind: "attraction",
    area: "GRA, Enugu",
    address: "65 Abakaliki Road, GRA, Enugu, Enugu State, Nigeria",
    summary: "Federal museum for understanding cultural heritage in Enugu. Pair it with a short city-history visit rather than treating every Enugu attraction as a day trip.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum of Unity, Enugu Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["museum","Enugu","culture"]
  },
  {
    slug: "national-museum-oron",
    guideSlug: "akwa-ibom-heritage-route",
    name: "National Museum Oron",
    kind: "attraction",
    area: "Oron",
    address: "National Museum Oron, Oron, Akwa Ibom State, Nigeria",
    summary: "An NCMM museum stop in Oron for visitors exploring coastal Akwa Ibom history and culture. Confirm the current galleries and access before setting off from Uyo.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Oron Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["museum","Oron","Akwa Ibom"]
  },
  {
    slug: "national-museum-ilorin",
    guideSlug: "ilorin",
    name: "National Museum Ilorin",
    kind: "attraction",
    area: "Ilorin GRA",
    address: "14 Abdulkadri Road, GRA, Ilorin, Kwara State, Nigeria",
    summary: "Federal museum in Ilorin, suitable for a heritage-focused city itinerary alongside local architecture and markets.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Ilorin Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["museum","Ilorin","Kwara"]
  },
  {
    slug: "national-museum-katsina",
    guideSlug: "katsina-state-travel-guide",
    name: "National Museum Katsina",
    kind: "attraction",
    area: "Kofa Uku, Katsina",
    address: "Kofa Uku, Mohammadu Dikko Road, Katsina, Katsina State, Nigeria",
    summary: "Federal museum for a Katsina history itinerary. Check visitor arrangements and the latest travel advice before any trip.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Katsina Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["museum","Katsina","history"]
  },
  {
    slug: "national-museum-igbo-ukwu",
    guideSlug: "anambra-heritage-circuit",
    name: "National Museum Igbo-Ukwu",
    kind: "attraction",
    area: "Aguata LGA",
    address: "Km 4 Umudege–Ezinifite Road, Igbo-Ukwu, Aguata LGA, Anambra State, Nigeria",
    summary: "An NCMM museum in the Igbo-Ukwu archaeological landscape, complementing the archaeological sites rather than duplicating them.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Igbo-Ukwu Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["museum","Igbo-Ukwu","Anambra"]
  },
  {
    slug: "national-museum-abeokuta",
    guideSlug: "abeokuta",
    name: "National Museum Abeokuta",
    kind: "attraction",
    area: "Idi-Aba, Abeokuta",
    address: "Baptist Girls College, Idi-Aba, Abeokuta, Ogun State, Nigeria",
    summary: "Federal museum in Abeokuta for visitors interested in Ogun history beyond the main Olumo Rock route.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Abeokuta Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["museum","Abeokuta","Ogun"]
  },
  {
    slug: "national-museum-jalingo",
    guideSlug: "taraba-highlands",
    name: "National Museum Jalingo",
    kind: "attraction",
    area: "Jalingo",
    address: "Beside Taraba State Ministry of Culture and Tourism, opposite Governor's Office, Jalingo, Taraba State, Nigeria",
    summary: "Federal museum in the Taraba capital. A sensible city heritage stop before planning longer trips towards highland areas.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Jalingo Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["museum","Jalingo","Taraba"]
  },
  {
    slug: "national-museum-abakaliki",
    guideSlug: "ebonyi-state-travel-guide",
    name: "National Museum Abakaliki",
    kind: "attraction",
    area: "Kiriri, Abakaliki",
    address: "6 St Patrick Road, Kiriri, Abakaliki, Ebonyi State, Nigeria",
    summary: "Officially listed NCMM museum in Abakaliki for local-history and material-culture discovery.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Abakaliki Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["Abakaliki","Ebonyi"]
  },
  {
    slug: "national-museum-damaturu",
    guideSlug: "yobe-state-travel-guide",
    name: "National Museum Damaturu",
    kind: "attraction",
    area: "Damaturu city",
    address: "Opposite Ben Kadio Housing Estate, behind Cultural Centre, Maiduguri Road, Damaturu, Yobe State, Nigeria",
    summary: "NCMM-listed museum stop in the Yobe capital. Confirm gallery access and current security/travel guidance before visiting.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Damaturu Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["Damaturu","Yobe"]
  },
  {
    slug: "national-museum-kaduna",
    guideSlug: "kaduna-state-travel-guide",
    name: "National Museum Kaduna",
    kind: "attraction",
    area: "Kaduna city",
    address: "33 Ali Akilu Road, Kaduna, Kaduna State, Nigeria",
    summary: "Federal heritage museum in Kaduna city; a practical cultural stop when planning the central Kaduna corridor.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Kaduna Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["Kaduna","heritage"]
  },
  {
    slug: "national-museum-akure",
    guideSlug: "ondo-state-highlights",
    name: "National Museum Akure",
    kind: "attraction",
    area: "Akure city centre",
    address: "Opposite Post Office, Oba Adesida Road, Akure, Ondo State, Nigeria",
    summary: "NCMM-listed museum in Akure, offering a city-based cultural alternative to hiking-focused Ondo trips.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Akure Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["Akure","Ondo"]
  },
  {
    slug: "national-museum-calabar",
    guideSlug: "calabar",
    name: "National Museum Calabar",
    kind: "attraction",
    area: "Calabar",
    address: "Ekpo Eyo Drive, Calabar, Cross River State, Nigeria",
    summary: "Federal museum in Calabar. This is a distinct museum listing from the Slave History Museum at Marina Resort.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Calabar Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["Calabar","Cross River"]
  },
  {
    slug: "national-museum-ogbomosho",
    guideSlug: "oyo-state-travel-guide",
    name: "National Museum Ogbomosho",
    kind: "attraction",
    area: "Ogbomosho",
    address: "3 Museum Street, off Sunsun Road, Ogbomosho, Oyo State, Nigeria",
    summary: "NCMM-listed museum in Ogbomosho for travellers extending an Oyo cultural trip beyond Ibadan.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Ogbomosho Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["Ogbomosho","Oyo"]
  },
  {
    slug: "national-museum-lafia",
    guideSlug: "nasarawa-state-travel-guide",
    name: "National Museum Lafia",
    kind: "attraction",
    area: "Lafia",
    address: "Behind Deputy Governor's Office, Shendam Road, Lafia, Nasarawa State, Nigeria",
    summary: "NCMM-listed museum location in Lafia, a city heritage option along a wider Nasarawa travel plan.",
    cost: "Confirm current admission charges with the museum before visiting",
    hours: "Confirm gallery opening days and hours directly before travelling.",
    mapQuery: "National Museum Lafia Nigeria",
    source: { label: "NCMM official national museums directory", href: "https://museum.ng/national-museums-list/" },
    checkedAt: "2026-10-08",
    tags: ["Lafia","Nasarawa"]
  }
];
