import type { ExplorePlace } from "@/lib/explore-places";

export const exploreGrowthPlacesWave8: ExplorePlace[] = [
{slug:"igbo-olodumare",guideSlug:"ondo-nature-heritage",name:"Igbo Olodumare",kind:"nature",area:"Oke-Igbo",address:"Oke-Igbo, Ile Oluji/Okeigbo LGA, Ondo State, Nigeria",summary:"Mythical forest made famous by D.O. Fagunwa and promoted by Ondo State as a sacred cultural-heritage site.",cost:"Confirm current community access and guide charges",hours:"Daylight visit recommended; respect local cultural rules.",mapQuery:"Igbo Olodumare Oke Igbo Ondo",source:{label:"Ondo State Government — Tourism",href:"https://www.ondostate.gov.ng/tourism"},checkedAt:"2026-10-07",tags:["forest","cultural heritage","Ondo"]},
{slug:"olowo-wildlife-park",guideSlug:"ondo-nature-heritage",name:"Olowo Wildlife Park",kind:"nature",area:"Owo",address:"Owo, Ondo State, Nigeria",summary:"Wildlife park promoted by Ondo State with primates, birds and reptiles in natural-style habitats.",cost:"Confirm current admission before visiting",hours:"Confirm current visitor hours.",mapQuery:"Olowo Wildlife Park Owo Ondo",source:{label:"Ondo State Government — Tourism",href:"https://www.ondostate.gov.ng/tourism"},checkedAt:"2026-10-07",tags:["wildlife","Owo","Ondo"]},
{slug:"igbokoda-waterfront",guideSlug:"ondo-nature-heritage",name:"Igbokoda Waterfront",kind:"nature",area:"Ilaje",address:"Igbokoda, Ilaje LGA, Ondo State, Nigeria",summary:"Riverine waterfront promoted by Ondo State for fishing, boat rides and mangrove exploration.",cost:"Boat and activity charges vary; confirm locally",hours:"Use daylight and confirm marine conditions before travel.",mapQuery:"Igbokoda Waterfront Ondo",source:{label:"Ondo State Government — Tourism",href:"https://www.ondostate.gov.ng/tourism"},checkedAt:"2026-10-07",tags:["waterfront","mangrove","Ondo"]},

{slug:"ikogosi-warm-cold-springs",guideSlug:"ekiti-springs-waterfalls",name:"Ikogosi Warm & Cold Springs",kind:"nature",area:"Ikogosi-Ekiti",address:"Ikogosi-Ekiti, Ekiti State, Nigeria",summary:"Ekiti's best-known spring attraction where warm and cold sources meet.",cost:"Confirm current spring/resort admission",hours:"Confirm current visitor hours.",mapQuery:"Ikogosi Warm Springs Ekiti",source:{label:"Ekiti State Government — Tourism",href:"https://www.ekitistate.gov.ng/about-ekiti/tourism"},checkedAt:"2026-10-07",tags:["spring","nature","Ekiti"]},
{slug:"ipole-iloro-waterfall",guideSlug:"ekiti-springs-waterfalls",name:"Ipole-Iloro Waterfall",kind:"nature",area:"Ipole-Iloro",address:"Ipole-Iloro, Ekiti State, Nigeria",summary:"Waterfall within the wider Ikogosi tourism corridor.",cost:"Confirm local access and charges",hours:"Daylight visit recommended.",mapQuery:"Ipole Iloro Waterfall Ekiti",source:{label:"Ekiti State Government",href:"https://www.ekitistate.gov.ng/archives/3943"},checkedAt:"2026-10-07",tags:["waterfall","nature","Ekiti"]},
{slug:"erio-hills-ekiti",guideSlug:"ekiti-springs-waterfalls",name:"Erio Hills",kind:"nature",area:"Erio-Ekiti",address:"Erio-Ekiti, Ekiti State, Nigeria",summary:"Hill area in Ekiti's wider nature and pilgrimage corridor.",cost:"Confirm local access arrangements",hours:"Daylight visit recommended.",mapQuery:"Erio Ekiti hills",source:{label:"Ekiti State Government",href:"https://www.ekitistate.gov.ng/archives/3943"},checkedAt:"2026-10-07",tags:["hill","nature","Ekiti"]},

{slug:"lord-lugard-rest-house-lokoja",guideSlug:"lokoja",name:"Lord Lugard's Rest House",kind:"landmark",area:"Mount Patti",address:"Mount Patti, Lokoja, Kogi State, Nigeria",summary:"Colonial-era rest house on Mount Patti identified by Kogi State as a heritage attraction under restoration.",cost:"Confirm current access during restoration",hours:"Daylight visit recommended; access may change with works.",mapQuery:"Lord Lugard Rest House Mount Patti Lokoja",source:{label:"Kogi State Government — Tourism",href:"https://kogistate.gov.ng/kogi-state-where-rivers-kiss-the-sky/"},checkedAt:"2026-10-07",tags:["colonial history","Lokoja","Kogi"]},
{slug:"colonial-cemeteries-lokoja",guideSlug:"lokoja",name:"Lokoja Colonial Cemeteries",kind:"landmark",area:"Lokoja",address:"Lokoja, Kogi State, Nigeria",summary:"Colonial-era cemeteries highlighted by Kogi State as part of Lokoja's historic visitor circuit.",cost:"No standard tourist admission published",hours:"Visit respectfully in daylight and confirm local access.",mapQuery:"Colonial Cemetery Lokoja Kogi",source:{label:"Kogi State Government — Tourism",href:"https://kogistate.gov.ng/kogi-state-where-rivers-kiss-the-sky/"},checkedAt:"2026-10-07",tags:["colonial history","cemetery","Lokoja"]},
{slug:"iron-of-liberty-lokoja",guideSlug:"lokoja",name:"Iron of Liberty",kind:"landmark",area:"Lokoja",address:"Lokoja, Kogi State, Nigeria",summary:"Historic freedom monument associated with Lokoja's colonial-era heritage.",cost:"No standard admission published",hours:"Daylight visit recommended.",mapQuery:"Iron of Liberty Lokoja",source:{label:"Kogi State Government — Tourism",href:"https://kogistate.gov.ng/kogi-state-where-rivers-kiss-the-sky/"},checkedAt:"2026-10-07",tags:["history","landmark","Kogi"]},

{slug:"long-juju-arochukwu",guideSlug:"abia-war-history",name:"Long Juju of Arochukwu",kind:"landmark",area:"Arochukwu",address:"Arochukwu, Abia State, Nigeria",summary:"Major Abia heritage site that the state government has funded for tourism-site development.",cost:"Confirm community access and guide charges",hours:"Daylight visit recommended; local cultural rules apply.",mapQuery:"Long Juju Arochukwu Abia",source:{label:"Abia State Government — tourism development budget",href:"https://abiastate.gov.ng/wp-content/uploads/2025/07/Abia-State-Report-of-the-Accountant-General-for-the-year-ended-31-12-2024-for-publication-Fina-1.pdf"},checkedAt:"2026-10-07",tags:["heritage","Arochukwu","Abia"]},
{slug:"azumini-blue-river",guideSlug:"abia-war-history",name:"Azumini Blue River",kind:"nature",area:"Azumini",address:"Azumini, Ukwa East LGA, Abia State, Nigeria",summary:"River attraction identified in Abia State tourism-development spending as a priority visitor site.",cost:"Confirm current local access and activity charges",hours:"Daylight visit recommended.",mapQuery:"Azumini Blue River Abia",source:{label:"Abia State Government — tourism development budget",href:"https://abiastate.gov.ng/wp-content/uploads/2025/07/Abia-State-Report-of-the-Accountant-General-for-the-year-ended-31-12-2024-for-publication-Fina-1.pdf"},checkedAt:"2026-10-07",tags:["river","nature","Abia"]},
{slug:"colonial-history-museum-aba",guideSlug:"abia-war-history",name:"National Museum of Colonial History, Aba",kind:"attraction",area:"Aba",address:"Aba, Abia State, Nigeria",summary:"Colonial-history museum in Aba that extends the Umuahia heritage route.",cost:"Confirm current admission",hours:"Confirm current opening hours.",mapQuery:"National Museum Colonial History Aba",source:{label:"National Commission for Museums and Monuments",href:"https://museum.ng/museums/"},checkedAt:"2026-10-07",tags:["museum","colonial history","Abia"]},

{slug:"ogbunike-caves",guideSlug:"anambra-heritage",name:"Ogbunike Caves",kind:"nature",area:"Ogbunike",address:"Ogbunike, Oyi LGA, Anambra State, Nigeria",summary:"Major cave system with strong cultural and community significance.",cost:"Confirm current community/site charges",hours:"Visit in daylight and confirm access rules.",mapQuery:"Ogbunike Caves Anambra",source:{label:"Anambra State Ministry of Tourism",href:"https://demos.anambrastate.gov.ng/anambra-state-ministry-of-tourism/"},checkedAt:"2026-10-07",tags:["cave","nature","Anambra"]},
{slug:"iyi-enu-hospital-cave",guideSlug:"anambra-heritage",name:"Iyi-Enu Hospital Cave",kind:"nature",area:"Ogidi / Iyi-Enu",address:"Iyi-Enu area, Anambra State, Nigeria",summary:"Cave site specifically identified by the Anambra State Ministry of Tourism among attractions it develops and promotes.",cost:"Confirm current site access and guide arrangements",hours:"Daylight visit recommended.",mapQuery:"Iyi Enu Hospital Cave Anambra",source:{label:"Anambra State Ministry of Tourism — Services",href:"https://demos.anambrastate.gov.ng/anambra-state-ministry-of-tourism/services.html"},checkedAt:"2026-10-07",tags:["cave","heritage","Anambra"]},
{slug:"igbo-ukwu-archaeological-sites",guideSlug:"anambra-heritage",name:"Igbo-Ukwu Archaeological Sites",kind:"landmark",area:"Igbo-Ukwu",address:"Igbo-Ukwu, Aguata LGA, Anambra State, Nigeria",summary:"Archaeological heritage associated with sophisticated early Igbo metalwork.",cost:"Confirm current site access",hours:"Confirm current visitor arrangements.",mapQuery:"Igbo Ukwu archaeological site Anambra",source:{label:"Anambra State Ministry of Tourism",href:"https://demos.anambrastate.gov.ng/anambra-state-ministry-of-tourism/"},checkedAt:"2026-10-07",tags:["archaeology","Igbo heritage","Anambra"]},

{slug:"matan-fada-river-argungu",guideSlug:"kebbi-heritage",name:"Matan Fada River",kind:"nature",area:"Argungu",address:"Matan Fada River, Argungu, Kebbi State, Nigeria",summary:"River venue at the heart of the Argungu International Fishing and Cultural Festival.",cost:"Public river access varies; festival activities are event-specific",hours:"Daylight visit recommended; festival-season access differs.",mapQuery:"Matan Fada River Argungu Kebbi",source:{label:"Kebbi State Investment Promotion Agency — Tourism",href:"https://kipa.kebbistate.gov.ng/wp-content/uploads/2023/12/PRIORITY-INVESTMENT-SECTORS.pdf"},checkedAt:"2026-10-07",tags:["river","Argungu","Kebbi"]},
{slug:"birnin-kebbi-royal-horse-racing-club",guideSlug:"kebbi-heritage",name:"Birnin Kebbi Royal Horse Racing Club",kind:"landmark",area:"Birnin Kebbi",address:"Birnin Kebbi, Kebbi State, Nigeria",summary:"Royal horse-racing heritage asset identified by Kebbi's investment agency among notable tourism attractions.",cost:"Event access varies; confirm current programme locally",hours:"Event-dependent.",mapQuery:"Royal Horse Racing Club Birnin Kebbi",source:{label:"Kebbi State Investment Promotion Agency",href:"https://kipa.kebbistate.gov.ng/quick-win-investment-sectors/"},checkedAt:"2026-10-07",tags:["horse racing","heritage","Kebbi"]},
{slug:"kainji-lake-kebbi-shore",guideSlug:"kebbi-heritage",name:"Kainji Lake — Kebbi Shore",kind:"nature",area:"Yauri / Ngaski corridor",address:"Kainji Lake, Kebbi State, Nigeria",summary:"Large freshwater landscape with a substantial share of Kainji Lake lying within Kebbi State.",cost:"Boat and fishing activities vary; confirm local operators",hours:"Use daylight and confirm water conditions.",mapQuery:"Kainji Lake Kebbi State",source:{label:"Kebbi State Government — Fisheries Department",href:"https://kebbistate.gov.ng/ministry-animal-health-fisheries-husbandry"},checkedAt:"2026-10-07",tags:["lake","fishing","Kebbi"]},

{slug:"ngel-nyaki-forest-reserve",guideSlug:"taraba-highlands",name:"Ngel Nyaki Forest Reserve",kind:"nature",area:"Mambilla highlands",address:"Ngel Nyaki Forest Reserve, Taraba State, Nigeria",summary:"Montane forest reserve near Gashaka-Gumti with exceptional plant diversity and endangered Nigerian chimpanzees.",cost:"Confirm reserve access and guide arrangements before travel",hours:"Access is remote; daylight and local guidance are essential.",mapQuery:"Ngel Nyaki Forest Reserve Taraba",source:{label:"Nigeria National Park Service — Gashaka-Gumti visitor brochure",href:"https://nigeriaparkservice.gov.ng/blog/2023/11/17/nigeria-national-parks-service-brochure/"},checkedAt:"2026-10-07",tags:["forest","biodiversity","Taraba"]},
{slug:"gashaka-gumti-national-park",guideSlug:"taraba-highlands",name:"Gashaka-Gumti National Park",kind:"nature",area:"Gashaka / Taraba-Adamawa",address:"Gashaka-Gumti National Park, Nigeria",summary:"Nigeria's largest national park and a major protected wilderness.",cost:"Confirm park entry, guides and activities",hours:"Access depends on park operations and season.",mapQuery:"Gashaka Gumti National Park Nigeria",source:{label:"Taraba State Ministry of Heritage & Ecotourism",href:"https://tarabatourism.org.ng/"},checkedAt:"2026-10-07",tags:["national park","wildlife","Taraba"]},
{slug:"chappal-waddi",guideSlug:"taraba-highlands",name:"Chappal Waddi",kind:"nature",area:"Taraba highlands",address:"Chappal Waddi, Taraba State, Nigeria",summary:"Nigeria's highest mountain and a serious adventure destination.",cost:"Requires organised guide and transport planning",hours:"Attempt only with suitable daylight and weather.",mapQuery:"Chappal Waddi Taraba Nigeria",source:{label:"Taraba State Ministry of Heritage & Ecotourism",href:"https://tarabatourism.org.ng/"},checkedAt:"2026-10-07",tags:["mountain","hiking","Taraba"]},

{slug:"gurara-falls",guideSlug:"niger-state-nature",name:"Gurara Falls",kind:"nature",area:"Gurara",address:"Gurara Falls, Niger State, Nigeria",summary:"Major waterfall on the Abuja-Minna corridor.",cost:"Confirm current site admission",hours:"Daylight visit recommended.",mapQuery:"Gurara Falls Niger State",source:{label:"Niger State Investment Promotion Agency — Tourism",href:"https://nsipa.nigerstate.gov.ng/tourism/"},checkedAt:"2026-10-07",tags:["waterfall","nature","Niger State"]},
{slug:"zuma-rock-niger",guideSlug:"niger-state-nature",name:"Zuma Rock",kind:"nature",area:"Suleja axis",address:"Zuma Rock, Niger State, Nigeria",summary:"Iconic monolith on the approach to Abuja and Suleja.",cost:"Roadside/public views are free",hours:"Daylight viewing recommended.",mapQuery:"Zuma Rock Niger State",source:{label:"Niger State Government",href:"https://nigerstate.gov.ng/about/"},checkedAt:"2026-10-07",tags:["rock","landmark","Niger State"]},
{slug:"baro-empire-hills",guideSlug:"niger-state-nature",name:"Baro Empire Hills",kind:"nature",area:"Baro / Agaie",address:"Baro, Agaie LGA, Niger State, Nigeria",summary:"Historic hill landscape listed among Niger State tourism assets.",cost:"Confirm local access",hours:"Daylight visit recommended.",mapQuery:"Baro Empire Hills Niger State",source:{label:"Niger State Investment Promotion Agency — Tourism",href:"https://nsipa.nigerstate.gov.ng/tourism/"},checkedAt:"2026-10-07",tags:["hill","history","Niger State"]},

{slug:"moremi-statue-liberty-ile-ife",guideSlug:"osun-nature-culture",name:"Moremi Statue of Liberty",kind:"landmark",area:"Ile-Ife",address:"Ile-Ife, Osun State, Nigeria",summary:"Monument to Queen Moremi Ajasoro, highlighted by Osun State as a major Ile-Ife cultural attraction.",cost:"Public monument; confirm any managed-site access rules",hours:"Daylight visit recommended.",mapQuery:"Moremi Statue of Liberty Ile Ife",source:{label:"Osun State Government — Tourist Centres",href:"https://www.osunstate.gov.ng/tourist-centres/"},checkedAt:"2026-10-07",tags:["monument","Ile-Ife","Osun"]},
{slug:"erin-ijesha-waterfall",guideSlug:"osun-nature-culture",name:"Erin-Ijesha Waterfall",kind:"nature",area:"Erin-Ijesha",address:"Erin-Ijesha, Osun State, Nigeria",summary:"Multi-level Olumirin waterfall and one of Osun's best-known natural attractions.",cost:"Confirm current admission",hours:"Daylight visit recommended.",mapQuery:"Erin Ijesha Waterfall Osun",source:{label:"Osun State Government — Tourist Centres",href:"https://www.osunstate.gov.ng/tourist-centres/"},checkedAt:"2026-10-07",tags:["waterfall","nature","Osun"]},
{slug:"ayikunnugba-waterfall-oke-ila",guideSlug:"osun-nature-culture",name:"Ayikunnugba Waterfall",kind:"nature",area:"Oke-Ila Orangun",address:"Oke-Ila Orangun, Osun State, Nigeria",summary:"Waterfall near Oke-Ila highlighted by Osun tourism authorities.",cost:"Confirm local access and charges",hours:"Daylight visit recommended.",mapQuery:"Ayikunnugba Waterfall Oke Ila Osun",source:{label:"Osun State Government — Tourist Centres",href:"https://www.osunstate.gov.ng/tourist-centres/"},checkedAt:"2026-10-07",tags:["waterfall","nature","Osun"]}
];