export type ExploreGuideKind = "city" | "destination" | "itinerary";

export type ExploreGuide = {
  slug: string;
  title: string;
  shortTitle: string;
  kind: ExploreGuideKind;
  region: string;
  summary: string;
  intro: string[];
  bestFor: string[];
  highlights: Array<{ name: string; detail: string }>;
  planning: Array<{ label: string; detail: string }>;
  source?: { label: string; href: string };
  lastReviewed: string;
};

export const exploreGuides: ExploreGuide[] = [
  {
    slug: "lagos",
    title: "Lagos Travel Guide",
    shortTitle: "Lagos",
    kind: "city",
    region: "Lagos State",
    summary: "Plan Lagos by area: culture, nature, beaches, art and food without turning the trip into one long traffic jam.",
    intro: [
      "Lagos rewards planning by neighbourhood. Pick one or two areas for each day instead of crossing the city repeatedly, and keep generous time around airport, bridge and rush-hour journeys.",
      "This starter guide focuses on durable places and planning decisions rather than fragile lists of today's hotel prices or venue opening hours.",
    ],
    bestFor: ["Art & culture", "Beaches", "Food", "Short city breaks"],
    highlights: [
      { name: "Lekki Conservation Centre", detail: "A nature-focused stop on the Lekki axis with forest walks and elevated walkways. Confirm current admission and operating details before setting out." },
      { name: "Nike Art Gallery", detail: "A strong starting point for Nigerian visual art and craft in Lagos, especially if you want an indoor cultural stop." },
      { name: "National Museum Lagos", detail: "Useful for historical context before exploring the city's newer creative and commercial districts." },
      { name: "Tarkwa Bay", detail: "A beach outing normally reached by boat. Use a reputable operator, confirm return arrangements and check weather before departure." },
    ],
    planning: [
      { label: "Cluster your day", detail: "Plan Island, Lekki/Victoria Island and Mainland stops in separate blocks where possible." },
      { label: "Build in traffic time", detail: "Do not schedule airport transfers, cinema tickets or reservations back-to-back with cross-city journeys." },
      { label: "Treat water trips separately", detail: "Confirm boat operator, boarding point, return time, weather and life-jacket arrangements before a beach or waterfront trip." },
      { label: "Keep a return plan", detail: "For late outings, decide how you are getting back before you leave rather than depending on last-minute availability." },
    ],
    source: { label: "Lagos State Ministry of Tourism, Arts & Culture", href: "https://tourismartandculture.lagosstate.gov.ng/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "abuja",
    title: "Abuja Travel Guide",
    shortTitle: "Abuja",
    kind: "city",
    region: "Federal Capital Territory",
    summary: "A practical Abuja guide for parks, lakes, landmarks, neighbourhood dining and easy day planning around the capital.",
    intro: [
      "Abuja is easier to enjoy when you group stops by district and leave time for security checks around formal government areas.",
      "The city mixes monumental landmarks with parks, lakes, markets, galleries, restaurants and nearby hills, so a balanced itinerary can work well even on a short stay.",
    ],
    bestFor: ["City breaks", "Parks", "Landmarks", "Dining"],
    highlights: [
      { name: "Millennium Park", detail: "A central green-space stop that works well as a low-pressure break between busier parts of an Abuja day." },
      { name: "Jabi Lake", detail: "A waterfront area for relaxed afternoons, dining and recreation; check any activity operator directly before booking." },
      { name: "National Mosque & National Christian Centre", detail: "Major city landmarks. Be respectful of worship, dress requirements, photography rules and restricted areas." },
      { name: "Arts and craft shopping", detail: "Abuja has established craft and market options; compare quality and prices and keep valuables secure in busy areas." },
    ],
    planning: [
      { label: "Plan by district", detail: "Maitama, Wuse, Central Area, Jabi and Gwarinpa can be far enough apart to make poor sequencing expensive in time." },
      { label: "Respect controlled areas", detail: "Government and diplomatic zones may have photography, parking or access restrictions." },
      { label: "Check the weather", detail: "Heat and heavy rainy-season storms can change the best time for parks, hills and lake activities." },
      { label: "Arrange return transport", detail: "For evening plans or less central stops, confirm your return option before staying late." },
    ],
    source: { label: "Visit Abuja visitor information", href: "https://www.visitabuja.org/about-abuja/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "benin-city",
    title: "Benin City Travel Guide",
    shortTitle: "Benin City",
    kind: "city",
    region: "Edo State",
    summary: "Explore Benin City's royal history, bronze-casting tradition, museums and wider Edo heritage with the right cultural context.",
    intro: [
      "Benin City is strongest as a heritage trip. The best experience comes from understanding the Benin Kingdom, its art traditions and the living cultural institutions behind the places you visit.",
      "Some heritage locations are active royal, religious or community spaces rather than conventional tourist attractions, so access and photography rules should be treated seriously.",
    ],
    bestFor: ["History", "Benin art", "Culture", "Heritage"],
    highlights: [
      { name: "Benin City National Museum", detail: "A useful first stop for historical context and collections connected to Benin and wider Nigerian heritage." },
      { name: "Igun Street", detail: "Known for the city's bronze-casting tradition and craft workshops; ask before photographing people or workspaces." },
      { name: "Oba's Palace area", detail: "Central to Benin's living royal institution. Visit only areas open to the public and follow local guidance." },
      { name: "Great Benin earthworks", detail: "The historic moat and earthwork system is part of the city's larger heritage story; access varies by section." },
    ],
    planning: [
      { label: "Start with context", detail: "A museum or knowledgeable local guide can make later heritage stops much more meaningful." },
      { label: "Ask before photographing", detail: "Royal, sacred and workshop settings may restrict photography even when the surrounding area is public." },
      { label: "Separate city and day trips", detail: "Okomu and other Edo attractions sit outside the central city and need their own transport plan." },
      { label: "Confirm access", detail: "Palace-related and heritage sites can change visitor access for ceremonies, maintenance or local events." },
    ],
    source: { label: "Edo State Government tourism overview", href: "https://edostate.gov.ng/visit-edo-state-to-enjoy-her-unique-hospitality-and-tourism-signature/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "calabar",
    title: "Calabar Travel Guide",
    shortTitle: "Calabar",
    kind: "city",
    region: "Cross River State",
    summary: "Plan Calabar around history, waterfront leisure, Efik culture and the wider Cross River tourism circuit.",
    intro: [
      "Calabar works both as a city break and as the gateway to wider Cross River trips. History-focused stops, the waterfront and December events attract very different crowds, so timing changes the experience.",
      "If you are travelling around the year-end festival season, book transport and accommodation early and verify event dates rather than relying on old schedules.",
    ],
    bestFor: ["History", "Culture", "Waterfront", "December travel"],
    highlights: [
      { name: "Marina Resort", detail: "A waterfront leisure area in Calabar with recreation and visitor facilities; individual attractions inside can change, so check what is operating." },
      { name: "Slave History Museum", detail: "A history-focused stop connected to Calabar's role in the transatlantic slave trade." },
      { name: "Old Residency / museum circuit", detail: "Useful for understanding colonial-era and regional history before moving into modern Calabar." },
      { name: "Wider Cross River trips", detail: "Calabar can be a base for planning rainforest, wildlife and mountain destinations elsewhere in the state." },
    ],
    planning: [
      { label: "December needs early booking", detail: "Carnival and festive-season demand can change transport, hotel availability and road conditions." },
      { label: "Check rainfall", detail: "Outdoor and rainforest plans are more comfortable when you account for wet-season conditions." },
      { label: "Do not overpack day trips", detail: "Cross River destinations can involve substantial road travel; give major excursions a full day or more." },
      { label: "Verify individual attractions", detail: "Facilities inside resorts and leisure complexes can open, close or undergo redevelopment independently." },
    ],
    source: { label: "Calabar Municipal tourist attractions", href: "https://calabar.municipal.crossriverstate.gov.ng/tourist-attractions" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "port-harcourt",
    title: "Port Harcourt Travel Guide",
    shortTitle: "Port Harcourt",
    kind: "city",
    region: "Rivers State",
    summary: "Use Port Harcourt as a base for parks, food, culture and carefully planned waterfront or riverine excursions.",
    intro: [
      "Port Harcourt is best approached as both an urban destination and a gateway to Rivers State. Build the city part around food, parks and cultural experiences, then plan riverine or coastal trips separately.",
      "Water-based excursions need more preparation than ordinary city sightseeing: use an established operator and confirm transport, weather and local access conditions.",
    ],
    bestFor: ["Food", "Parks", "Culture", "Riverine trips"],
    highlights: [
      { name: "Port Harcourt Pleasure Park", detail: "A major urban recreation stop that works well for families, relaxed afternoons and a break from road-heavy sightseeing." },
      { name: "City food culture", detail: "Build time around Rivers cuisine rather than treating meals as an afterthought; ask locals for current, well-regarded options." },
      { name: "Bonny Island planning", detail: "A historically and economically significant island trip that requires transport and access planning rather than a spontaneous detour." },
      { name: "Rivers coastal destinations", detail: "The state tourism agency highlights destinations beyond the city; use local guidance for current routes and conditions." },
    ],
    planning: [
      { label: "Separate land and water days", detail: "Do not make a riverine trip depend on a tight city schedule." },
      { label: "Use established operators", detail: "For boats and remote coastal stops, verify the operator, boarding point, life-jacket arrangements and return plan." },
      { label: "Watch the weather", detail: "Heavy rainfall can affect road, water and outdoor plans quickly." },
      { label: "Ask about local access", detail: "Conditions for specific riverine communities or sites may change; current local guidance matters." },
    ],
    source: { label: "Rivers State Tourism Development Agency", href: "https://rstda.rv.gov.ng/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "kano",
    title: "Kano Travel Guide",
    shortTitle: "Kano",
    kind: "city",
    region: "Kano State",
    summary: "Discover Kano's old-city history, markets, museums and landmarks with practical guidance on culture, dress and photography.",
    intro: [
      "Kano's strongest visitor experience is cultural and historical. The old city, markets and museums make more sense when you understand the city's long role in trans-Saharan trade and Hausa history.",
      "Dress and behaviour should fit the local setting, particularly around religious, royal and traditional spaces.",
    ],
    bestFor: ["History", "Markets", "Architecture", "Culture"],
    highlights: [
      { name: "Gidan Makama Museum", detail: "A key place to build context around Kano's history, traditional architecture and material culture." },
      { name: "Kurmi Market", detail: "A historic commercial area whose long trading tradition remains part of Kano's identity." },
      { name: "Dala Hill", detail: "Closely connected to the early history of Kano; plan the visit in cooler parts of the day." },
      { name: "Old-city walls and gates", detail: "Use them as part of a wider old-city route rather than isolated photo stops, and ask before photographing people." },
    ],
    planning: [
      { label: "Dress for the setting", detail: "Modest clothing is the practical choice for markets, traditional areas and religious landmarks." },
      { label: "Ask before photographing", detail: "People, worship spaces, royal areas and some security-sensitive locations may not welcome photography." },
      { label: "Plan for heat", detail: "Outdoor walking is easier earlier or later in the day, with water and sun protection." },
      { label: "Allow for prayer times", detail: "Friday prayers and daily worship can affect traffic, opening patterns and access around major religious areas." },
    ],
    source: { label: "Kano State Government history", href: "https://kanostate.gov.ng/history/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "jos",
    title: "Jos Travel Guide",
    shortTitle: "Jos",
    kind: "city",
    region: "Plateau State",
    summary: "Plan a Jos highland break around museums, wildlife, rock formations, cooler weather and wider Plateau scenery.",
    intro: [
      "Jos and the Plateau reward travellers who mix city stops with outdoor scenery. The climate can feel different from much of Nigeria, but rain, fog and road conditions still need to be part of your plan.",
      "For hills, rocks and less formal nature sites, local guidance is more valuable than relying on an old blog post or map pin.",
    ],
    bestFor: ["Highlands", "Hiking", "Museums", "Nature"],
    highlights: [
      { name: "Jos Museum", detail: "A foundational cultural stop for Plateau and Nigerian history before heading to outdoor sites." },
      { name: "Jos Wildlife Park", detail: "A long-established recreation and wildlife stop; confirm current visitor conditions before travelling." },
      { name: "Shere Hills", detail: "A major Plateau highland destination for scenery and climbing; go with appropriate local guidance for the route you choose." },
      { name: "Riyom Rock", detail: "A distinctive rock formation south of Jos that fits naturally into a broader Plateau road trip." },
    ],
    planning: [
      { label: "Pack for changing weather", detail: "Highland conditions can shift quickly, especially in the rainy season and around exposed viewpoints." },
      { label: "Use local guidance outdoors", detail: "For hiking or unfamiliar rock routes, do not depend only on a map pin." },
      { label: "Keep road time realistic", detail: "Plateau attractions can be spread across different local-government areas." },
      { label: "Check current access", detail: "Nature sites and parks may change opening or access arrangements; verify shortly before travel." },
    ],
    source: { label: "Visit Plateau tourism platform", href: "https://visitplateau.com/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "enugu",
    title: "Enugu Travel Guide",
    shortTitle: "Enugu",
    kind: "city",
    region: "Enugu State",
    summary: "Explore Enugu's hills, forests, lakes and nearby waterfalls while accounting for ongoing tourism upgrades and road travel.",
    intro: [
      "Enugu is a strong base for a nature-heavy break because several of its best-known attractions sit outside the dense city centre.",
      "The state has been upgrading tourism sites, so current access can differ from older travel posts. Verify the specific site before building a day around it.",
    ],
    bestFor: ["Nature", "Hills", "Waterfalls", "Weekend breaks"],
    highlights: [
      { name: "Ngwo Pine Forest", detail: "A popular forest-and-cave outing near Enugu. Confirm current access and any redevelopment work before travelling." },
      { name: "Nike Lake", detail: "A calmer city-side option that can balance a trip dominated by road journeys and hikes." },
      { name: "Milken Hills", detail: "Known for views over Enugu; use a safe access route and avoid relying on an unverified shortcut." },
      { name: "Awhum Waterfall & Cave", detail: "A well-known day-trip destination outside central Enugu. Check access status, road conditions and local rules in advance." },
    ],
    planning: [
      { label: "Verify upgraded sites", detail: "Enugu State has announced tourism redevelopment at several natural attractions, so old directions may be outdated." },
      { label: "Give nature trips a full block", detail: "Do not squeeze waterfalls or forest trips between fixed city appointments." },
      { label: "Prepare for rain", detail: "Trails, rocks and access roads can change significantly after heavy rainfall." },
      { label: "Use known access routes", detail: "For hills and caves, prefer current local guidance over unofficial shortcuts." },
    ],
    source: { label: "Enugu State Government 2026 tourism update", href: "https://enugustate.gov.ng/2025/12/02/full-text-of-the-proposed-2026-budget-of-renewed-momentum-presented-by-governor-peter-mbah-to-the-house-of-assembly-today/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "obudu-mountain-resort",
    title: "Obudu Mountain Resort Guide",
    shortTitle: "Obudu Mountain Resort",
    kind: "destination",
    region: "Cross River State",
    summary: "Plan Obudu as a mountain destination, with realistic transport, weather and facility checks before the long journey.",
    intro: [
      "Obudu is a destination trip rather than a quick Calabar add-on. Road logistics, accommodation, mountain weather and the status of individual resort facilities should all be confirmed before departure.",
      "Cross River State announced a new concession and rehabilitation programme in 2026, including work on the cable car and hospitality infrastructure. Do not assume every legacy attraction is operating simply because it appears in older travel material.",
    ],
    bestFor: ["Mountain scenery", "Nature", "Resort stays", "Long weekends"],
    highlights: [
      { name: "Highland viewpoints", detail: "The mountain landscape is the core reason to visit; give yourself enough daylight to enjoy it rather than arriving late and leaving early." },
      { name: "Becheve Nature Reserve", detail: "One of the nature-oriented experiences associated with the resort area; confirm guided-access arrangements locally." },
      { name: "Nature walks", detail: "Shorter guided walks can be a better choice than trying to cover every attraction in one day." },
      { name: "Resort recreation", detail: "Facilities can change during rehabilitation. Confirm what is actually open for your dates before paying or travelling." },
    ],
    planning: [
      { label: "Confirm transport end-to-end", detail: "Plan the full road journey, fuel stops, driver arrangements and arrival time before setting out." },
      { label: "Check mountain weather", detail: "Visibility, rain and cooler temperatures can change what you can comfortably do." },
      { label: "Verify cable-car status", detail: "The state announced cable-car rehabilitation in 2026, so direct confirmation is essential before making it central to your itinerary." },
      { label: "Confirm rooms and facilities", detail: "Get current accommodation and activity confirmation directly from the resort or operator, not from an old listing." },
    ],
    source: { label: "Cross River State 2026 Obudu rehabilitation update", href: "https://news.crossriverstate.gov.ng/obudu-ranch-concession-will-transform-obanliku-create-jobs-boost-tourism-gov-otu/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "yankari-game-reserve",
    title: "Yankari Game Reserve Guide",
    shortTitle: "Yankari Game Reserve",
    kind: "destination",
    region: "Bauchi State",
    summary: "Prepare for wildlife viewing, Wikki Warm Spring and a multi-day reserve visit with the right season and logistics.",
    intro: [
      "Yankari is one of Nigeria's best-known wildlife destinations and is far enough from Bauchi city that it should be planned as its own trip.",
      "Bauchi State notes that wildlife viewing is generally better in the dry season, when animals are more likely to gather around water sources. Always confirm current reserve rules, accommodation and guided-drive arrangements.",
    ],
    bestFor: ["Wildlife", "Warm spring", "Nature", "Multi-day trips"],
    highlights: [
      { name: "Wildlife viewing", detail: "The reserve is known for species including elephants, baboons, buffalo and other wildlife; sightings are never guaranteed." },
      { name: "Wikki Warm Spring", detail: "A signature Yankari attraction and a natural break from vehicle-based wildlife activities." },
      { name: "Marshall Caves", detail: "Part of the wider historical and natural-interest circuit within the reserve." },
      { name: "Dry-season planning", detail: "Bauchi State tourism guidance says wildlife is generally easier to watch between November and May." },
    ],
    planning: [
      { label: "Plan more than a few hours", detail: "The travel distance and reserve scale make an overnight or multi-day plan more practical than a rushed stop." },
      { label: "Confirm guided activities", detail: "Check the current process for game drives, guides, vehicle requirements and restricted areas." },
      { label: "Book accommodation directly", detail: "Verify room availability and payment instructions using current reserve or official channels." },
      { label: "Pack for wildlife conditions", detail: "Bring water, sun protection, suitable footwear and realistic expectations about sightings." },
    ],
    source: { label: "Bauchi State Government tourism guide", href: "https://www.bauchistate.gov.ng/tourism/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "weekend-trips-from-lagos",
    title: "Weekend Trips from Lagos",
    shortTitle: "Weekend trips from Lagos",
    kind: "itinerary",
    region: "South West Nigeria",
    summary: "Choose a weekend escape from Lagos by travel effort, trip style and how much road time you actually want.",
    intro: [
      "A good Lagos weekend trip is not just a list of places. The deciding factor is how much of the weekend you are willing to spend in traffic or on the road.",
      "Leave Friday-night and Sunday-return congestion in your plan, and verify accommodation or attraction access before driving several hours for a single stop.",
    ],
    bestFor: ["2-day breaks", "Road trips", "Heritage", "Nature"],
    highlights: [
      { name: "Badagry heritage day or overnight", detail: "A history-focused option within Lagos State. Build the trip around verified heritage sites instead of trying to rush every stop." },
      { name: "Abeokuta & Olumo Rock", detail: "A classic Ogun State city-and-landmark combination that can work as a full day or relaxed overnight." },
      { name: "Epe and the eastern Lagos axis", detail: "A lower-intensity option if your priority is food, water-side scenery and a slower pace rather than a long interstate drive." },
      { name: "Ibadan city break", detail: "Works better as an overnight when you want food, culture and multiple city stops rather than one attraction." },
    ],
    planning: [
      { label: "Choose by road time", detail: "Pick the destination that leaves enough of the weekend for the actual experience, not just the drive." },
      { label: "Avoid optimistic departure times", detail: "Friday evenings and Sunday returns can add major delays; leave margin around check-in and tickets." },
      { label: "Verify the anchor attraction", detail: "If one attraction is the reason for the trip, confirm its access before committing to the journey." },
      { label: "Keep the return simple", detail: "Do not stack a final late activity onto the same day as a long drive back into Lagos." },
    ],
    source: { label: "Lagos State Ministry of Tourism, Arts & Culture", href: "https://tourismartandculture.lagosstate.gov.ng/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "ibadan",
    title: "Ibadan Travel Guide",
    shortTitle: "Ibadan",
    kind: "city",
    region: "Oyo State",
    summary: "Explore Ibadan through its hilltop views, civic landmarks, gardens, museums and strong food culture without overpacking the day.",
    intro: [
      "Ibadan is spread out, so the best plan is to group heritage stops around the older city and pair them with one or two more relaxed attractions rather than crossing town repeatedly.",
      "The city works well as an overnight from Lagos when you want enough time for history, food and a slower afternoon without turning the trip into a return-road sprint.",
    ],
    bestFor: ["History", "City breaks", "Food", "Viewpoints"],
    highlights: [
      { name: "Bower's Tower", detail: "A hilltop landmark on Oke-Are with broad views over Ibadan; confirm access conditions before climbing." },
      { name: "Agodi Gardens", detail: "A central leisure stop that works well for a quieter afternoon between busier city activities." },
      { name: "National Museum of Unity", detail: "A useful cultural stop for Nigerian history and material culture." },
      { name: "Mapo Hall", detail: "One of Ibadan's major civic landmarks and an easy anchor for exploring the older city." },
    ],
    planning: [
      { label: "Group the old city", detail: "Mapo, Oke-Are and nearby heritage areas are easier to combine than mixing them with far-out stops." },
      { label: "Leave road margin", detail: "Traffic can build quickly around major junctions, markets and intercity approaches." },
      { label: "Confirm attraction access", detail: "Some heritage sites have variable opening or guided-access arrangements." },
      { label: "Stay overnight if possible", detail: "An overnight makes food, culture and multiple attractions much easier to enjoy than a rushed day return." },
    ],
    source: { label: "Oyo State Government tourism overview", href: "https://oyostate.gov.ng/about-oyo-state/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "abeokuta",
    title: "Abeokuta Travel Guide",
    shortTitle: "Abeokuta",
    kind: "city",
    region: "Ogun State",
    summary: "Plan Abeokuta around Egba history, adire culture and the city's best-known rock landmark.",
    intro: [
      "Abeokuta is compact enough for a focused heritage day, but it is more rewarding when you leave time for both Olumo Rock and the living craft and royal traditions around the older city.",
      "Use Olumo Rock as one anchor rather than the whole trip; the markets, palace area and historic halls add much more context.",
    ],
    bestFor: ["Heritage", "Craft", "Day trips", "Rock landscapes"],
    highlights: [
      { name: "Olumo Rock", detail: "The city's best-known landmark and a natural viewpoint tied closely to Egba history." },
      { name: "Itoku Adire Market", detail: "A practical place to see and buy adire textiles; compare quality and ask before photographing traders." },
      { name: "Alake's Palace", detail: "A living royal institution in Ake; respect access rules, ceremonies and photography restrictions." },
      { name: "Centenary Hall", detail: "A historic civic building in the Ake area that fits naturally into a heritage-focused city circuit." },
    ],
    planning: [
      { label: "Start early", detail: "Outdoor climbing and market visits are more comfortable before the hottest part of the day." },
      { label: "Pair nearby heritage stops", detail: "Ake and Itoku can be combined more efficiently than repeatedly crossing the city." },
      { label: "Ask before photographing", detail: "Markets, palace spaces and craft workshops can have local rules or preferences." },
      { label: "Check Olumo access", detail: "Verify current entrance, guide and facility arrangements before travelling primarily for the rock." },
    ],
    source: { label: "Ogun State investment and tourism update", href: "https://invest.ogunstate.gov.ng/blogdetails?id=7" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "osogbo",
    title: "Osogbo Travel Guide",
    shortTitle: "Osogbo",
    kind: "city",
    region: "Osun State",
    summary: "Explore Osogbo through the Sacred Grove, Yoruba art, palace heritage and the city's long connection to the Osun festival.",
    intro: [
      "Osogbo's strongest visitor experience comes from treating culture as the centre of the trip rather than as a quick photo stop.",
      "The Sacred Grove, artists and traditional institutions are living cultural spaces, so respectful behaviour and attention to access rules matter.",
    ],
    bestFor: ["Yoruba culture", "Art", "Heritage", "Festivals"],
    highlights: [
      { name: "Osun-Osogbo Sacred Grove", detail: "A UNESCO World Heritage cultural landscape and the city's most important heritage site." },
      { name: "Nike Art Centre Osogbo", detail: "A strong stop for local art traditions, textiles and the wider Osogbo school of creativity." },
      { name: "Ataoja Palace", detail: "A living royal institution connected to Osogbo's history and the Osun festival." },
      { name: "Osun-Osogbo Festival", detail: "The annual festival draws large crowds; verify dates and plan accommodation and transport early." },
    ],
    planning: [
      { label: "Treat sacred spaces respectfully", detail: "Follow local guidance around worship areas, photography and ceremonial activity." },
      { label: "Festival travel needs planning", detail: "Crowds, traffic and accommodation demand rise sharply around the Osun-Osogbo festival." },
      { label: "Add an art stop", detail: "Pairing the grove with Osogbo's art centres gives the city visit more context." },
      { label: "Confirm same-day access", detail: "Palace or cultural-site access can change around ceremonies and maintenance." },
    ],
    source: { label: "Osun State tourist centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "ile-ife",
    title: "Ile-Ife Heritage Guide",
    shortTitle: "Ile-Ife",
    kind: "city",
    region: "Osun State",
    summary: "A heritage-focused Ile-Ife guide for royal history, museums, monuments and major Yoruba cultural sites.",
    intro: [
      "Ile-Ife is best approached as a living heritage city, not just a checklist of monuments.",
      "Many important locations remain active royal or spiritual spaces, so visitor access, dress, photography and ceremony rules should be confirmed locally.",
    ],
    bestFor: ["Yoruba history", "Museums", "Royal heritage", "Culture"],
    highlights: [
      { name: "Ooni of Ife Palace", detail: "The royal centre of Ile-Ife and one of the city's most important living institutions." },
      { name: "National Museum Ile-Ife", detail: "A useful stop for archaeological and artistic context before visiting other heritage locations." },
      { name: "Moremi Statue of Liberty", detail: "A prominent monument honouring Moremi Ajasoro and a clear visual landmark in the city." },
      { name: "Oranmiyan Staff", detail: "One of Ile-Ife's well-known historic monuments and part of the wider royal-heritage circuit." },
    ],
    planning: [
      { label: "Ask about palace access", detail: "Royal ceremonies and official activity can affect what visitors may see on a given day." },
      { label: "Start with the museum", detail: "Museum context helps make the city's monuments and artistic traditions easier to understand." },
      { label: "Respect sacred sites", detail: "Some locations are active spiritual spaces rather than conventional tourist attractions." },
      { label: "Keep the day focused", detail: "A small number of well-explained heritage stops is more useful than rushing through every landmark." },
    ],
    source: { label: "Osun State tourist centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "ondo-state-highlights",
    title: "Ondo State Nature & Heritage Guide",
    shortTitle: "Ondo State highlights",
    kind: "destination",
    region: "Ondo State",
    summary: "Build an Ondo State trip around Idanre Hills, Owo heritage and nature stops instead of treating the state as a single-city visit.",
    intro: [
      "Ondo State's strongest visitor circuit is spread across several towns and landscapes, so it works better as a road trip than as one tightly packed city itinerary.",
      "Idanre Hills is the obvious anchor, while Owo's museum heritage and nature areas around Akure add variety.",
    ],
    bestFor: ["Hiking", "Heritage", "Road trips", "Nature"],
    highlights: [
      { name: "Idanre Hills", detail: "A major natural and heritage site with a long climb, historic structures and wide views; plan footwear, water and weather carefully." },
      { name: "Owo Museum of Antiquities", detail: "A cultural stop focused on the history and artistic heritage of the old Owo Kingdom." },
      { name: "Akure Forest Reserve", detail: "A nature-focused option for travellers interested in forest environments and bird life." },
      { name: "Dry-season travel", detail: "Ondo State tourism guidance recommends the drier months for easier outdoor planning." },
    ],
    planning: [
      { label: "Treat it as a road circuit", detail: "Idanre, Owo and Akure are separate stops; build realistic driving time into the trip." },
      { label: "Prepare for the climb", detail: "Idanre is physically demanding for some visitors; take water and use suitable footwear." },
      { label: "Verify local guides", detail: "For hill, forest or heritage access, confirm current guide and entry arrangements locally." },
      { label: "Avoid overpacking one day", detail: "Give major nature sites enough time rather than trying to combine distant towns in one rushed loop." },
    ],
    source: { label: "Ondo State Government tourism", href: "https://ondostate.gov.ng/tourism" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "ekiti-nature-circuit",
    title: "Ekiti Nature & Springs Guide",
    shortTitle: "Ekiti nature circuit",
    kind: "destination",
    region: "Ekiti State",
    summary: "Plan an Ekiti road trip around warm springs, waterfalls, hills and quieter nature stops rather than trying to treat the state as one attraction.",
    intro: [
      "Ekiti's official tourism material highlights a cluster of springs, waterfalls, hills and heritage sites spread across several towns.",
      "A practical visit works best as a road circuit with realistic driving time and same-day checks for access, guides and weather conditions.",
    ],
    bestFor: ["Nature", "Waterfalls", "Hiking", "Road trips"],
    highlights: [
      { name: "Ikogosi Warm Springs", detail: "The state's best-known nature attraction, where warm and cold springs meet while retaining distinct temperatures." },
      { name: "Arinta Waterfalls", detail: "A waterfall area at Ipole-Iloro that fits naturally into an Ekiti West nature itinerary." },
      { name: "Fajuyi Memorial Park", detail: "A more accessible Ado-Ekiti stop that adds civic history to a nature-focused trip." },
      { name: "Olosunta & Orole Hills", detail: "Hill landscapes around Ikere-Ekiti for travellers interested in views and more active outings." },
    ],
    planning: [
      { label: "Use a road-trip plan", detail: "The attractions sit in different towns, so allow real travel time rather than stacking them tightly." },
      { label: "Check outdoor access", detail: "Rain, path conditions and local access arrangements can change the experience at waterfalls and hills." },
      { label: "Start major nature stops early", detail: "Earlier visits leave more daylight for walking, return travel and weather changes." },
      { label: "Verify resort facilities", detail: "For Ikogosi, confirm current accommodation, pool and visitor-facility availability directly before relying on them." },
    ],
    source: { label: "Ekiti State Bureau of Tourism Development", href: "https://www.ekitistate.gov.ng/bureau-of-tourism-development" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "kwara-highlights",
    title: "Kwara State Travel Highlights",
    shortTitle: "Kwara highlights",
    kind: "destination",
    region: "Kwara State",
    summary: "Combine Ilorin's landmarks with Kwara's waterfall and heritage sites using a realistic multi-stop road plan.",
    intro: [
      "Kwara combines city landmarks in Ilorin with nature and heritage attractions that sit much farther away.",
      "Keep Ilorin as one cluster and give Owu Falls or Esie their own travel block rather than assuming every attraction is close to the state capital.",
    ],
    bestFor: ["Waterfalls", "Heritage", "Architecture", "Road trips"],
    highlights: [
      { name: "Ilorin Central Mosque", detail: "A major city landmark that dominates the central Ilorin skyline; visit respectfully around worship activity." },
      { name: "Flower Garden", detail: "A government-recognised green-space and leisure location in Ilorin's GRA." },
      { name: "Owu Falls", detail: "A major waterfall attraction in the state that needs its own transport and outdoor-access plan." },
      { name: "Esie Museum", detail: "One of Kwara's key heritage attractions, known for its large collection of soapstone figures." },
    ],
    planning: [
      { label: "Separate Ilorin and rural stops", detail: "Owu Falls and Esie need more road time than city attractions." },
      { label: "Plan waterfall conditions", detail: "Weather and road conditions can affect access; verify locally before departure." },
      { label: "Respect worship spaces", detail: "Dress, photography and visitor movement at the Central Mosque should follow local guidance." },
      { label: "Avoid late rural returns", detail: "Build enough daylight into trips outside Ilorin for the return journey." },
    ],
    source: { label: "Kwara State Government tourism", href: "https://kwarastate.gov.ng/do-business/tourism/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "uyo",
    title: "Uyo Travel Guide",
    shortTitle: "Uyo",
    kind: "city",
    region: "Akwa Ibom State",
    summary: "Explore Uyo through museums, arts, entertainment and the wider Akwa Ibom leisure circuit with simple city planning.",
    intro: [
      "Uyo is a manageable city base for culture and entertainment, and it also works as the starting point for wider Akwa Ibom coastal and heritage trips.",
      "The most useful short visit combines one cultural stop, one entertainment or leisure stop and enough time for local food rather than rushing between many venues.",
    ],
    bestFor: ["Culture", "Museums", "Food", "Leisure"],
    highlights: [
      { name: "Ibom Unity Museum", detail: "A state museum stop for Akwa Ibom history, culture and identity." },
      { name: "State Centre for Arts and Culture", detail: "A cultural venue on the Olusegun Obasanjo Way axis connected to the state's arts and performance scene." },
      { name: "Ibom Tropicana Entertainment Centre", detail: "A major Uyo entertainment complex on Udo Udoma Avenue." },
      { name: "Wider waterfront trips", detail: "Akwa Ibom tourism planning can extend beyond Uyo to riverine and coastal leisure areas; confirm transport before leaving the city." },
    ],
    planning: [
      { label: "Keep city stops close", detail: "Group central Uyo venues rather than making repeated cross-city trips." },
      { label: "Confirm opening hours", detail: "Museum, arts and entertainment venue schedules can change around events." },
      { label: "Plan coastal trips separately", detail: "Waterfront destinations outside Uyo need their own transport and return plan." },
      { label: "Check event calendars", detail: "Arts and entertainment venues are more useful when you know what is actually scheduled during your visit." },
    ],
    source: { label: "Akwa Ibom State tourism-site tour", href: "https://akwaibomstate.gov.ng/a-r-i-s-e-agenda-gov-umo-eno-tours-tourism-sites-vows-to-revamp-akwa-ibom-tourism-sector/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "anambra-heritage-circuit",
    title: "Anambra Nature & Heritage Circuit",
    shortTitle: "Anambra heritage circuit",
    kind: "destination",
    region: "Anambra State",
    summary: "Plan Anambra around caves, lakes, waterfalls and Igbo heritage sites spread across several towns.",
    intro: [
      "Anambra's major tourism sites are distributed across the state rather than concentrated in Awka, so the right mental model is a road circuit.",
      "Official state tourism material highlights Ogbunike Caves, Agulu Lake, Owerre-Ezukala cave and waterfall, Igbo-Ukwu heritage and other natural sites.",
    ],
    bestFor: ["Caves", "Lakes", "Igbo heritage", "Road trips"],
    highlights: [
      { name: "Ogbunike Cave", detail: "A major cave system at Ogbunike and one of the state's best-known natural and cultural attractions." },
      { name: "Agulu Lake", detail: "A large lake at Agulu with strong local cultural significance and protected wildlife traditions." },
      { name: "Owerre-Ezukala Cave & Waterfall", detail: "A cave-and-waterfall destination in Orumba South highlighted by the state tourism ministry." },
      { name: "Igbo-Ukwu heritage", detail: "The wider Igbo-Ukwu area is important for archaeological history and bronze traditions." },
    ],
    planning: [
      { label: "Expect road travel", detail: "The major sites are in different local-government areas; do not plan them as a walkable cluster." },
      { label: "Use local guides at caves", detail: "Confirm access, footwear, water conditions and local guidance before entering cave systems." },
      { label: "Respect cultural rules", detail: "Some natural sites also have sacred or community significance; follow local instructions." },
      { label: "Check development status", detail: "Several Anambra tourism sites are being upgraded, so facilities and access can change." },
    ],
    source: { label: "Anambra State Ministry of Culture, Entertainment and Tourism", href: "https://anambrastate.gov.ng/ministry-of-culture-entertainment-and-tourism/" },
    lastReviewed: "2026-09-29",
  },

  {
    slug: "araromi-beach",
    title: "Araromi Beach Guide",
    shortTitle: "Araromi Beach",
    kind: "destination",
    region: "Ondo State",
    summary: "Plan a coastal trip to Araromi in Ilaje with realistic expectations around access, facilities, weather and the area's ongoing tourism development.",
    intro: [
      "Araromi is one of Ondo State's major coastal tourism areas and has been the focus of new state-led investment and beach-development plans.",
      "Treat it as a developing coastal destination rather than a fully standardised resort: confirm road conditions, facilities, food options and return transport shortly before travelling.",
    ],
    bestFor: ["Beach trips", "Coastline", "Day trips", "Photography"],
    highlights: [
      { name: "Araromi coastline", detail: "A long Atlantic-facing stretch promoted by Ondo State as a major tourism-development corridor." },
      { name: "Seaside events", detail: "The state has used the area for seaside carnival activity; event dates and access arrangements should be verified directly." },
      { name: "Coastal scenery", detail: "The main draw is the open coastline rather than a dense cluster of built attractions." },
      { name: "Developing visitor facilities", detail: "Government plans include improved beach facilities, so older descriptions may not match current conditions." },
    ],
    planning: [
      { label: "Confirm access before departure", detail: "Road upgrades and coastal-development work can change the best approach route." },
      { label: "Bring a return plan", detail: "Do not depend on finding late transport from the beach area after arrival." },
      { label: "Check tide and weather", detail: "Rain, surf and wind can change the value and safety of a beach day." },
      { label: "Verify facilities", detail: "Food, changing areas, accommodation and organised activities may vary by event or development phase." },
    ],
    source: { label: "Ondo State Government — Araromi coastal tourism development", href: "https://ondostate.gov.ng/news-details?id=708515" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "ebomi-lake",
    title: "Ebomi Lake Guide",
    shortTitle: "Ebomi Lake",
    kind: "destination",
    region: "Ondo State",
    summary: "Visit Ebomi Lake at Ipesi-Akoko as a quiet nature stop with local cultural significance and limited formal visitor infrastructure.",
    intro: [
      "Ebomi Lake is identified by Ondo State as a tourism asset in Akoko South-East and is included in current state development planning.",
      "This is not a heavily commercialised attraction, so local guidance, daylight travel and confirmation of current access are more important than relying on old visitor posts.",
    ],
    bestFor: ["Nature", "Lakes", "Quiet trips", "Local culture"],
    highlights: [
      { name: "Natural lake setting", detail: "The lake is one of the state's recognised inland nature attractions." },
      { name: "Ipesi-Akoko location", detail: "The destination sits outside the major city tourism circuit, making road and return planning important." },
      { name: "Cultural context", detail: "Local stories and community traditions are part of the destination experience; follow local guidance respectfully." },
      { name: "Development plans", detail: "Ondo State's 2026 planning documents include development funding for Ebomi Lake, so facilities may change over time." },
    ],
    planning: [
      { label: "Travel in daylight", detail: "Plan arrival and departure with enough daylight for unfamiliar local roads." },
      { label: "Use local guidance", detail: "Confirm the best access point and any local visitor expectations before approaching the lake." },
      { label: "Expect limited facilities", detail: "Carry water and essentials rather than assuming formal tourism services will be available." },
      { label: "Respect the environment", detail: "Avoid littering, swimming or boating unless current local guidance explicitly supports the activity." },
    ],
    source: { label: "Ondo State Ministry of Economic Planning — state profile", href: "https://mepb.on.gov.ng/meet-us/ondo-state-profile/" },
    lastReviewed: "2026-09-29",
  },
  {
    slug: "igbokoda-waterfront",
    title: "Igbokoda Waterfront Guide",
    shortTitle: "Igbokoda Waterfront",
    kind: "destination",
    region: "Ondo State",
    summary: "Use Igbokoda as a base for riverine scenery, fishing culture and carefully planned waterfront or mangrove experiences in Ilaje.",
    intro: [
      "Ondo State's tourism material highlights Igbokoda Waterfront as part of the state's coastal and riverine visitor circuit.",
      "Water-based experiences need more preparation than an ordinary roadside attraction: confirm the operator, boarding point, life-jacket arrangements, weather and return plan before setting out.",
    ],
    bestFor: ["Waterfront", "Riverine trips", "Fishing culture", "Nature"],
    highlights: [
      { name: "Igbokoda waterfront", detail: "A riverine landscape in Ilaje associated with fishing, boat movement and mangrove scenery." },
      { name: "Fishing culture", detail: "Igbokoda is an important fishing centre and offers context for Ondo's coastal economy." },
      { name: "Mangrove and creek scenery", detail: "The attraction is the wider water landscape rather than a single built monument." },
      { name: "Gateway to Ilaje", detail: "The town works as a practical starting point for wider coastal exploration when local conditions allow." },
    ],
    planning: [
      { label: "Use an established boat operator", detail: "Verify the boat, operator, life jackets, route and return time before departure." },
      { label: "Check weather first", detail: "Heavy rain, wind and poor visibility can make water trips unsuitable." },
      { label: "Protect valuables", detail: "Keep phones, documents and electronics in waterproof protection around boats and jetties." },
      { label: "Confirm local access", detail: "Water routes and community access conditions can change, so current local information matters." },
    ],
    source: { label: "Ondo State Government tourism", href: "https://ondostate.gov.ng/tourism" },
    lastReviewed: "2026-09-29",
  },
];

export function getExploreGuide(slug: string) {
  return exploreGuides.find((guide) => guide.slug === slug);
}
