import type { ExplorePlace } from "@/lib/explore-places";

export const exploreGrowthPlacesWave9: ExplorePlace[] = [
  {
    slug: "ado-awaye-suspended-lake",
    guideSlug: "oyo-state-travel-guide",
    name: "Ado-Awaye Suspended Lake",
    kind: "nature",
    area: "Ado-Awaye / Iseyin",
    address: "Ado-Awaye, Iseyin Local Government Area, Oyo State, Nigeria",
    summary: "Iyake Lake sits high on the Ado-Awaye ridge and is one of Oyo State's signature nature attractions.",
    cost: "Confirm current entrance and local-guide charges before travelling",
    hours: "Start in daylight and allow enough time for the climb and return.",
    mapQuery: "Ado Awaye Suspended Lake Oyo State",
    source: { label: "Oyo State Government — About Oyo State", href: "https://oyostate.gov.ng/about-oyo-state/" },
    checkedAt: "2026-10-07",
    tags: ["lake", "hiking", "viewpoint", "Oyo"]
  },
  {
    slug: "cocoa-house-ibadan",
    guideSlug: "oyo-state-travel-guide",
    name: "Cocoa House",
    kind: "landmark",
    area: "Dugbe",
    address: "Cocoa House, Dugbe, Ibadan, Oyo State, Nigeria",
    summary: "Historic Ibadan high-rise and one of Oyo State's best-known urban landmarks.",
    cost: "Public exterior viewing is free; interior access depends on current building operations",
    hours: "Business-building access varies; verify before planning an interior visit.",
    mapQuery: "Cocoa House Dugbe Ibadan",
    source: { label: "Oyo State Government — About Oyo State", href: "https://oyostate.gov.ng/about-oyo-state/" },
    checkedAt: "2026-10-07",
    tags: ["architecture", "history", "Ibadan", "Oyo"]
  },
  {
    slug: "iita-forest-reserve-ibadan",
    guideSlug: "oyo-state-travel-guide",
    name: "IITA Forest Reserve",
    kind: "nature",
    area: "IITA Ibadan",
    address: "International Institute of Tropical Agriculture, Ibadan, Oyo State, Nigeria",
    summary: "Mature lowland forest and lake environment highlighted by Oyo investment material for birding, walking and recreation.",
    cost: "Confirm current visitor, tour or campus-access arrangements with IITA",
    hours: "Campus and reserve access can be controlled; verify before travel.",
    mapQuery: "IITA Forest Reserve Ibadan",
    source: { label: "Oyo State Investment Promotion Agency — Tourism", href: "https://oysipa.oyostate.gov.ng/admin/uploads/INVEST-IN-TOURISM.pdf" },
    checkedAt: "2026-10-07",
    tags: ["forest", "birding", "nature", "Ibadan"]
  },
  {
    slug: "asejire-reservoir-oyo",
    guideSlug: "oyo-state-travel-guide",
    name: "Asejire Reservoir",
    kind: "nature",
    area: "Asejire",
    address: "Asejire Reservoir, Oyo State, Nigeria",
    summary: "Large reservoir east of Ibadan identified by Oyo tourism investment material as a recreation and nature asset.",
    cost: "Confirm current access and any managed activity charges before visiting",
    hours: "Use daylight and verify local access conditions.",
    mapQuery: "Asejire Reservoir Oyo State",
    source: { label: "Oyo State Investment Promotion Agency — Tourism", href: "https://oysipa.oyostate.gov.ng/admin/uploads/INVEST-IN-TOURISM.pdf" },
    checkedAt: "2026-10-07",
    tags: ["reservoir", "nature", "road trip", "Oyo"]
  },
  {
    slug: "old-oyo-national-park",
    guideSlug: "oyo-state-travel-guide",
    name: "Old Oyo National Park",
    kind: "nature",
    area: "Northern Oyo State",
    address: "Old Oyo National Park, Oyo State, Nigeria",
    summary: "Protected savanna and historical landscape around the former Oyo Empire region.",
    cost: "Confirm current park entry, guide and activity charges before travel",
    hours: "Park entry and visitor sectors should be confirmed before departure.",
    mapQuery: "Old Oyo National Park Nigeria",
    source: { label: "Oyo State Government — About Oyo State", href: "https://oyostate.gov.ng/about-oyo-state/" },
    checkedAt: "2026-10-07",
    tags: ["national park", "history", "wildlife", "Oyo"]
  },

  {
    slug: "sungbo-eredo-ogun",
    guideSlug: "ogun-state-nature-heritage-guide",
    name: "Sungbo Eredo",
    kind: "landmark",
    area: "Ijebu area",
    address: "Sungbo Eredo earthworks, Ijebu area, Ogun State, Nigeria",
    summary: "Extensive ancient earthworks associated with Ijebu history and highlighted by Ogun State for heritage revitalisation.",
    cost: "Confirm current community access and local-guide charges before visiting",
    hours: "Daylight visit recommended; use local guidance for access points.",
    mapQuery: "Sungbo Eredo Ogun State",
    source: { label: "OgunInvest — Tourism & Creative Economy", href: "https://invest.ogunstate.gov.ng/tourism-creative-economy" },
    checkedAt: "2026-10-07",
    tags: ["earthworks", "heritage", "Ijebu", "Ogun"]
  },
  {
    slug: "bilikisu-sungbo-queens-forest",
    guideSlug: "ogun-state-nature-heritage-guide",
    name: "Bilikisu Sungbo Queen's Forest",
    kind: "nature",
    area: "Ijebu corridor",
    address: "Bilikisu Sungbo heritage area, Ogun State, Nigeria",
    summary: "Forest-and-heritage landscape identified by Ogun State for conservation and visitor-facility development.",
    cost: "Confirm community access and any guide charges before travelling",
    hours: "Daylight visit recommended.",
    mapQuery: "Bilikisu Sungbo Ogun State",
    source: { label: "OgunInvest — Tourism & Creative Economy", href: "https://invest.ogunstate.gov.ng/tourism-creative-economy" },
    checkedAt: "2026-10-07",
    tags: ["forest", "heritage", "Ijebu", "Ogun"]
  },
  {
    slug: "yemoji-pool-ogun",
    guideSlug: "ogun-state-nature-heritage-guide",
    name: "Yemoji Pool",
    kind: "nature",
    area: "Ogun State",
    address: "Yemoji Pool tourism corridor, Ogun State, Nigeria",
    summary: "Natural-water attraction named by Ogun State among proposed eco-tourism development opportunities.",
    cost: "Confirm current access and any local charges before visiting",
    hours: "Visit in daylight and verify route conditions locally.",
    mapQuery: "Yemoji Pool Ogun State",
    source: { label: "OgunInvest — Tourism & Creative Economy", href: "https://invest.ogunstate.gov.ng/tourism-creative-economy" },
    checkedAt: "2026-10-07",
    tags: ["pool", "nature", "eco-tourism", "Ogun"]
  },
  {
    slug: "osuuru-springs-ogun",
    guideSlug: "ogun-state-nature-heritage-guide",
    name: "Osuuru Springs",
    kind: "nature",
    area: "Ogun State",
    address: "Osuuru Springs tourism corridor, Ogun State, Nigeria",
    summary: "Spring attraction listed by Ogun State among tourism-development opportunities around the Olumo corridor.",
    cost: "Confirm current access and local charges before visiting",
    hours: "Daylight visit recommended.",
    mapQuery: "Osuuru Springs Ogun State",
    source: { label: "OgunInvest — Tourism & Creative Economy", href: "https://invest.ogunstate.gov.ng/tourism-creative-economy" },
    checkedAt: "2026-10-07",
    tags: ["spring", "nature", "Ogun"]
  },
  {
    slug: "omo-forest-reserve-ogun",
    guideSlug: "ogun-state-nature-heritage-guide",
    name: "Omo Forest Reserve",
    kind: "nature",
    area: "Ijebu East",
    address: "Omo Forest Reserve, Ogun State, Nigeria",
    summary: "Large forest and conservation landscape identified by Ogun State for safari and conservation tourism.",
    cost: "Confirm current permission, ranger, guide and activity charges before travel",
    hours: "Protected-area access should be arranged before departure.",
    mapQuery: "Omo Forest Reserve Ogun State",
    source: { label: "OgunInvest — Tourism & Creative Economy", href: "https://invest.ogunstate.gov.ng/tourism-creative-economy" },
    checkedAt: "2026-10-07",
    tags: ["forest", "conservation", "wildlife", "Ogun"]
  },
  {
    slug: "tongeji-islands-ogun",
    guideSlug: "ogun-state-nature-heritage-guide",
    name: "Tongeji Islands",
    kind: "nature",
    area: "Ipokia coast",
    address: "Tongeji Islands, Ipokia Local Government Area, Ogun State, Nigeria",
    summary: "Coastal-island landscape listed by Ogun State among tourism-development opportunities.",
    cost: "Boat transport and community access are separately arranged; confirm current prices before travel",
    hours: "Plan marine travel in daylight and check weather and local access.",
    mapQuery: "Tongeji Islands Ogun State",
    source: { label: "OgunInvest — Tourism & Creative Economy", href: "https://invest.ogunstate.gov.ng/tourism-creative-economy" },
    checkedAt: "2026-10-07",
    tags: ["island", "coast", "boat trip", "Ogun"]
  },

  {
    slug: "milliken-hills-enugu",
    guideSlug: "enugu-state-tourism-route",
    name: "Milliken Hills",
    kind: "nature",
    area: "Enugu",
    address: "Milliken Hills, Enugu, Enugu State, Nigeria",
    summary: "Hill landscape above Enugu highlighted by the state as one of its prominent tourism assets.",
    cost: "Public viewpoints may be free; confirm guided or managed-site charges locally",
    hours: "Daylight visit recommended.",
    mapQuery: "Milliken Hills Enugu",
    source: { label: "Enugu State Investment Guide", href: "https://enugustate.gov.ng/wp-content/uploads/2024/05/ENUGU-STATE-INVESTMENT-GUIDE-Final-Version-NEW-AJUSTED.pdf" },
    checkedAt: "2026-10-07",
    tags: ["hill", "viewpoint", "Enugu"]
  },
  {
    slug: "iva-valley-enugu",
    guideSlug: "enugu-state-tourism-route",
    name: "Iva Valley",
    kind: "landmark",
    area: "Enugu",
    address: "Iva Valley, Enugu, Enugu State, Nigeria",
    summary: "Historic coal-mining and labour-history landscape identified by Enugu State as a cultural attraction.",
    cost: "Confirm current access and guided-visit arrangements locally",
    hours: "Daylight visit recommended.",
    mapQuery: "Iva Valley Enugu",
    source: { label: "Enugu State Investment Guide", href: "https://enugustate.gov.ng/wp-content/uploads/2024/05/ENUGU-STATE-INVESTMENT-GUIDE-Final-Version-NEW-AJUSTED.pdf" },
    checkedAt: "2026-10-07",
    tags: ["industrial heritage", "history", "Enugu"]
  },
  {
    slug: "iyi-nzu-ezimo-waterfall",
    guideSlug: "enugu-state-tourism-route",
    name: "Iyi-Nzu Ezimo Waterfall",
    kind: "nature",
    area: "Ezimo",
    address: "Ezimo, Enugu State, Nigeria",
    summary: "Waterfall listed in Enugu State's official investment guide among its tourism assets.",
    cost: "Confirm local entrance, guide and access charges before visiting",
    hours: "Use daylight and check seasonal road conditions.",
    mapQuery: "Iyi Nzu Ezimo Waterfall Enugu",
    source: { label: "Enugu State Investment Guide", href: "https://enugustate.gov.ng/wp-content/uploads/2024/05/ENUGU-STATE-INVESTMENT-GUIDE-Final-Version-NEW-AJUSTED.pdf" },
    checkedAt: "2026-10-07",
    tags: ["waterfall", "nature", "Enugu"]
  },
  {
    slug: "ezeagu-cave-enugu",
    guideSlug: "enugu-state-tourism-route",
    name: "Ezeagu Cave",
    kind: "nature",
    area: "Ezeagu",
    address: "Ezeagu Local Government Area, Enugu State, Nigeria",
    summary: "Cave landscape identified by Enugu State among its prominent natural tourism sites.",
    cost: "Confirm community access and guide charges before travelling",
    hours: "Visit in daylight with local guidance.",
    mapQuery: "Ezeagu Cave Enugu State",
    source: { label: "Enugu State Investment Guide", href: "https://enugustate.gov.ng/wp-content/uploads/2024/05/ENUGU-STATE-INVESTMENT-GUIDE-Final-Version-NEW-AJUSTED.pdf" },
    checkedAt: "2026-10-07",
    tags: ["cave", "nature", "Enugu"]
  },
  {
    slug: "nsude-pyramids-enugu",
    guideSlug: "enugu-state-tourism-route",
    name: "Nsude Pyramids",
    kind: "landmark",
    area: "Nsude",
    address: "Nsude, Udi Local Government Area, Enugu State, Nigeria",
    summary: "Historic earth structures being developed by Enugu State as a cultural tourism park.",
    cost: "Confirm current access while site-development work continues",
    hours: "Visit in daylight and verify construction/access status before departure.",
    mapQuery: "Nsude Pyramids Enugu",
    source: { label: "Enugu State — Tourism projects update", href: "https://works.enugustate.gov.ng/news/27" },
    checkedAt: "2026-10-07",
    tags: ["heritage", "pyramids", "culture", "Enugu"]
  },
  {
    slug: "okpatu-hill-enugu",
    guideSlug: "enugu-state-tourism-route",
    name: "Okpatu Hill",
    kind: "nature",
    area: "Okpatu",
    address: "Okpatu, Enugu State, Nigeria",
    summary: "High-elevation Enugu tourism-development site with panoramic landscape potential.",
    cost: "Confirm public access while development work is ongoing",
    hours: "Daylight visit recommended; verify construction status before travelling.",
    mapQuery: "Okpatu Hill Enugu",
    source: { label: "Enugu State — Tourism projects update", href: "https://works.enugustate.gov.ng/news/27" },
    checkedAt: "2026-10-07",
    tags: ["hill", "viewpoint", "tourism project", "Enugu"]
  },
  {
    slug: "akwuke-sand-beach-enugu",
    guideSlug: "enugu-state-tourism-route",
    name: "Akwuke Sand Beach",
    kind: "nature",
    area: "Akwuke",
    address: "Akwuke, Enugu State, Nigeria",
    summary: "Sand-beach attraction included in Enugu State's tourism-development pipeline.",
    cost: "Confirm current visitor access and local charges before travelling",
    hours: "Daylight visit recommended; check current development/access status.",
    mapQuery: "Akwuke Sand Beach Enugu",
    source: { label: "Enugu State — Tourism projects update", href: "https://works.enugustate.gov.ng/news/27" },
    checkedAt: "2026-10-07",
    tags: ["beach", "nature", "Enugu"]
  },

  {
    slug: "kurra-falls-plateau",
    guideSlug: "plateau-state-nature-guide",
    name: "Kurra Falls",
    kind: "nature",
    area: "Plateau State",
    address: "Kurra Falls, Plateau State, Nigeria",
    summary: "Waterfall identified in Plateau State's official tourism-development strategy.",
    cost: "Confirm current local access and guide charges before visiting",
    hours: "Daylight visit recommended; conditions vary by season.",
    mapQuery: "Kurra Falls Plateau State",
    source: { label: "Plateau State Tourism & Culture", href: "https://www.plateaustate.gov.ng/tourism/" },
    checkedAt: "2026-10-07",
    tags: ["waterfall", "nature", "Plateau"]
  },
  {
    slug: "pandam-game-reserve",
    guideSlug: "plateau-state-nature-guide",
    name: "Pandam Game Reserve",
    kind: "nature",
    area: "Qua'an Pan",
    address: "Pandam Game Reserve, Qua'an Pan Local Government Area, Plateau State, Nigeria",
    summary: "Wildlife and wetland reserve included in Plateau State's tourism-development planning.",
    cost: "Confirm current reserve entry, guide and activity charges before travel",
    hours: "Check current reserve operations before departure.",
    mapQuery: "Pandam Game Reserve Plateau State",
    source: { label: "Plateau State tourism strategy", href: "https://www.plateaustate.gov.ng/uploads/20190828_Plateau_State_Strategy-Plateau_State_Strategic_Plan_2017-2023.pdf" },
    checkedAt: "2026-10-07",
    tags: ["game reserve", "wildlife", "wetland", "Plateau"]
  },
  {
    slug: "solomon-lar-amusement-park",
    guideSlug: "plateau-state-nature-guide",
    name: "Solomon Lar Amusement Park",
    kind: "attraction",
    area: "Jos",
    address: "Solomon Lar Amusement Park, Jos, Plateau State, Nigeria",
    summary: "Recreation asset identified by Plateau State for major tourism-and-hospitality reconstruction.",
    cost: "Confirm current opening and activity charges while redevelopment proceeds",
    hours: "Operating status can change during reconstruction; verify before visiting.",
    mapQuery: "Solomon Lar Amusement Park Jos",
    source: { label: "Plateau State PPP framework", href: "https://plateaustate.gov.ng/uploads/DLI3/PLATEAU_STATE_FCCL%20FRAMEWORK%20.pdf" },
    checkedAt: "2026-10-07",
    tags: ["park", "family", "recreation", "Jos"]
  },
  {
    slug: "kahwang-basalt-rock-formation",
    guideSlug: "plateau-state-nature-guide",
    name: "Kahwang Basalt Rock Formation",
    kind: "nature",
    area: "Plateau State",
    address: "Kahwang area, Plateau State, Nigeria",
    summary: "Distinctive basalt landscape included in Plateau State's official tourism-development strategy.",
    cost: "Confirm local access and any guide charges before visiting",
    hours: "Daylight visit recommended.",
    mapQuery: "Kahwang Basalt Rock Plateau State",
    source: { label: "Plateau State tourism strategy", href: "https://www.plateaustate.gov.ng/uploads/20190828_Plateau_State_Strategy-Plateau_State_Strategic_Plan_2017-2023.pdf" },
    checkedAt: "2026-10-07",
    tags: ["geology", "rock formation", "Plateau"]
  },

  {
    slug: "finima-nature-park",
    guideSlug: "rivers-state-coast-nature-guide",
    name: "Finima Nature Park",
    kind: "nature",
    area: "Bonny Island",
    address: "NLNG Roundabout, behind RA3, Bonny Island, Rivers State, Nigeria",
    summary: "1,000-hectare wetland and forest conservation park with guided nature, wildlife and environmental-education experiences.",
    cost: "Confirm current tour or group-visit charges directly with the park",
    hours: "Official park hours vary by weekday/weekend; check before travel.",
    phone: "08039052657",
    website: "https://finimanaturepark.com/",
    mapQuery: "Finima Nature Park Bonny Island",
    source: { label: "Finima Nature Park official site", href: "https://finimanaturepark.com/" },
    checkedAt: "2026-10-07",
    tags: ["wetland", "wildlife", "Bonny", "Rivers"]
  },
  {
    slug: "ikuru-atlantic-beach-rivers",
    guideSlug: "rivers-state-coast-nature-guide",
    name: "Ikuru Atlantic Beach",
    kind: "nature",
    area: "Rivers coast",
    address: "Ikuru coastal area, Rivers State, Nigeria",
    summary: "Atlantic-beach destination promoted by the Rivers State Tourism Development Agency.",
    cost: "Confirm current community access, transport and activity charges before travel",
    hours: "Daylight visit recommended; check marine and weather conditions.",
    mapQuery: "Ikuru Atlantic Beach Rivers State",
    source: { label: "Rivers State Tourism Development Agency", href: "https://rstda.rv.gov.ng/" },
    checkedAt: "2026-10-07",
    tags: ["beach", "coast", "Rivers"]
  },
  {
    slug: "isaac-boro-park-port-harcourt",
    guideSlug: "rivers-state-coast-nature-guide",
    name: "Isaac Boro Park",
    kind: "attraction",
    area: "Port Harcourt",
    address: "Isaac Boro Park, Port Harcourt, Rivers State, Nigeria",
    summary: "Urban recreation and civic-history park in Port Harcourt.",
    cost: "Confirm current park/event access and any activity charges",
    hours: "Daylight visits are simplest; event schedules vary.",
    mapQuery: "Isaac Boro Park Port Harcourt",
    source: { label: "Rivers State Tourism Development Agency", href: "https://rstda.rv.gov.ng/" },
    checkedAt: "2026-10-07",
    tags: ["park", "history", "Port Harcourt"]
  },

  {
    slug: "sanda-kyarimi-park",
    guideSlug: "borno-state-travel-guide",
    name: "Sanda Kyarimi Park",
    kind: "attraction",
    area: "Maiduguri",
    address: "Sanda Kyarimi Park, Maiduguri, Borno State, Nigeria",
    summary: "Zoo and recreation park listed by Borno's investment agency among the state's tourism sites.",
    cost: "Confirm current admission and operating status before visiting",
    hours: "Verify current public opening hours.",
    mapQuery: "Sanda Kyarimi Park Maiduguri",
    source: { label: "Borno State Investment Promotion Agency — Tourism", href: "https://bornoinvest.ng/culture-and-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["zoo", "park", "Maiduguri", "Borno"]
  },
  {
    slug: "lake-alau-borno",
    guideSlug: "borno-state-travel-guide",
    name: "Lake Alau",
    kind: "nature",
    area: "Maiduguri outskirts",
    address: "Lake Alau, Borno State, Nigeria",
    summary: "Large water body near Maiduguri listed by Borno authorities among the state's tourism assets.",
    cost: "Confirm current access, safety conditions and any organised activity charges",
    hours: "Daylight visit only; re-check local conditions before travel.",
    mapQuery: "Lake Alau Borno State",
    source: { label: "Borno State Investment Promotion Agency — Tourism", href: "https://bornoinvest.ng/culture-and-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["lake", "nature", "Borno"]
  },
  {
    slug: "gwoza-hills",
    guideSlug: "borno-state-travel-guide",
    name: "Gwoza Hills",
    kind: "nature",
    area: "Gwoza",
    address: "Gwoza Hills, Gwoza Local Government Area, Borno State, Nigeria",
    summary: "Mountain landscape listed by Borno State among its tourism sites.",
    cost: "Do not travel without current local/security guidance; guide and transport costs vary",
    hours: "Only consider daylight travel after checking current official safety conditions.",
    mapQuery: "Gwoza Hills Borno",
    source: { label: "Borno State Investment Promotion Agency — Tourism", href: "https://bornoinvest.ng/culture-and-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["hills", "nature", "Gwoza", "Borno"]
  },
  {
    slug: "borno-state-museum",
    guideSlug: "borno-state-travel-guide",
    name: "Borno State Museum",
    kind: "attraction",
    area: "Maiduguri",
    address: "Borno State Museum, Maiduguri, Borno State, Nigeria",
    summary: "State museum listed by Borno authorities among the area's cultural tourism assets.",
    cost: "Confirm current admission before visiting",
    hours: "Confirm current museum opening hours.",
    mapQuery: "Borno State Museum Maiduguri",
    source: { label: "Borno State Investment Promotion Agency — Tourism", href: "https://bornoinvest.ng/culture-and-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["museum", "culture", "Maiduguri", "Borno"]
  },
  {
    slug: "lake-tilla-borno",
    guideSlug: "borno-state-travel-guide",
    name: "Lake Tilla",
    kind: "nature",
    area: "Borno State",
    address: "Lake Tilla, Borno State, Nigeria",
    summary: "Lake listed by Borno State among its tourism assets.",
    cost: "Confirm current local access, transport and any activity charges",
    hours: "Daylight visit and current local guidance recommended.",
    mapQuery: "Lake Tilla Borno State",
    source: { label: "Borno State Investment Promotion Agency — Tourism", href: "https://bornoinvest.ng/culture-and-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["lake", "nature", "Borno"]
  },
  {
    slug: "rabeh-fort-dikwa",
    guideSlug: "borno-state-travel-guide",
    name: "Rabeh's Fort",
    kind: "landmark",
    area: "Dikwa",
    address: "Rabeh's Fort, Dikwa, Borno State, Nigeria",
    summary: "Historic fort at Dikwa listed by Borno State among its cultural tourism sites.",
    cost: "Confirm current access and local-guide arrangements before travel",
    hours: "Only visit with current local/security guidance and in daylight.",
    mapQuery: "Rabeh Fort Dikwa Borno",
    source: { label: "Borno State Investment Promotion Agency — Tourism", href: "https://bornoinvest.ng/culture-and-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["fort", "history", "Dikwa", "Borno"]
  },
  {
    slug: "jarry-falls-borno",
    guideSlug: "borno-state-travel-guide",
    name: "Jarry Falls",
    kind: "nature",
    area: "Borno State",
    address: "Jarry Falls, Borno State, Nigeria",
    summary: "Waterfall listed by Borno State among its tourism sites.",
    cost: "Confirm current local access, guide and transport charges before travel",
    hours: "Daylight-only planning with current local/security guidance.",
    mapQuery: "Jarry Falls Borno State",
    source: { label: "Borno State Investment Promotion Agency — Tourism", href: "https://bornoinvest.ng/culture-and-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["waterfall", "nature", "Borno"]
  },

  {
    slug: "mary-slessor-tomb-akwa-ibom",
    guideSlug: "akwa-ibom-heritage-route",
    name: "Mary Slessor Tomb",
    kind: "landmark",
    area: "Use Ikot Oku / Ibiono Ibom",
    address: "Use Ikot Oku, Ibiono Ibom Local Government Area, Akwa Ibom State, Nigeria",
    summary: "Grave monument associated with missionary Mary Slessor, highlighted by Akwa Ibom State as a heritage site.",
    cost: "Confirm community access and any local-guide arrangements before visiting",
    hours: "Daylight visit recommended; respect memorial and community rules.",
    mapQuery: "Mary Slessor Tomb Akwa Ibom",
    source: { label: "Akwa Ibom State Government — About Akwa Ibom", href: "https://akwaibomstate.gov.ng/about-akwa-ibom/" },
    checkedAt: "2026-10-07",
    tags: ["missionary history", "heritage", "Akwa Ibom"]
  },
  {
    slug: "ukam-market-ikot-abasi",
    guideSlug: "akwa-ibom-heritage-route",
    name: "Ukam Market",
    kind: "landmark",
    area: "Ikot Abasi",
    address: "Ukam Market, Ikot Abasi, Akwa Ibom State, Nigeria",
    summary: "Market identified by Akwa Ibom State's official history with the origins of the 1929 women's anti-colonial resistance.",
    cost: "Normal market access; purchases are individually priced",
    hours: "Market activity varies by day; visit during daylight and respect active trading.",
    mapQuery: "Ukam Market Ikot Abasi Akwa Ibom",
    source: { label: "Akwa Ibom State Government — About Akwa Ibom", href: "https://akwaibomstate.gov.ng/about-akwa-ibom/" },
    checkedAt: "2026-10-07",
    tags: ["women's history", "market", "Ikot Abasi", "Akwa Ibom"]
  },
  {
    slug: "first-qua-iboe-church-ibeno",
    guideSlug: "akwa-ibom-heritage-route",
    name: "First Qua Iboe Church",
    kind: "landmark",
    area: "Ibeno",
    address: "Ibeno, Akwa Ibom State, Nigeria",
    summary: "Historic church identified by Akwa Ibom State as the first Qua Iboe Church, founded in 1887.",
    cost: "No tourist admission expected; worship and community access rules take priority",
    hours: "Active religious site — avoid disrupting worship and confirm access locally.",
    mapQuery: "First Qua Iboe Church Ibeno Akwa Ibom",
    source: { label: "Akwa Ibom State Government — About Akwa Ibom", href: "https://akwaibomstate.gov.ng/about-akwa-ibom/" },
    checkedAt: "2026-10-07",
    tags: ["church", "missionary history", "Ibeno", "Akwa Ibom"]
  }
];
