export type ExplorePlaceKind = "attraction" | "nature" | "restaurant" | "hotel" | "shopping" | "landmark";

export type ExplorePlace = {
  slug: string;
  guideSlug: string;
  name: string;
  kind: ExplorePlaceKind;
  area: string;
  address: string;
  summary: string;
  cost: string;
  costNote?: string;
  hours?: string;
  phone?: string;
  website?: string;
  mapQuery?: string;
  source?: { label: string; href: string };
  checkedAt: string;
  tags: string[];
};

export const explorePlaces: ExplorePlace[] = [
  {
    slug: "lekki-conservation-centre",
    guideSlug: "lagos",
    name: "Lekki Conservation Centre",
    kind: "nature",
    area: "Lekki",
    address: "Km 19 Lekki-Epe Expressway, Lekki Peninsula II, Lekki 106104, Lagos",
    summary: "Forest walks, elevated walkways and a nature-focused break from the city.",
    cost: "Verify current admission before travel",
    costNote: "Admission and activity charges can change; confirm directly before setting out.",
    hours: "Current listing commonly shows daytime opening; verify same-day access.",
    phone: "+234 906 546 0479",
    mapQuery: "Lekki Conservation Centre Lagos",
    source: { label: "Nigerian Conservation Foundation", href: "https://ncfnigeria.org/" },
    checkedAt: "2026-09-29",
    tags: ["nature", "family", "outdoors"],
  },
  {
    slug: "nike-art-gallery-lagos",
    guideSlug: "lagos",
    name: "Nike Art Gallery",
    kind: "attraction",
    area: "Lekki",
    address: "2 Nike Art Gallery Road, Lekki Phase I, Lekki 106104, Lagos",
    summary: "A large collection of Nigerian art, textiles and craft in an easy indoor cultural stop.",
    cost: "Gallery entry is commonly free; confirm special-event charges",
    hours: "Current listing: roughly 10:00–18:00 most days; verify before visiting.",
    phone: "+234 803 409 6656",
    mapQuery: "Nike Art Gallery Lekki Lagos",
    checkedAt: "2026-09-29",
    tags: ["art", "culture", "indoor"],
  },
  {
    slug: "national-museum-lagos",
    guideSlug: "lagos",
    name: "National Museum Lagos",
    kind: "attraction",
    area: "Onikan",
    address: "Onikan Road, Ikoyi, Lagos 102273, Lagos",
    summary: "A useful historical starting point before exploring Lagos's newer cultural districts.",
    cost: "Verify current museum admission",
    hours: "Current listing: daytime opening; verify before travel.",
    phone: "+234 1 263 6005",
    mapQuery: "National Museum Lagos Onikan",
    checkedAt: "2026-09-29",
    tags: ["history", "museum", "culture"],
  },
  {
    slug: "nok-by-alara",
    guideSlug: "lagos",
    name: "NOK by Alara",
    kind: "restaurant",
    area: "Victoria Island",
    address: "12A Akin Olugbade Street, Victoria Island, Lagos 106104, Lagos",
    summary: "Contemporary Pan-African dining behind the Alára concept store.",
    cost: "Plan about ₦45,000–₦70,000 per person for dinner",
    costNote: "Early-2026 dining estimate; individual dishes and drinks vary. Check the current menu before booking.",
    hours: "Lunch and dinner service; current listing shows separate afternoon/evening sessions.",
    phone: "+234 908 561 4815",
    website: "https://www.nokbyalara.com/",
    mapQuery: "NOK by Alara Lagos",
    source: { label: "NOK menus", href: "https://www.nokbyalara.com/menus" },
    checkedAt: "2026-09-29",
    tags: ["restaurant", "fine dining", "african food"],
  },
  {
    slug: "cactus-restaurant-lagos",
    guideSlug: "lagos",
    name: "Cactus Restaurant",
    kind: "restaurant",
    area: "Victoria Island",
    address: "20/24 Ozumba Mbadiwe Avenue, Victoria Island, Lagos 106104, Lagos",
    summary: "Waterfront restaurant with breakfast, Nigerian and international dishes.",
    cost: "Many meals fall around ₦8,500–₦25,000; premium meat/seafood can be much higher",
    costNote: "Menu prices vary by item and can change quickly.",
    hours: "Current listing: from morning until late evening.",
    phone: "+234 802 777 7666",
    mapQuery: "Cactus Restaurant Lagos",
    source: { label: "Recent menu guide", href: "https://wakaabuja.com/cactus-restaurant-lagos/" },
    checkedAt: "2026-09-29",
    tags: ["restaurant", "waterfront", "family"],
  },
  {
    slug: "radisson-blu-anchorage-lagos",
    guideSlug: "lagos",
    name: "Radisson Blu Anchorage Hotel",
    kind: "hotel",
    area: "Victoria Island",
    address: "1A Ozumba Mbadiwe Avenue, Victoria Island, Lagos 101241, Lagos",
    summary: "Waterfront business/leisure hotel with quick access to central Island districts.",
    cost: "Live nightly rate — check the hotel for your exact dates",
    phone: "+234 708 061 0000",
    mapQuery: "Radisson Blu Anchorage Hotel Lagos",
    website: "https://www.radissonhotels.com/",
    checkedAt: "2026-09-29",
    tags: ["hotel", "waterfront", "victoria island"],
  },

  {
    slug: "millennium-park-abuja",
    guideSlug: "abuja",
    name: "Millennium Park",
    kind: "nature",
    area: "Maitama / Three Arms Zone",
    address: "5 Usuma Street, Three Arms Zone, Abuja 900103, FCT",
    summary: "Central lawns and walking space for a low-pressure break between busier Abuja stops.",
    cost: "Usually free",
    hours: "Current listing: roughly 08:00–18:30; verify for events or closures.",
    mapQuery: "Millennium Park Abuja",
    source: { label: "Visit Abuja", href: "https://www.visitabuja.org/see-and-do/" },
    checkedAt: "2026-09-29",
    tags: ["park", "free", "family"],
  },
  {
    slug: "abuja-national-mosque",
    guideSlug: "abuja",
    name: "Abuja National Mosque",
    kind: "landmark",
    area: "Central Business District",
    address: "1012 Sani Abacha Way, Central Business District, Abuja 900103, FCT",
    summary: "One of Abuja's defining landmarks; visitors should respect worship times and dress expectations.",
    cost: "Free",
    hours: "Access can be limited around prayer times and religious events.",
    phone: "+234 803 631 3301",
    mapQuery: "Abuja National Mosque",
    source: { label: "Visit Abuja", href: "https://www.visitabuja.org/see-and-do/" },
    checkedAt: "2026-09-29",
    tags: ["landmark", "architecture", "religion"],
  },
  {
    slug: "national-christian-centre-abuja",
    guideSlug: "abuja",
    name: "National Christian Centre",
    kind: "landmark",
    area: "Central Business District",
    address: "Opposite Central Bank of Nigeria, Central Business District, Abuja 900211, FCT",
    summary: "A major national church and architectural landmark near the city centre.",
    cost: "Free",
    hours: "Visitor access can change around services and events.",
    phone: "+234 802 402 3348",
    mapQuery: "National Christian Centre Abuja",
    source: { label: "Visit Abuja", href: "https://www.visitabuja.org/see-and-do/" },
    checkedAt: "2026-09-29",
    tags: ["landmark", "architecture", "religion"],
  },
  {
    slug: "blucabana-abuja",
    guideSlug: "abuja",
    name: "BluCabana Restaurant & Cafe",
    kind: "restaurant",
    area: "Mabushi",
    address: "1322 Shehu Yar'Adua Way, Mabushi, Abuja 900108, FCT",
    summary: "Large restaurant/cafe with Lebanese, Nigerian and international options.",
    cost: "Many sandwiches, grills and mains are about ₦7,000–₦25,000; premium dishes can reach ₦49,000+",
    costNote: "Official menu prices checked September 2026; VAT, entertainment and service charges may be extra.",
    hours: "Official site lists 09:00–22:30 Monday–Thursday and later closing Friday–Sunday.",
    phone: "+234 810 090 0000",
    website: "https://blucabana.com/",
    mapQuery: "BluCabana Abuja Mabushi",
    source: { label: "Official menu", href: "https://blucabana.com/menu/" },
    checkedAt: "2026-09-29",
    tags: ["restaurant", "international", "family"],
  },
  {
    slug: "abuja-continental-hotel",
    guideSlug: "abuja",
    name: "Abuja Continental Hotel",
    kind: "hotel",
    area: "Wuse",
    address: "1 Ladi Kwali Street, Zone 4, Wuse, Abuja 900001, FCT",
    summary: "Large central hotel useful for visitors who want quick access to Wuse and the Central Area.",
    cost: "Live nightly rate — check direct for your dates",
    phone: "+234 209 461 2000",
    mapQuery: "Abuja Continental Hotel",
    checkedAt: "2026-09-29",
    tags: ["hotel", "wuse", "central"],
  },

  {
    slug: "national-museum-benin-city",
    guideSlug: "benin-city",
    name: "Benin City National Museum",
    kind: "attraction",
    area: "Ring Road / King's Square",
    address: "King's Square, Ring Road, Benin City, Edo State",
    summary: "A compact starting point for Benin history, royal art traditions and wider Nigerian collections.",
    cost: "Verify current museum admission",
    mapQuery: "National Museum Benin City Ring Road",
    source: { label: "Edo State tourism overview", href: "https://edostate.gov.ng/your-tourist-destinations-in-edo-state-this-easter-holiday/" },
    checkedAt: "2026-09-29",
    tags: ["museum", "history", "culture"],
  },
  {
    slug: "igun-street",
    guideSlug: "benin-city",
    name: "Igun Street",
    kind: "attraction",
    area: "Central Benin City",
    address: "Igun Street, off Sakponba Road, Benin City, Edo State",
    summary: "The historic home of Benin bronze-casting guilds and working craft studios.",
    cost: "Street access is free; purchases and workshop arrangements vary",
    mapQuery: "Igun Street Benin City",
    source: { label: "Edo State tourism overview", href: "https://edostate.gov.ng/your-tourist-destinations-in-edo-state-this-easter-holiday/" },
    checkedAt: "2026-09-29",
    tags: ["art", "craft", "heritage"],
  },
  {
    slug: "naira-grill-benin",
    guideSlug: "benin-city",
    name: "Naira Grill",
    kind: "restaurant",
    area: "Country Home / Oka",
    address: "36 Country Home Road, Oka, Benin City 300251, Edo State",
    summary: "Casual grill spot known for barbecue, chicken, shawarma, smoothies and relaxed dining.",
    cost: "Recent diners commonly report about ₦10,000–₦20,000 per person",
    costNote: "Review-based 2026 estimate rather than a fixed menu quote.",
    phone: "+234 915 527 9412",
    mapQuery: "Naira Grill Benin City",
    source: { label: "Recent price/review listing", href: "https://restaurantguru.com/Naira-Grill-Benin-City" },
    checkedAt: "2026-09-29",
    tags: ["restaurant", "grill", "casual"],
  },
  {
    slug: "seven-restaurant-benin",
    guideSlug: "benin-city",
    name: "Seven Restaurant Benin",
    kind: "restaurant",
    area: "Ugbor",
    address: "36A 1st Ugbor Road, Oka, Benin City 300102, Edo State",
    summary: "Modern restaurant with international dishes and rooftop-style dining.",
    cost: "Recent reported spend varies widely; budget roughly ₦16,000+ per person",
    costNote: "Recent diner reports vary substantially by order. Confirm menu before visiting.",
    phone: "+234 905 137 0407",
    mapQuery: "Seven Restaurant Benin",
    source: { label: "Recent price/review listing", href: "https://restaurantguru.com/Seven-Restaurant-Benin-Benin-City" },
    checkedAt: "2026-09-29",
    tags: ["restaurant", "rooftop", "dinner"],
  },

  {
    slug: "marina-resort-calabar",
    guideSlug: "calabar",
    name: "Marina Resort",
    kind: "attraction",
    area: "Duke Town",
    address: "Marina Resort, Duke Town, Calabar 540281, Cross River State",
    summary: "Waterfront recreation complex and useful base for several Calabar heritage attractions.",
    cost: "Entry/activity costs vary — confirm what is currently operating",
    phone: "+234 705 299 1489",
    mapQuery: "Marina Resort Calabar",
    source: { label: "Cross River tourism update", href: "https://news.crossriverstate.gov.ng/two-years-of-purposeful-leadership-and-shared-progress-a-state-broadcast-by-his-excellency-the-governor-of-cross-river-state-on-the-occasion-of-his-second-year-in-office-may-29-2025/" },
    checkedAt: "2026-09-29",
    tags: ["waterfront", "family", "leisure"],
  },
  {
    slug: "slave-history-museum-calabar",
    guideSlug: "calabar",
    name: "Slave History Museum",
    kind: "attraction",
    area: "Marina",
    address: "Moor Road, Marina Resort, Calabar 540261, Cross River State",
    summary: "History museum focused on Calabar and the transatlantic slave trade.",
    cost: "Verify current museum admission",
    mapQuery: "Slave History Museum Calabar",
    checkedAt: "2026-09-29",
    tags: ["museum", "history", "heritage"],
  },
  {
    slug: "e3-restaurant-calabar",
    guideSlug: "calabar",
    name: "E3 Restaurant",
    kind: "restaurant",
    area: "Calabar Road",
    address: "12 Calabar Road, Calabar, Cross River State",
    summary: "Nigerian and continental restaurant with a broad casual-dining menu.",
    cost: "Selected dishes currently around ₦3,500–₦7,000; Sunday buffet has been reported around ₦13,000 per person",
    costNote: "Menu and buffet pricing can change; check directly before relying on the figure.",
    hours: "Official site lists 09:00–20:00 weekdays and 12:00–21:00 weekends.",
    phone: "+234 812 280 4442",
    website: "https://e3restaurant.com/",
    mapQuery: "E3 Restaurant Calabar",
    source: { label: "Official restaurant menu/site", href: "https://e3restaurant.com/" },
    checkedAt: "2026-09-29",
    tags: ["restaurant", "nigerian food", "casual"],
  },

  {
    slug: "port-harcourt-pleasure-park",
    guideSlug: "port-harcourt",
    name: "Port Harcourt Pleasure Park",
    kind: "attraction",
    area: "City Centre",
    address: "Between Army Bori Camp and Air Force Base Junction, Port Harcourt, Rivers State",
    summary: "Large city recreation park with open space, family activities and evening leisure.",
    cost: "Activity charges vary — confirm current prices on arrival",
    hours: "Current listing shows long daily opening hours; verify event-day access.",
    phone: "+234 906 002 2295",
    mapQuery: "Port Harcourt Pleasure Park",
    checkedAt: "2026-09-29",
    tags: ["park", "family", "leisure"],
  },
  {
    slug: "landmark-port-harcourt-resort",
    guideSlug: "port-harcourt",
    name: "Landmark Port Harcourt Resort",
    kind: "hotel",
    area: "Old Port Harcourt Township",
    address: "Tourist Beach Road, Old Port Harcourt Township, Port Harcourt 500101, Rivers State",
    summary: "Waterfront resort project on the historic Tourist Beach axis.",
    cost: "Live room/activity rates — check direct",
    phone: "+234 805 055 7000",
    website: "https://www.landmarkafrica.com/",
    mapQuery: "Landmark Port Harcourt Resort",
    source: { label: "Landmark Africa", href: "https://www.landmarkafrica.com/contact" },
    checkedAt: "2026-09-29",
    tags: ["hotel", "waterfront", "resort"],
  },
  {
    slug: "bole-king-port-harcourt",
    guideSlug: "port-harcourt",
    name: "Bole King",
    kind: "restaurant",
    area: "Elekahia",
    address: "2 Circular Road, Elekahia Housing Estate, Port Harcourt 500101, Rivers State",
    summary: "A local-food stop built around Port Harcourt's well-known bole and grilled-fish culture.",
    cost: "Menu price varies by fish size and sides — confirm current total before ordering",
    mapQuery: "Bole King Port Harcourt Elekahia",
    checkedAt: "2026-09-29",
    tags: ["restaurant", "local food", "bole"],
  },

  {
    slug: "gidan-makama-museum",
    guideSlug: "kano",
    name: "Gidan Makama Museum",
    kind: "attraction",
    area: "Old City",
    address: "Emir Palace Road, Wudilawa, Kano 700103, Kano State",
    summary: "Historic Hausa architecture and collections that give context to Kano before exploring the old city.",
    cost: "Verify current museum admission",
    hours: "Current listing: daytime opening.",
    phone: "+234 816 373 9092",
    mapQuery: "Gidan Makama Museum Kano",
    checkedAt: "2026-09-29",
    tags: ["museum", "history", "architecture"],
  },
  {
    slug: "dala-hill",
    guideSlug: "kano",
    name: "Dala Hill",
    kind: "landmark",
    area: "Kano City",
    address: "Dala, Kano City, Kano 700212, Kano State",
    summary: "Historic hill closely tied to the early settlement story of Kano.",
    cost: "Generally open-access; use local guidance and confirm conditions",
    mapQuery: "Dala Hill Kano",
    checkedAt: "2026-09-29",
    tags: ["history", "viewpoint", "outdoors"],
  },
  {
    slug: "jalsa-kano",
    guideSlug: "kano",
    name: "Jalsa",
    kind: "restaurant",
    area: "Bompai",
    address: "3 Bompai Road, Kano 700222, Kano State",
    summary: "Casual Indian/Nigerian restaurant with pizza, grills, rice dishes and quick meals.",
    cost: "Many full meals are about ₦4,000–₦8,000; larger platters and extras cost more",
    costNote: "Official menu checked September 2026.",
    phone: "+234 818 011 1777",
    website: "https://cilantrorestaurants.com/",
    mapQuery: "Jalsa Kano Bompai Road",
    source: { label: "Official Kano menu", href: "https://cilantrorestaurants.com/menu/kano/jalsa/" },
    checkedAt: "2026-09-29",
    tags: ["restaurant", "indian", "casual"],
  },

  {
    slug: "jos-museum-and-zoo",
    guideSlug: "jos",
    name: "Jos Museum and Zoo",
    kind: "attraction",
    area: "Museum Street",
    address: "1 Museum Street, Jos 930105, Plateau State",
    summary: "A long-established museum complex useful for Plateau and Nigerian cultural context.",
    cost: "Verify current admission",
    hours: "Current listing: roughly 10:00–18:00 daily.",
    phone: "+234 816 061 4742",
    mapQuery: "Jos Museum and Zoo",
    checkedAt: "2026-09-29",
    tags: ["museum", "history", "family"],
  },
  {
    slug: "jos-wildlife-park",
    guideSlug: "jos",
    name: "Jos Wildlife Park",
    kind: "nature",
    area: "Tudun Wada",
    address: "41 Tudun Wada Road, Jos 930105, Plateau State",
    summary: "A large green-space and wildlife stop on the edge of Jos.",
    cost: "Verify current park admission",
    hours: "Current listing: daytime opening; Sunday hours may differ.",
    mapQuery: "Jos Wildlife Park",
    checkedAt: "2026-09-29",
    tags: ["wildlife", "park", "family"],
  },
  {
    slug: "ask-me-restaurant-jos",
    guideSlug: "jos",
    name: "Ask Me Restaurant Jos",
    kind: "restaurant",
    area: "Ahmadu Bello Way",
    address: "48 Ahmadu Bello Way, Jos 930105, Plateau State",
    summary: "Straightforward local restaurant option near central Jos.",
    cost: "Current listing indicates many meals within roughly ₦1–₦10,000",
    phone: "+234 903 686 9736",
    mapQuery: "Ask Me Restaurant Jos",
    checkedAt: "2026-09-29",
    tags: ["restaurant", "budget", "local food"],
  },
  {
    slug: "barcardi-restaurant-jos",
    guideSlug: "jos",
    name: "Barcardi Restaurant & Cafe",
    kind: "restaurant",
    area: "GRA",
    address: "11 Dandaura Road, off Wase Road, GRA, Jos, Plateau State",
    summary: "Cafe/restaurant option in GRA for a more polished sit-down meal.",
    cost: "Current listing indicates roughly ₦20,000–₦30,000 per person",
    phone: "+234 817 488 3779",
    mapQuery: "Barcardi Restaurant Cafe Jos",
    checkedAt: "2026-09-29",
    tags: ["restaurant", "cafe", "gra"],
  },

  {
    slug: "ngwo-pine-forest",
    guideSlug: "enugu",
    name: "Ngwo Pine Forest",
    kind: "nature",
    area: "Ngwo",
    address: "Ngwo-Asaa 401107, Enugu State",
    summary: "Pine forest and cave/waterfall area close enough to Enugu for a dedicated half-day outing.",
    cost: "Local access/guide charges vary — confirm before departure",
    mapQuery: "Ngwo Pine Forest Enugu",
    checkedAt: "2026-09-29",
    tags: ["forest", "hiking", "nature"],
  },
  {
    slug: "landmark-nike-lake-resort",
    guideSlug: "enugu",
    name: "Landmark Nike Lake Resort Hotel",
    kind: "hotel",
    area: "Nike",
    address: "Nike Hotel Drive, Enugu 400103, Enugu State",
    summary: "Lakeside resort and hotel that works as both accommodation and a calmer leisure stop.",
    cost: "Live room and activity rates — check direct",
    phone: "+234 805 055 7000",
    website: "https://www.landmarkafrica.com/",
    mapQuery: "Landmark Nike Lake Resort Enugu",
    source: { label: "Landmark Africa", href: "https://www.landmarkafrica.com/contact" },
    checkedAt: "2026-09-29",
    tags: ["hotel", "lake", "resort"],
  },
  {
    slug: "ntachi-osa-new-haven",
    guideSlug: "enugu",
    name: "Ntachi-Osa",
    kind: "restaurant",
    area: "New Haven",
    address: "97 Chime Avenue, Mbanefo Street, New Haven, Enugu 400102, Enugu State",
    summary: "Popular Enugu restaurant focused on Nigerian and Igbo meals.",
    cost: "Official site currently advertises food from about ₦500 to ₦10,000",
    costNote: "Specific dishes and branch pricing can change.",
    phone: "+234 803 493 6435",
    website: "https://www.ntachiosa.ng/",
    mapQuery: "Ntachi Osa New Haven Enugu",
    source: { label: "Official restaurant site", href: "https://www.ntachiosa.ng/" },
    checkedAt: "2026-09-29",
    tags: ["restaurant", "igbo food", "budget"],
  },
  {
    slug: "awhum-waterfall",
    guideSlug: "enugu",
    name: "Awhum Waterfall & Cave",
    kind: "nature",
    area: "Awhum / Udi",
    address: "Awhum, Udi Local Government Area, Enugu State",
    summary: "A day-trip waterfall and cave destination outside central Enugu.",
    cost: "Local access/guide charges vary — verify before travel",
    mapQuery: "Awhum Waterfall Enugu",
    checkedAt: "2026-09-29",
    tags: ["waterfall", "nature", "day trip"],
  },

  {
    slug: "obudu-mountain-resort-main",
    guideSlug: "obudu-mountain-resort",
    name: "Obudu Mountain Resort",
    kind: "hotel",
    area: "Obudu Plateau / Obanliku",
    address: "Obudu Plateau, Obanliku Local Government Area, Cross River State",
    summary: "Highland resort complex undergoing major rehabilitation and concession-led redevelopment in 2026.",
    cost: "Confirm current room, access and activity prices directly",
    costNote: "Do not rely on old cable-car or accommodation prices while rehabilitation is ongoing.",
    mapQuery: "Obudu Mountain Resort Cross River",
    source: { label: "Cross River 2026 rehabilitation update", href: "https://news2.crossriverstate.gov.ng/obudu-ranch-concession-will-transform-obanliku-create-jobs-boost-tourism-gov-otu/" },
    checkedAt: "2026-09-29",
    tags: ["mountain", "resort", "nature"],
  },
  {
    slug: "becheve-nature-reserve",
    guideSlug: "obudu-mountain-resort",
    name: "Becheve Nature Reserve",
    kind: "nature",
    area: "Obudu Plateau",
    address: "Obudu Plateau, Obanliku Local Government Area, Cross River State",
    summary: "Nature-focused forest area associated with the Obudu highlands.",
    cost: "Confirm guided-access arrangements locally",
    mapQuery: "Becheve Nature Reserve Obudu",
    checkedAt: "2026-09-29",
    tags: ["forest", "nature", "guided walk"],
  },
  {
    slug: "ulanga-mountain-obudu",
    guideSlug: "obudu-mountain-resort",
    name: "Ulanga Mountain Views",
    kind: "nature",
    area: "Obudu",
    address: "Obudu Local Government Area, Cross River State",
    summary: "Scenic mountain landscape highlighted by the Obudu local-government tourism guide.",
    cost: "Local guide/transport cost varies",
    mapQuery: "Ulanga Mountain Obudu Cross River",
    source: { label: "Obudu LGA tourism", href: "https://obudu.crossriverstate.gov.ng/tourism" },
    checkedAt: "2026-09-29",
    tags: ["mountain", "viewpoint", "nature"],
  },

  {
    slug: "yankari-game-reserve-main",
    guideSlug: "yankari-game-reserve",
    name: "Yankari Game Reserve",
    kind: "nature",
    area: "Alkaleri LGA",
    address: "Yankari Game Reserve, Alkaleri Local Government Area, Bauchi State",
    summary: "Large wildlife reserve best planned as an overnight or multi-day trip rather than a quick stop.",
    cost: "Confirm current entrance, vehicle and guided-drive charges directly",
    mapQuery: "Yankari Game Reserve Bauchi",
    source: { label: "Bauchi State tourism", href: "https://www.bauchistate.gov.ng/tourism/" },
    checkedAt: "2026-09-29",
    tags: ["wildlife", "safari", "nature"],
  },
  {
    slug: "wikki-warm-spring",
    guideSlug: "yankari-game-reserve",
    name: "Wikki Warm Spring",
    kind: "nature",
    area: "Inside Yankari Game Reserve",
    address: "Yankari Game Reserve, Alkaleri LGA, Bauchi State",
    summary: "Warm natural spring and one of Yankari's signature visitor experiences.",
    cost: "Usually part of the reserve visit; confirm any separate activity/access charge",
    mapQuery: "Wikki Warm Spring Yankari",
    checkedAt: "2026-09-29",
    tags: ["spring", "swimming", "nature"],
  },
  {
    slug: "marshall-caves-yankari",
    guideSlug: "yankari-game-reserve",
    name: "Marshall Caves",
    kind: "attraction",
    area: "Inside Yankari Game Reserve",
    address: "Yankari Game Reserve, Alkaleri LGA, Bauchi State",
    summary: "Historic cave site within the wider Yankari reserve circuit.",
    cost: "Confirm guided-access arrangements with the reserve",
    mapQuery: "Marshall Caves Yankari Game Reserve",
    checkedAt: "2026-09-29",
    tags: ["history", "caves", "guided"],
  },

  {
    slug: "badagry-heritage-district",
    guideSlug: "weekend-trips-from-lagos",
    name: "Badagry Heritage District",
    kind: "attraction",
    area: "Badagry",
    address: "Badagry, Lagos State",
    summary: "A history-focused weekend or day trip built around museums, heritage sites and the old coastal town.",
    cost: "Museum/site charges vary — confirm each stop",
    mapQuery: "Badagry Heritage Museum Lagos",
    checkedAt: "2026-09-29",
    tags: ["history", "heritage", "day trip"],
  },
  {
    slug: "olumo-rock",
    guideSlug: "weekend-trips-from-lagos",
    name: "Olumo Rock",
    kind: "nature",
    area: "Abeokuta",
    address: "Ikija Road, Ikija, Abeokuta, Ogun State",
    summary: "Major Abeokuta landmark that can anchor a one-day or overnight road trip from Lagos.",
    cost: "Verify current entrance and guide charges",
    mapQuery: "Olumo Rock Abeokuta",
    checkedAt: "2026-09-29",
    tags: ["rock", "history", "viewpoint"],
  },
  {
    slug: "mapo-hall-ibadan",
    guideSlug: "weekend-trips-from-lagos",
    name: "Mapo Hall",
    kind: "landmark",
    area: "Ibadan",
    address: "Mapo Hill, Ibadan, Oyo State",
    summary: "Historic civic landmark that can be paired with markets, food and other central Ibadan stops.",
    cost: "Exterior viewing is free; confirm access for interior/event use",
    mapQuery: "Mapo Hall Ibadan",
    checkedAt: "2026-09-29",
    tags: ["architecture", "history", "city break"],
  },
  {
    slug: "agodi-gardens-ibadan",
    guideSlug: "ibadan",
    name: "Agodi Gardens",
    kind: "nature",
    area: "Mokola / Parliament Road",
    address: "Parliament Road, Mokola Hill, Ibadan, Oyo State",
    summary: "A central leisure garden that works well as a relaxed break between heritage and food stops.",
    cost: "Verify current entrance and activity charges before visiting",
    mapQuery: "Agodi Gardens Ibadan",
    source: { label: "Oyo State tourism overview", href: "https://oyostate.gov.ng/about-oyo-state/" },
    checkedAt: "2026-09-29",
    tags: ["garden", "family", "outdoors"],
  },
  {
    slug: "bowers-tower-ibadan",
    guideSlug: "ibadan",
    name: "Bower's Tower",
    kind: "landmark",
    area: "Oke-Are",
    address: "Oke-Are, Ibadan, Oyo State",
    summary: "Historic hilltop tower with a broad panorama over Ibadan.",
    cost: "Verify current entrance and access arrangements locally",
    mapQuery: "Bowers Tower Ibadan",
    source: { label: "Oyo State tourism investment guide", href: "https://tourism.oyostate.gov.ng/wp-content/uploads/2025/07/NEW-DEAL-BOOK-ITSOYOSTATE-2025.pdf" },
    checkedAt: "2026-09-29",
    tags: ["viewpoint", "history", "landmark"],
  },
  {
    slug: "national-museum-unity-ibadan",
    guideSlug: "ibadan",
    name: "National Museum of Unity",
    kind: "attraction",
    area: "Aleshinloye",
    address: "Aleshinloye, Ibadan, Oyo State",
    summary: "Museum stop for Nigerian history, archaeology and material culture.",
    cost: "Verify current admission and opening arrangements before visiting",
    mapQuery: "National Museum of Unity Ibadan",
    source: { label: "Oyo State tourism investment guide", href: "https://oysipa.oyostate.gov.ng/admin/uploads/INVEST-IN-TOURISM.pdf" },
    checkedAt: "2026-09-29",
    tags: ["museum", "history", "indoor"],
  },

  {
    slug: "itoku-adire-market",
    guideSlug: "abeokuta",
    name: "Itoku Adire Market",
    kind: "shopping",
    area: "Itoku",
    address: "Itoku, Abeokuta, Ogun State",
    summary: "A practical stop for adire textiles, craft shopping and a closer look at Abeokuta's textile tradition.",
    cost: "Market browsing is free; textile prices vary by fabric, design and seller",
    mapQuery: "Itoku Adire Market Abeokuta",
    checkedAt: "2026-09-29",
    tags: ["adire", "shopping", "craft"],
  },
  {
    slug: "alake-palace-abeokuta",
    guideSlug: "abeokuta",
    name: "Alake's Palace",
    kind: "landmark",
    area: "Ake",
    address: "Ake, Abeokuta, Ogun State",
    summary: "The royal palace of the Alake of Egbaland and an important part of Abeokuta's living heritage.",
    cost: "Public-area access may be free; confirm visitor or guided access before arrival",
    mapQuery: "Alake Palace Abeokuta",
    checkedAt: "2026-09-29",
    tags: ["palace", "heritage", "culture"],
  },
  {
    slug: "centenary-hall-abeokuta",
    guideSlug: "abeokuta",
    name: "Centenary Hall",
    kind: "landmark",
    area: "Ake",
    address: "Ake, Abeokuta, Ogun State",
    summary: "Historic civic landmark that fits naturally into a heritage walk around central Abeokuta.",
    cost: "Exterior viewing is free; confirm interior or event access locally",
    mapQuery: "Centenary Hall Abeokuta",
    checkedAt: "2026-09-29",
    tags: ["architecture", "history", "landmark"],
  },

  {
    slug: "osun-osogbo-sacred-grove",
    guideSlug: "osogbo",
    name: "Osun-Osogbo Sacred Grove",
    kind: "nature",
    area: "Osogbo",
    address: "Osun-Osogbo Sacred Grove, Osogbo, Osun State",
    summary: "UNESCO-listed sacred forest and cultural landscape associated with the Osun river and annual festival.",
    cost: "Verify current admission, guide and festival-period arrangements before visiting",
    mapQuery: "Osun Osogbo Sacred Grove",
    source: { label: "Osun State tourist centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    checkedAt: "2026-09-29",
    tags: ["unesco", "culture", "sacred grove"],
  },
  {
    slug: "nike-art-centre-osogbo",
    guideSlug: "osogbo",
    name: "Nike Art Centre Osogbo",
    kind: "attraction",
    area: "Old Ede Road",
    address: "Old Ede Road, Osogbo, Osun State",
    summary: "Art and cultural centre connected to Osogbo's long tradition of textile, painting and craft practice.",
    cost: "Confirm current visitor, workshop and event charges directly",
    mapQuery: "Nike Art Centre Osogbo",
    source: { label: "Osun State tourist centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    checkedAt: "2026-09-29",
    tags: ["art", "textiles", "culture"],
  },
  {
    slug: "ataoja-palace-osogbo",
    guideSlug: "osogbo",
    name: "Ataoja Palace",
    kind: "landmark",
    area: "Oja Oba",
    address: "Oja Oba, Osogbo, Osun State",
    summary: "Royal institution closely connected to Osogbo's history and the annual Osun-Osogbo festival.",
    cost: "Confirm visitor access locally; ceremonies can affect availability",
    mapQuery: "Ataoja Palace Osogbo",
    checkedAt: "2026-09-29",
    tags: ["palace", "heritage", "festival"],
  },

  {
    slug: "ooni-palace-ile-ife",
    guideSlug: "ile-ife",
    name: "Ooni of Ife Palace",
    kind: "landmark",
    area: "Enuwa",
    address: "Enuwa Square, Ile-Ife, Osun State",
    summary: "Living royal palace at the centre of Ile-Ife's cultural and historical identity.",
    cost: "Confirm current visitor and guided-access arrangements locally",
    mapQuery: "Ooni of Ife Palace",
    source: { label: "Osun State tourist centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    checkedAt: "2026-09-29",
    tags: ["palace", "yoruba history", "heritage"],
  },
  {
    slug: "moremi-statue-ile-ife",
    guideSlug: "ile-ife",
    name: "Moremi Statue of Liberty",
    kind: "landmark",
    area: "Ile-Ife",
    address: "Ile-Ife, Osun State",
    summary: "Large monument honouring Moremi Ajasoro and one of the city's most recognisable modern heritage landmarks.",
    cost: "Exterior viewing is generally free; confirm any managed-access charges locally",
    mapQuery: "Moremi Statue of Liberty Ile Ife",
    source: { label: "Osun State tourist centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    checkedAt: "2026-09-29",
    tags: ["monument", "history", "heritage"],
  },
  {
    slug: "national-museum-ile-ife",
    guideSlug: "ile-ife",
    name: "National Museum Ile-Ife",
    kind: "attraction",
    area: "Ile-Ife",
    address: "Ile-Ife, Osun State",
    summary: "Museum focused on the archaeological, artistic and cultural heritage of Ile-Ife and the wider Yoruba world.",
    cost: "Verify current admission and opening arrangements before visiting",
    mapQuery: "National Museum Ile Ife",
    source: { label: "Osun State tourist centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    checkedAt: "2026-09-29",
    tags: ["museum", "archaeology", "art"],
  },

  {
    slug: "idanre-hills",
    guideSlug: "ondo-state-highlights",
    name: "Idanre Hills",
    kind: "nature",
    area: "Idanre",
    address: "Idanre, Idanre Local Government Area, Ondo State",
    summary: "Historic hill settlement and major hiking destination with long climbs, old structures and wide views.",
    cost: "Verify current entrance, guide and parking charges before travel",
    mapQuery: "Idanre Hills Ondo State",
    source: { label: "Ondo State Government tourism", href: "https://ondostate.gov.ng/tourism" },
    checkedAt: "2026-09-29",
    tags: ["hiking", "heritage", "viewpoint"],
  },
  {
    slug: "owo-museum-antiquities",
    guideSlug: "ondo-state-highlights",
    name: "Owo Museum of Antiquities",
    kind: "attraction",
    area: "Owo",
    address: "Owo, Ondo State",
    summary: "Museum of royal regalia, archaeological material and historic artworks connected to the old Owo Kingdom.",
    cost: "Verify current admission and opening arrangements before visiting",
    mapQuery: "Owo Museum of Antiquities",
    source: { label: "Ondo State Government tourism", href: "https://ondostate.gov.ng/tourism" },
    checkedAt: "2026-09-29",
    tags: ["museum", "royal history", "culture"],
  },
  {
    slug: "akure-forest-reserve",
    guideSlug: "ondo-state-highlights",
    name: "Akure Forest Reserve",
    kind: "nature",
    area: "Akure South",
    address: "Akure South Local Government Area, Ondo State",
    summary: "Forest environment highlighted by Ondo State for nature walks, birdwatching and ecological interest.",
    cost: "Confirm current access, guide and permit requirements before visiting",
    mapQuery: "Akure Forest Reserve Ondo State",
    source: { label: "Ondo State Government tourism", href: "https://ondostate.gov.ng/tourism" },
    checkedAt: "2026-09-29",
    tags: ["forest", "birdwatching", "nature"],
  },
  {
    slug: "ikogosi-warm-springs",
    guideSlug: "ekiti-nature-circuit",
    name: "Ikogosi Warm Springs",
    kind: "nature",
    area: "Ikogosi-Ekiti",
    address: "Ikogosi-Ekiti, Ekiti West Local Government Area, Ekiti State",
    summary: "Natural warm and cold springs that flow separately before meeting at a well-known confluence.",
    cost: "Verify current entrance, pool and resort charges before travel",
    mapQuery: "Ikogosi Warm Springs Ekiti",
    source: { label: "Ekiti State tourism", href: "https://www.ekitistate.gov.ng/about-ekiti/tourism" },
    checkedAt: "2026-09-29",
    tags: ["springs", "nature", "resort"],
  },
  {
    slug: "arinta-waterfalls",
    guideSlug: "ekiti-nature-circuit",
    name: "Arinta Waterfalls",
    kind: "nature",
    area: "Ipole-Iloro",
    address: "Ipole-Iloro, Ekiti West Local Government Area, Ekiti State",
    summary: "Waterfall attraction listed by Ekiti State among its major nature and adventure sites.",
    cost: "Verify current entrance and local-guide charges before visiting",
    mapQuery: "Arinta Waterfalls Ipole Iloro Ekiti",
    source: { label: "Ekiti State Bureau of Tourism Development", href: "https://www.ekitistate.gov.ng/bureau-of-tourism-development" },
    checkedAt: "2026-09-29",
    tags: ["waterfall", "nature", "outdoors"],
  },
  {
    slug: "fajuyi-memorial-park",
    guideSlug: "ekiti-nature-circuit",
    name: "Fajuyi Memorial Park",
    kind: "landmark",
    area: "Ado-Ekiti",
    address: "Ado-Ekiti, Ekiti State",
    summary: "Memorial park in the state capital and a simple civic-history stop within a wider Ekiti trip.",
    cost: "Verify current access and any activity charges locally",
    mapQuery: "Fajuyi Memorial Park Ado Ekiti",
    source: { label: "Ekiti State tourism facts", href: "https://www.ekitistate.gov.ng/wp-content/uploads/2023/FACTS_FIGURES_2023.pdf" },
    checkedAt: "2026-09-29",
    tags: ["park", "history", "ado ekiti"],
  },

  {
    slug: "ilorin-central-mosque",
    guideSlug: "kwara-highlights",
    name: "Ilorin Central Mosque",
    kind: "landmark",
    area: "Central Ilorin",
    address: "Ilorin, Kwara State",
    summary: "Major religious and architectural landmark in central Ilorin.",
    cost: "No standard sightseeing fee; visit respectfully and confirm visitor access around prayers",
    mapQuery: "Ilorin Central Mosque",
    source: { label: "Kwara State Government tourism", href: "https://kwarastate.gov.ng/do-business/tourism/" },
    checkedAt: "2026-09-29",
    tags: ["mosque", "architecture", "culture"],
  },
  {
    slug: "kwara-flower-garden",
    guideSlug: "kwara-highlights",
    name: "Flower Garden",
    kind: "nature",
    area: "GRA Ilorin",
    address: "Adeloun Road, GRA, Ilorin, Kwara State",
    summary: "Government-recognised green space in Ilorin intended for recreation and leisure.",
    cost: "Verify current entrance, event and activity charges locally",
    mapQuery: "Flower Garden Ilorin Kwara",
    source: { label: "Kwara State Government tourism", href: "https://kwarastate.gov.ng/do-business/tourism/" },
    checkedAt: "2026-09-29",
    tags: ["garden", "leisure", "ilorin"],
  },
  {
    slug: "owu-falls-kwara",
    guideSlug: "kwara-highlights",
    name: "Owu Falls",
    kind: "nature",
    area: "Owa-Kajola / Ifelodun axis",
    address: "Owu Falls, Kwara State",
    summary: "Large waterfall and mountain-area attraction highlighted by the Kwara State Government.",
    cost: "Verify current entrance, guide and road-access conditions before departure",
    mapQuery: "Owu Waterfall Kwara State",
    source: { label: "Kwara State Government tourism", href: "https://kwarastate.gov.ng/do-business/tourism/" },
    checkedAt: "2026-09-29",
    tags: ["waterfall", "road trip", "nature"],
  },

  {
    slug: "ibom-unity-museum",
    guideSlug: "uyo",
    name: "Ibom Unity Museum",
    kind: "attraction",
    area: "Uyo",
    address: "Uyo, Akwa Ibom State",
    summary: "State museum included in Akwa Ibom's tourism-development circuit.",
    cost: "Verify current admission and opening arrangements before visiting",
    mapQuery: "Ibom Unity Museum Uyo",
    source: { label: "Akwa Ibom State tourism-site tour", href: "https://akwaibomstate.gov.ng/a-r-i-s-e-agenda-gov-umo-eno-tours-tourism-sites-vows-to-revamp-akwa-ibom-tourism-sector/" },
    checkedAt: "2026-09-29",
    tags: ["museum", "culture", "indoor"],
  },
  {
    slug: "akwa-ibom-state-centre-arts-culture",
    guideSlug: "uyo",
    name: "State Centre for Arts and Culture",
    kind: "attraction",
    area: "Olusegun Obasanjo Way",
    address: "Olusegun Obasanjo Way, Uyo, Akwa Ibom State",
    summary: "State arts and culture venue connected to performance, heritage and creative programming.",
    cost: "General access and event ticketing vary; check the current programme before visiting",
    mapQuery: "Akwa Ibom State Center for Arts and Culture Uyo",
    source: { label: "Akwa Ibom State tourism-site tour", href: "https://akwaibomstate.gov.ng/a-r-i-s-e-agenda-gov-umo-eno-tours-tourism-sites-vows-to-revamp-akwa-ibom-tourism-sector/" },
    checkedAt: "2026-09-29",
    tags: ["arts", "culture", "events"],
  },
  {
    slug: "ibom-tropicana",
    guideSlug: "uyo",
    name: "Ibom Tropicana Entertainment Centre",
    kind: "attraction",
    area: "Udo Udoma Avenue",
    address: "Udo Udoma Avenue, Uyo, Akwa Ibom State",
    summary: "Major entertainment complex in Uyo and a useful leisure option during a city stay.",
    cost: "Costs depend on the venue or activity; check current operators before visiting",
    mapQuery: "Ibom Tropicana Entertainment Centre Uyo",
    source: { label: "Akwa Ibom State tourism-site tour", href: "https://akwaibomstate.gov.ng/a-r-i-s-e-agenda-gov-umo-eno-tours-tourism-sites-vows-to-revamp-akwa-ibom-tourism-sector/" },
    checkedAt: "2026-09-29",
    tags: ["entertainment", "leisure", "uyo"],
  },

  {
    slug: "ogbunike-cave",
    guideSlug: "anambra-heritage-circuit",
    name: "Ogbunike Cave",
    kind: "nature",
    area: "Ogbunike",
    address: "Ifite, 433103, Ogbunike, Oyi Local Government Area, Anambra State",
    summary: "Major cave system with cultural importance and multiple natural tunnels.",
    cost: "Verify current entrance, guide and access conditions before visiting",
    mapQuery: "Ogbunike Caves Anambra",
    source: { label: "Anambra State places of interest", href: "https://anambrastate.gov.ng/directory/ogbunike-cave/" },
    checkedAt: "2026-09-29",
    tags: ["cave", "heritage", "nature"],
  },
  {
    slug: "agulu-lake",
    guideSlug: "anambra-heritage-circuit",
    name: "Agulu Lake",
    kind: "nature",
    area: "Agulu",
    address: "Agulu Lake, Anaocha Local Government Area, Anambra State",
    summary: "Large lake with strong cultural significance and a long-standing local wildlife tradition.",
    cost: "Verify current managed-access or activity charges locally before visiting",
    mapQuery: "Agulu Lake Anambra",
    source: { label: "Anambra State Government", href: "https://anambrastate.gov.ng/directory/agulu-lake/" },
    checkedAt: "2026-09-29",
    tags: ["lake", "nature", "culture"],
  },
  {
    slug: "owerre-ezukala-cave-waterfall",
    guideSlug: "anambra-heritage-circuit",
    name: "Owerre-Ezukala Cave & Waterfall",
    kind: "nature",
    area: "Owerre-Ezukala",
    address: "Owerre-Ezukala, Orumba South Local Government Area, Anambra State",
    summary: "Cave-and-waterfall attraction identified by the state as one of Anambra's major tourism-development sites.",
    cost: "Verify current entrance, guide and road-access conditions before visiting",
    mapQuery: "Owerre Ezukala Cave Waterfall Anambra",
    source: { label: "Anambra State tourism heritage sites", href: "https://anambrastate.gov.ng/soludo-administration-to-develop-five-major-tourism-heritage-sites-in-anambra/" },
    checkedAt: "2026-09-29",
    tags: ["waterfall", "cave", "road trip"],
  },

  {
    slug: "araromi-seaside",
    guideSlug: "araromi-beach",
    name: "Araromi Seaside",
    kind: "nature",
    area: "Ilaje",
    address: "Araromi Seaside, Ilaje Local Government Area, Ondo State",
    summary: "Atlantic-facing beach and coastline currently being promoted and developed by Ondo State as a tourism destination.",
    cost: "Verify current access, parking and event charges before travel",
    costNote: "Charges can differ during organised events or as new facilities open.",
    hours: "Daylight visits are the safest default unless an organised event publishes different hours.",
    mapQuery: "Araromi Beach Ondo State",
    source: { label: "Ondo State Government — Araromi coastal development", href: "https://ondostate.gov.ng/news-details?id=708515" },
    checkedAt: "2026-09-29",
    tags: ["beach", "coast", "day trip"],
  },
  {
    slug: "ebomi-lake-ipesi",
    guideSlug: "ebomi-lake",
    name: "Ebomi Lake",
    kind: "nature",
    area: "Ipesi-Akoko",
    address: "Ipesi-Akoko, Akoko South-East Local Government Area, Ondo State",
    summary: "Recognised Ondo State lake attraction with a quiet natural setting and local cultural significance.",
    cost: "Verify current community access, guide or development-related charges locally",
    hours: "Plan for daylight access and confirm local arrangements before travel.",
    mapQuery: "Ebomi Lake Ipesi Akoko Ondo State",
    source: { label: "Ondo State Ministry of Economic Planning — state profile", href: "https://mepb.on.gov.ng/meet-us/ondo-state-profile/" },
    checkedAt: "2026-09-29",
    tags: ["lake", "nature", "akoko"],
  },
  {
    slug: "igbokoda-waterfront-ondo",
    guideSlug: "igbokoda-waterfront",
    name: "Igbokoda Waterfront",
    kind: "nature",
    area: "Igbokoda",
    address: "Igbokoda, Ilaje Local Government Area, Ondo State",
    summary: "Riverine waterfront landscape associated with fishing, boat transport and mangrove exploration.",
    cost: "Waterfront access may be free; boat trips and guided activities are negotiated separately",
    costNote: "Confirm current operator prices, route and safety equipment before boarding.",
    hours: "Use daylight hours for independent visits; boat operators may set their own schedules.",
    mapQuery: "Igbokoda Waterfront Ondo State",
    source: { label: "Ondo State Government tourism", href: "https://ondostate.gov.ng/tourism" },
    checkedAt: "2026-09-29",
    tags: ["waterfront", "riverine", "fishing", "boats"],
  },
];

export function getExplorePlacesForGuide(guideSlug: string) {
  return explorePlaces.filter((place) => place.guideSlug === guideSlug);
}

export function googleMapsUrl(place: Pick<ExplorePlace, "name" | "address" | "mapQuery">) {
  const query = place.mapQuery || [place.name, place.address].filter(Boolean).join(" ");
  return "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(query);
}

export const explorePlaceKindLabel: Record<ExplorePlaceKind, string> = {
  attraction: "Attraction",
  nature: "Nature",
  restaurant: "Restaurant",
  hotel: "Stay",
  shopping: "Shopping",
  landmark: "Landmark",
};
