import type { ExplorePlace } from "@/lib/explore-places";

export const exploreGrowthPlacesWave8: ExplorePlace[] = [
  {
    slug: "erio-hills-ekiti",
    guideSlug: "ekiti-springs-waterfalls",
    name: "Erio Hills",
    kind: "nature",
    area: "Erio-Ekiti",
    address: "Erio-Ekiti, Ekiti State, Nigeria",
    summary: "Hill area identified in Ekiti's tourism corridor for religious and scenic tourism.",
    cost: "Confirm current access and pilgrimage-site arrangements locally",
    hours: "Daylight visits recommended; event access varies.",
    mapQuery: "Erio Ekiti hills",
    source: { label: "Ekiti State Government — Ikogosi tourism corridor", href: "https://www.ekitistate.gov.ng/archives/3943" },
    checkedAt: "2026-10-07",
    tags: ["hill", "pilgrimage", "nature", "Ekiti"]
  },
  {
    slug: "iron-of-liberty-lokoja",
    guideSlug: "lokoja",
    name: "Iron of Liberty",
    kind: "landmark",
    area: "Lokoja",
    address: "Lokoja, Kogi State, Nigeria",
    summary: "Historic freedom monument highlighted by Kogi State as a Lokoja heritage attraction.",
    cost: "Public landmark; no standard admission published",
    hours: "Visit in daylight.",
    mapQuery: "Iron of Liberty Lokoja",
    source: { label: "Kogi State Government — Tourism", href: "https://kogistate.gov.ng/kogi-state-where-rivers-kiss-the-sky/" },
    checkedAt: "2026-10-07",
    tags: ["history", "landmark", "Lokoja", "Kogi"]
  },
  {
    slug: "colonial-history-museum-aba",
    guideSlug: "abia-war-history",
    name: "National Museum of Colonial History, Aba",
    kind: "attraction",
    area: "Aba",
    address: "Aba, Abia State, Nigeria",
    summary: "NCMM-listed colonial-history museum in Aba, useful as a second-city extension to the Umuahia war-history route.",
    cost: "Confirm current museum admission",
    hours: "Confirm current opening hours before travel.",
    mapQuery: "National Museum Colonial History Aba",
    source: { label: "NCMM — Proposed National Monuments", href: "https://museum.ng/national-monuments-in-nigeria/proposed-national-monuments/" },
    checkedAt: "2026-10-07",
    tags: ["museum", "colonial history", "Aba", "Abia"]
  },
  {
    slug: "igbo-ukwu-archaeological-sites",
    guideSlug: "anambra-heritage",
    name: "Igbo-Ukwu Archaeological Sites",
    kind: "landmark",
    area: "Igbo-Ukwu",
    address: "Igbo-Ukwu, Aguata LGA, Anambra State, Nigeria",
    summary: "Archaeological heritage associated with sophisticated early Igbo metalwork and ritual culture.",
    cost: "Confirm current museum/site access before visiting",
    hours: "Confirm current visitor arrangements locally.",
    mapQuery: "Igbo Ukwu archaeological site Anambra",
    source: { label: "Anambra State Ministry of Tourism", href: "https://demos.anambrastate.gov.ng/anambra-state-ministry-of-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["archaeology", "Igbo heritage", "history", "Anambra"]
  },
  {
    slug: "chappal-waddi",
    guideSlug: "taraba-highlands",
    name: "Chappal Waddi",
    kind: "nature",
    area: "Gashaka-Gumti / Cameroon border highlands",
    address: "Chappal Waddi, Taraba State, Nigeria",
    summary: "Nigeria's highest mountain, highlighted by Taraba's heritage ministry as a major highland landmark.",
    cost: "Requires organised transport/guide planning; confirm current park access",
    hours: "Only attempt with appropriate daylight, weather and local guidance.",
    mapQuery: "Chappal Waddi Taraba Nigeria",
    source: { label: "Taraba State Ministry of Heritage & Ecotourism", href: "https://tarabatourism.org.ng/" },
    checkedAt: "2026-10-07",
    tags: ["mountain", "hiking", "adventure", "Taraba"]
  },
  {
    slug: "baro-empire-hills",
    guideSlug: "niger-state-nature",
    name: "Baro Empire Hills",
    kind: "nature",
    area: "Baro / Agaie",
    address: "Baro, Agaie LGA, Niger State, Nigeria",
    summary: "Historic hill landscape listed by Niger State among its tourism assets.",
    cost: "Confirm current local access before travelling",
    hours: "Daylight visit recommended.",
    mapQuery: "Baro Empire Hills Niger State",
    source: { label: "Niger State Investment Promotion Agency — Tourism", href: "https://nsipa.nigerstate.gov.ng/tourism/" },
    checkedAt: "2026-10-07",
    tags: ["hill", "history", "Baro", "Niger State"]
  },
  {
    slug: "ayikunnugba-waterfall-oke-ila",
    guideSlug: "osun-nature-culture",
    name: "Ayikunnugba Waterfall",
    kind: "nature",
    area: "Oke-Ila Orangun",
    address: "Oke-Ila Orangun, Ifedayo LGA, Osun State, Nigeria",
    summary: "Roughly 30-metre waterfall highlighted by Osun State's tourism board.",
    cost: "Confirm current local access and charges",
    hours: "Daylight visit recommended.",
    mapQuery: "Ayikunnugba Waterfall Oke Ila Osun",
    source: { label: "Osun State Government — Tourist Centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    checkedAt: "2026-10-07",
    tags: ["waterfall", "nature", "Oke-Ila", "Osun"]
  }
];
