import type { ExplorePlace } from "@/lib/explore-places";

export const exploreGrowthPlacesWave8: ExplorePlace[] = [
  {
    slug: "idanre-hills",
    guideSlug: "ondo-nature-heritage",
    name: "Idanre Hills",
    kind: "nature",
    area: "Idanre",
    address: "Idanre, Ondo State, Nigeria",
    summary: "Ondo State's flagship hill-and-heritage attraction with 682 steps, old settlement remains and panoramic views.",
    cost: "Confirm current admission and guide charges with Ondo tourism authorities",
    hours: "Visit in daylight; confirm current opening and guide arrangements before travel.",
    mapQuery: "Idanre Hills Ondo State",
    source: { label: "Ondo State Government — Tourism", href: "https://www.ondostate.gov.ng/tourism" },
    checkedAt: "2026-10-07",
    tags: ["hiking", "heritage", "viewpoint", "Ondo"]
  },
  {
    slug: "owo-museum-antiquities",
    guideSlug: "ondo-nature-heritage",
    name: "Owo Museum of Antiquities",
    kind: "attraction",
    area: "Owo",
    address: "Olowo's Palace area, Owo, Ondo State, Nigeria",
    summary: "Museum collection connected with the old Owo Kingdom, royal regalia, archaeology and Yoruba artworks.",
    cost: "Confirm current museum admission before visiting",
    hours: "Confirm current visitor hours with the museum.",
    phone: "07031533798",
    mapQuery: "National Museum Owo Ondo State",
    source: { label: "National Commission for Museums and Monuments — Owo Museum", href: "https://museum.ng/museums/" },
    checkedAt: "2026-10-07",
    tags: ["museum", "royal heritage", "Owo", "Ondo"]
  },
  {
    slug: "akure-forest-reserve",
    guideSlug: "ondo-nature-heritage",
    name: "Akure Forest Reserve",
    kind: "nature",
    area: "Akure South",
    address: "Akure Forest Reserve, Akure area, Ondo State, Nigeria",
    summary: "State-listed forest reserve for nature walks, bird watching and ecological visits.",
    cost: "Confirm current access and guide requirements before visiting",
    hours: "Daylight visit recommended; current formal visitor hours are not published.",
    mapQuery: "Akure Forest Reserve Ondo",
    source: { label: "Ondo State Government — Tourism", href: "https://www.ondostate.gov.ng/tourism" },
    checkedAt: "2026-10-07",
    tags: ["forest", "birding", "nature", "Akure"]
  },
  {
    slug: "ikogosi-warm-cold-springs",
    guideSlug: "ekiti-springs-waterfalls",
    name: "Ikogosi Warm & Cold Springs",
    kind: "nature",
    area: "Ikogosi-Ekiti",
    address: "Ikogosi-Ekiti, Ekiti West LGA, Ekiti State, Nigeria",
    summary: "Ekiti's best-known spring attraction where warm and cold water sources meet while retaining distinct temperatures.",
    cost: "Confirm current spring/resort admission and packages before travel",
    hours: "Confirm current visitor hours with the resort or Ekiti tourism authority.",
    mapQuery: "Ikogosi Warm Springs Ekiti",
    source: { label: "Ekiti State Government — Tourism", href: "https://www.ekitistate.gov.ng/about-ekiti/tourism" },
    checkedAt: "2026-10-07",
    tags: ["spring", "nature", "resort", "Ekiti"]
  },
  {
    slug: "ipole-iloro-waterfall",
    guideSlug: "ekiti-springs-waterfalls",
    name: "Ipole-Iloro Waterfall",
    kind: "nature",
    area: "Ipole-Iloro",
    address: "Ipole-Iloro, Ekiti State, Nigeria",
    summary: "Waterfall on the wider Ikogosi tourism corridor identified in Ekiti State tourism material.",
    cost: "Confirm current local access and any community charges",
    hours: "Visit in daylight and verify access before travel.",
    mapQuery: "Ipole Iloro Waterfall Ekiti",
    source: { label: "Ekiti State Government — Ikogosi tourism corridor", href: "https://www.ekitistate.gov.ng/archives/3943" },
    checkedAt: "2026-10-07",
    tags: ["waterfall", "nature", "Ekiti"]
  },
  {
    slug: "erio-hills-ekiti",
    guideSlug: "ekiti-springs-waterfalls",
    name: "Erio Hills",
    kind: "nature",
    area: "Erio-Ekiti",
    address: "Erio-Ekiti, Ekiti State, Nigeria",
    summary: "Hill area identified in Ekiti's tourism corridor for religious and scenic tourism.",
    cost: "Confirm current access and pilgrimage-site arrangements locally",
    hours: "Daylight visits recommended; event access varies.",
    mapQuery: "Erio Ekiti hills",
    source: { label: "Ekiti State Government — Ikogosi tourism corridor", href: "https://www.ekitistate.gov.ng/archives/3943" },
    checkedAt: "2026-10-07",
    tags: ["hill", "pilgrimage", "nature", "Ekiti"]
  },
  {
    slug: "mount-patti-lokoja",
    guideSlug: "lokoja",
    name: "Mount Patti",
    kind: "nature",
    area: "Lokoja",
    address: "Mount Patti, Lokoja, Kogi State, Nigeria",
    summary: "Hill above Lokoja with broad views toward the Niger-Benue confluence and colonial heritage sites.",
    cost: "Confirm current hill access or guide charges before visiting",
    hours: "Daylight visit recommended.",
    mapQuery: "Mount Patti Lokoja",
    source: { label: "Kogi State Government — Tourism", href: "https://kogistate.gov.ng/kogi-state-where-rivers-kiss-the-sky/" },
    checkedAt: "2026-10-07",
    tags: ["hill", "viewpoint", "Lokoja", "Kogi"]
  },
  {
    slug: "niger-benue-confluence-lokoja",
    guideSlug: "lokoja",
    name: "Niger-Benue Confluence",
    kind: "nature",
    area: "Lokoja riverfront",
    address: "Lokoja, Kogi State, Nigeria",
    summary: "The natural meeting point of the Rivers Niger and Benue and Lokoja's defining landscape.",
    cost: "Public viewpoints may be free; organised boat trips vary",
    hours: "Use safe established viewpoints and daylight for river activities.",
    mapQuery: "Niger Benue Confluence Lokoja",
    source: { label: "Kogi State Government — Tourism", href: "https://kogistate.gov.ng/kogi-state-where-rivers-kiss-the-sky/" },
    checkedAt: "2026-10-07",
    tags: ["river", "confluence", "Lokoja", "Kogi"]
  },
  {
    slug: "iron-of-liberty-lokoja",
    guideSlug: "lokoja",
    name: "Iron of Liberty",
    kind: "landmark",
    area: "Lokoja",
    address: "Lokoja, Kogi State, Nigeria",
    summary: "Historic freedom monument highlighted by Kogi State as a Lokoja heritage attraction.",
    cost: "Public landmark; no standard admission published",
    hours: "Visit in daylight.",
    mapQuery: "Iron of Liberty Lokoja",
    source: { label: "Kogi State Government — Tourism", href: "https://kogistate.gov.ng/kogi-state-where-rivers-kiss-the-sky/" },
    checkedAt: "2026-10-07",
    tags: ["history", "landmark", "Lokoja", "Kogi"]
  },
  {
    slug: "national-war-museum-umuahia",
    guideSlug: "abia-war-history",
    name: "National War Museum Umuahia",
    kind: "attraction",
    area: "Umuahia",
    address: "War Museum Road, Ebite-Amafor, Isingwu by Ugwunchara, Umuahia, Abia State, Nigeria",
    summary: "Nigeria's dedicated war museum preserving Civil War and traditional-warfare relics, military technology and peace-history material.",
    cost: "Confirm current NCMM admission before visiting",
    hours: "Confirm current museum opening hours.",
    phone: "08062627376",
    mapQuery: "National War Museum Umuahia",
    source: { label: "National Commission for Museums and Monuments", href: "https://museum.ng/museums/" },
    checkedAt: "2026-10-07",
    tags: ["museum", "civil war", "history", "Umuahia"]
  },
  {
    slug: "ojukwu-bunker-umuahia",
    guideSlug: "abia-war-history",
    name: "Ojukwu Bunker / Former Biafran State House",
    kind: "landmark",
    area: "Umuahia",
    address: "Umuahia, Abia State, Nigeria",
    summary: "Civil War-era bunker and former Biafran State House complex listed by NCMM among proposed national monuments.",
    cost: "Confirm current access with NCMM/local heritage authorities",
    hours: "Visitor access can vary; confirm before travel.",
    mapQuery: "Ojukwu Bunker Umuahia",
    source: { label: "NCMM — Proposed National Monuments", href: "https://museum.ng/national-monuments-in-nigeria/proposed-national-monuments/" },
    checkedAt: "2026-10-07",
    tags: ["civil war", "bunker", "history", "Umuahia"]
  },
  {
    slug: "colonial-history-museum-aba",
    guideSlug: "abia-war-history",
    name: "National Museum of Colonial History, Aba",
    kind: "attraction",
    area: "Aba",
    address: "Aba, Abia State, Nigeria",
    summary: "NCMM-listed colonial-history museum in Aba, useful as a second-city extension to the Umuahia war-history route.",
    cost: "Confirm current museum admission",
    hours: "Confirm current opening hours before travel.",
    mapQuery: "National Museum Colonial History Aba",
    source: { label: "NCMM — Proposed National Monuments", href: "https://museum.ng/national-monuments-in-nigeria/proposed-national-monuments/" },
    checkedAt: "2026-10-07",
    tags: ["museum", "colonial history", "Aba", "Abia"]
  },
  {
    slug: "ogbunike-caves",
    guideSlug: "anambra-heritage",
    name: "Ogbunike Caves",
    kind: "nature",
    area: "Ogbunike",
    address: "Ogbunike, Oyi LGA, Anambra State, Nigeria",
    summary: "Major Anambra cave system with strong cultural and community significance.",
    cost: "Confirm current community/site charges before visiting",
    hours: "Visit in daylight and confirm access/customary rules locally.",
    mapQuery: "Ogbunike Caves Anambra",
    source: { label: "Anambra State Ministry of Tourism", href: "https://demos.anambrastate.gov.ng/anambra-state-ministry-of-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["cave", "nature", "heritage", "Anambra"]
  },
  {
    slug: "agulu-lake",
    guideSlug: "anambra-heritage",
    name: "Agulu Lake",
    kind: "nature",
    area: "Agulu",
    address: "Agulu, Anaocha LGA, Anambra State, Nigeria",
    summary: "Large natural lake highlighted by Anambra's tourism ministry as one of the state's visitor assets.",
    cost: "Public-view access varies; confirm any organised activity charges locally",
    hours: "Daylight visits recommended.",
    mapQuery: "Agulu Lake Anambra",
    source: { label: "Anambra State Ministry of Tourism", href: "https://demos.anambrastate.gov.ng/anambra-state-ministry-of-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["lake", "nature", "Agulu", "Anambra"]
  },
  {
    slug: "igbo-ukwu-archaeological-sites",
    guideSlug: "anambra-heritage",
    name: "Igbo-Ukwu Archaeological Sites",
    kind: "landmark",
    area: "Igbo-Ukwu",
    address: "Igbo-Ukwu, Aguata LGA, Anambra State, Nigeria",
    summary: "Archaeological heritage associated with sophisticated early Igbo metalwork and ritual culture.",
    cost: "Confirm current museum/site access before visiting",
    hours: "Confirm current visitor arrangements locally.",
    mapQuery: "Igbo Ukwu archaeological site Anambra",
    source: { label: "Anambra State Ministry of Tourism", href: "https://demos.anambrastate.gov.ng/anambra-state-ministry-of-tourism/" },
    checkedAt: "2026-10-07",
    tags: ["archaeology", "Igbo heritage", "history", "Anambra"]
  },
  {
    slug: "kanta-museum-argungu",
    guideSlug: "kebbi-heritage",
    name: "Kanta Museum",
    kind: "attraction",
    area: "Argungu",
    address: "Argungu, Kebbi State, Nigeria",
    summary: "Heritage museum highlighted by Kebbi State as a major cultural attraction.",
    cost: "Confirm current museum admission before visiting",
    hours: "Confirm current opening hours locally.",
    mapQuery: "Kanta Museum Argungu Kebbi",
    source: { label: "Kebbi State Government — About Kebbi", href: "https://kebbistate.gov.ng/about-kebbi-state" },
    checkedAt: "2026-10-07",
    tags: ["museum", "Argungu", "heritage", "Kebbi"]
  },
  {
    slug: "hubbare-gwandu",
    guideSlug: "kebbi-heritage",
    name: "Hubbare — Tomb of Sheikh Abdullahi Dan Fodio",
    kind: "landmark",
    area: "Gwandu",
    address: "Gwandu, Kebbi State, Nigeria",
    summary: "Historic tomb associated with Sheikh Abdullahi Dan Fodio and the Gwandu Emirate.",
    cost: "No standard tourist fee published; confirm access locally",
    hours: "Religious/heritage access rules may apply.",
    mapQuery: "Sheikh Abdullahi Dan Fodio tomb Gwandu",
    source: { label: "Kebbi State Government — About Kebbi", href: "https://kebbistate.gov.ng/about-kebbi-state" },
    checkedAt: "2026-10-07",
    tags: ["religious heritage", "Gwandu", "history", "Kebbi"]
  },
  {
    slug: "girmache-shrine-zuru",
    guideSlug: "kebbi-heritage",
    name: "Girmache Shrine",
    kind: "landmark",
    area: "Zuru",
    address: "Zuru, Kebbi State, Nigeria",
    summary: "Cultural shrine in Zuru listed by Kebbi State among its important tourist attractions.",
    cost: "Confirm community access and any local charges before visiting",
    hours: "Access can depend on community and cultural rules.",
    mapQuery: "Girmache Shrine Zuru Kebbi",
    source: { label: "Kebbi State Government — About Kebbi", href: "https://kebbistate.gov.ng/about-kebbi-state" },
    checkedAt: "2026-10-07",
    tags: ["cultural heritage", "Zuru", "shrine", "Kebbi"]
  },
  {
    slug: "mambilla-plateau",
    guideSlug: "taraba-highlands",
    name: "Mambilla Plateau",
    kind: "nature",
    area: "Sardauna LGA",
    address: "Mambilla Plateau, Sardauna LGA, Taraba State, Nigeria",
    summary: "Highland region known for cool weather, dramatic scenery and tea-growing landscapes.",
    cost: "Landscape access varies; guides, transport and private sites are separately priced",
    hours: "Plan daylight travel and verify local road/weather conditions.",
    mapQuery: "Mambilla Plateau Taraba",
    source: { label: "Taraba State Ministry of Heritage & Ecotourism", href: "https://tarabatourism.org.ng/" },
    checkedAt: "2026-10-07",
    tags: ["highlands", "tea", "nature", "Taraba"]
  },
  {
    slug: "gashaka-gumti-national-park",
    guideSlug: "taraba-highlands",
    name: "Gashaka-Gumti National Park",
    kind: "nature",
    area: "Gashaka / Taraba-Adamawa",
    address: "Gashaka-Gumti National Park, Taraba and Adamawa States, Nigeria",
    summary: "Nigeria's largest national park and one of the country's most important protected wilderness areas.",
    cost: "Park entry, guides and activities vary — confirm with park authorities",
    hours: "Access depends on park operations, season and route.",
    mapQuery: "Gashaka Gumti National Park Nigeria",
    source: { label: "Taraba State Ministry of Heritage & Ecotourism", href: "https://tarabatourism.org.ng/" },
    checkedAt: "2026-10-07",
    tags: ["national park", "wildlife", "wilderness", "Taraba"]
  },
  {
    slug: "chappal-waddi",
    guideSlug: "taraba-highlands",
    name: "Chappal Waddi",
    kind: "nature",
    area: "Gashaka-Gumti / Cameroon border highlands",
    address: "Chappal Waddi, Taraba State, Nigeria",
    summary: "Nigeria's highest mountain, highlighted by Taraba's heritage ministry as a major highland landmark.",
    cost: "Requires organised transport/guide planning; confirm current park access",
    hours: "Only attempt with appropriate daylight, weather and local guidance.",
    mapQuery: "Chappal Waddi Taraba Nigeria",
    source: { label: "Taraba State Ministry of Heritage & Ecotourism", href: "https://tarabatourism.org.ng/" },
    checkedAt: "2026-10-07",
    tags: ["mountain", "hiking", "adventure", "Taraba"]
  },
  {
    slug: "gurara-falls",
    guideSlug: "niger-state-nature",
    name: "Gurara Falls",
    kind: "nature",
    area: "Gurara",
    address: "Gurara Falls, along Abuja-Minna road, Niger State, Nigeria",
    summary: "Major waterfall on the Abuja-Minna corridor and one of Niger State's flagship nature sites.",
    cost: "Confirm current site admission and local access charges",
    hours: "Daylight visit recommended; conditions vary by season.",
    mapQuery: "Gurara Falls Niger State",
    source: { label: "Niger State Investment Promotion Agency — Tourism", href: "https://nsipa.nigerstate.gov.ng/tourism/" },
    checkedAt: "2026-10-07",
    tags: ["waterfall", "nature", "Niger State"]
  },
  {
    slug: "zuma-rock-niger",
    guideSlug: "niger-state-nature",
    name: "Zuma Rock",
    kind: "nature",
    area: "Suleja axis",
    address: "Zuma Rock, Abuja-Kaduna/Lokoja highway axis, Niger State, Nigeria",
    summary: "Iconic monolith on the approach to Abuja and a major landmark tourism asset of Niger State.",
    cost: "Roadside/public views are free; organised activities vary",
    hours: "Daylight viewing recommended.",
    mapQuery: "Zuma Rock Niger State",
    source: { label: "Niger State Government — About", href: "https://nigerstate.gov.ng/about/" },
    checkedAt: "2026-10-07",
    tags: ["rock", "landmark", "Suleja", "Niger State"]
  },
  {
    slug: "baro-empire-hills",
    guideSlug: "niger-state-nature",
    name: "Baro Empire Hills",
    kind: "nature",
    area: "Baro / Agaie",
    address: "Baro, Agaie LGA, Niger State, Nigeria",
    summary: "Historic hill landscape listed by Niger State among its tourism assets.",
    cost: "Confirm current local access before travelling",
    hours: "Daylight visit recommended.",
    mapQuery: "Baro Empire Hills Niger State",
    source: { label: "Niger State Investment Promotion Agency — Tourism", href: "https://nsipa.nigerstate.gov.ng/tourism/" },
    checkedAt: "2026-10-07",
    tags: ["hill", "history", "Baro", "Niger State"]
  },
  {
    slug: "osun-osogbo-sacred-grove",
    guideSlug: "osun-nature-culture",
    name: "Osun-Osogbo Sacred Grove",
    kind: "nature",
    area: "Osogbo",
    address: "Osun-Osogbo Sacred Grove, Osogbo, Osun State, Nigeria",
    summary: "UNESCO-recognised sacred forest landscape and the spiritual centre of the Osun-Osogbo festival.",
    cost: "Confirm current visitor admission and guide charges",
    hours: "Visitor access varies around religious events and festival periods.",
    mapQuery: "Osun Osogbo Sacred Grove",
    source: { label: "Osun State Government — Tourism", href: "https://www.osunstate.gov.ng/2017/06/travel-guide-five-places-must-visit-osun/" },
    checkedAt: "2026-10-07",
    tags: ["UNESCO", "sacred grove", "culture", "Osogbo"]
  },
  {
    slug: "erin-ijesha-waterfall",
    guideSlug: "osun-nature-culture",
    name: "Erin-Ijesha Waterfall",
    kind: "nature",
    area: "Erin-Ijesha",
    address: "Erin-Ijesha, Oriade LGA, Osun State, Nigeria",
    summary: "Multi-level Olumirin waterfall and one of Osun State's best-known nature attractions.",
    cost: "Confirm current community/site admission before visiting",
    hours: "Visit in daylight; current management arrangements can change.",
    mapQuery: "Erin Ijesha Waterfall Osun",
    source: { label: "Osun State Government — Tourist Centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    checkedAt: "2026-10-07",
    tags: ["waterfall", "nature", "Erin-Ijesha", "Osun"]
  },
  {
    slug: "ayikunnugba-waterfall-oke-ila",
    guideSlug: "osun-nature-culture",
    name: "Ayikunnugba Waterfall",
    kind: "nature",
    area: "Oke-Ila Orangun",
    address: "Oke-Ila Orangun, Ifedayo LGA, Osun State, Nigeria",
    summary: "Roughly 30-metre waterfall highlighted by Osun State's tourism board.",
    cost: "Confirm current local access and charges",
    hours: "Daylight visit recommended.",
    mapQuery: "Ayikunnugba Waterfall Oke Ila Osun",
    source: { label: "Osun State Government — Tourist Centres", href: "https://www.osunstate.gov.ng/tourist-centres/" },
    checkedAt: "2026-10-07",
    tags: ["waterfall", "nature", "Oke-Ila", "Osun"]
  }
];
