import type { ExplorePlace } from "@/lib/explore-places";

export const exploreGrowthPlacesWave7: ExplorePlace[] = [
  {
    slug: "niger-bridge-asaba",
    guideSlug: "asaba",
    name: "Niger Bridge",
    kind: "landmark",
    area: "Asaba–Onitsha crossing",
    address: "River Niger crossing between Asaba, Delta State and Onitsha, Anambra State, Nigeria",
    summary: "The landmark bridge crossing the River Niger between Asaba and Onitsha, central to the city's gateway identity.",
    cost: "No tourist admission; this is active transport infrastructure",
    hours: "Open as a public road crossing; sightseeing should be done only from safe public viewpoints.",
    mapQuery: "Niger Bridge Asaba Onitsha",
    source: { label: "Discover Delta — Asaba visitor guide", href: "https://www.discoverdeltang.com/visit/asaba" },
    checkedAt: "2026-10-07",
    tags: ["River Niger", "bridge", "landmark", "Asaba"]
  },
  {
    slug: "lander-brothers-anchorage-asaba",
    guideSlug: "asaba",
    name: "Lander Brothers Anchorage",
    kind: "landmark",
    area: "Asaba riverside",
    address: "Asaba riverside, Oshimili South, Delta State, Nigeria",
    summary: "A Niger-side memorial, garden and small museum connected with Richard and John Lander's exploration history.",
    cost: "Current access fee is not published — confirm locally before visiting",
    hours: "Opening hours are not published; visit in daylight and confirm access.",
    mapQuery: "Lander Brothers Anchorage Asaba",
    source: { label: "Discover Delta — Lander Brothers Anchorage", href: "https://www.discoverdeltang.com/visit/asaba/lander-brothers-anchorage" },
    checkedAt: "2026-10-07",
    tags: ["River Niger", "heritage", "history", "Asaba"]
  },
  {
    slug: "stephen-keshi-stadium-asaba",
    guideSlug: "asaba",
    name: "Stephen Keshi Stadium",
    kind: "landmark",
    area: "Asaba",
    address: "Stephen Keshi Stadium, Asaba, Delta State, Nigeria",
    summary: "Asaba's major sports and events venue, useful when athletics, football or large public events are scheduled.",
    cost: "Event-dependent — confirm the specific programme or ticket",
    hours: "Access depends on the event calendar.",
    mapQuery: "Stephen Keshi Stadium Asaba",
    source: { label: "Discover Delta — Asaba visitor guide", href: "https://www.discoverdeltang.com/visit/asaba" },
    checkedAt: "2026-10-07",
    tags: ["stadium", "sports", "events", "Asaba"]
  },
  {
    slug: "yenagoa-city-park",
    guideSlug: "yenagoa",
    name: "Yenagoa City Park",
    kind: "attraction",
    area: "Peace Park",
    address: "Yenagoa City Park, Peace Park, Yenagoa, Bayelsa State, Nigeria",
    summary: "Omu Resort-operated family park with rides, water park, skating, archery, horse rides, mini golf and a mini zoo.",
    cost: "Packages vary by attraction — check the official Yenagoa City Park site for current pricing",
    hours: "Confirm current daily opening hours with the operator before visiting.",
    phone: "+234 903 956 9299",
    website: "https://yenagoa.omuresort.org/",
    mapQuery: "Yenagoa City Park Peace Park Bayelsa",
    source: { label: "Yenagoa City Park official site", href: "https://yenagoa.omuresort.org/" },
    checkedAt: "2026-10-07",
    tags: ["family", "amusement", "water park", "Yenagoa"]
  },
  {
    slug: "peace-park-yenagoa",
    guideSlug: "yenagoa",
    name: "Peace Park",
    kind: "attraction",
    area: "Central Yenagoa",
    address: "Peace Park, Yenagoa, Bayelsa State, Nigeria",
    summary: "Major civic and recreation space used for state events, public gatherings and leisure.",
    cost: "Public-event and attraction access varies — confirm the activity you plan to attend",
    hours: "Event and facility hours vary.",
    mapQuery: "Peace Park Yenagoa Bayelsa",
    source: { label: "Bayelsa State Government — Peace Park event coverage", href: "https://bayelsastate.gov.ng/support-our-armed-forces-gov-diri-urges-corporate-bodies/" },
    checkedAt: "2026-10-07",
    tags: ["park", "events", "recreation", "Yenagoa"]
  },
  {
    slug: "best-western-plus-oxbow-lake-yenagoa",
    guideSlug: "yenagoa",
    name: "Best Western Plus at the Oxbow Lake",
    kind: "hotel",
    area: "Swali / Oxbow Lake",
    address: "10 Julius Berger Road, Swali, Yenagoa 560223, Bayelsa State, Nigeria",
    summary: "Waterfront hotel on the Oxbow Lake axis with rooms, dining, events and leisure facilities.",
    cost: "Official site currently shows rooms from about ₦180,000 per night; confirm live rates for your dates",
    costNote: "Hotel rates are dynamic and can change by room type and date.",
    hours: "Hotel operates daily; restaurant and facility hours vary.",
    website: "https://www.bestwesternplusyenagoa.com/",
    mapQuery: "Best Western Plus Oxbow Lake Yenagoa",
    source: { label: "Best Western Plus Yenagoa official site", href: "https://www.bestwesternplusyenagoa.com/" },
    checkedAt: "2026-10-07",
    tags: ["hotel", "waterfront", "Oxbow Lake", "Yenagoa"]
  },
  {
    slug: "national-museum-owerri",
    guideSlug: "owerri",
    name: "National Museum Owerri",
    kind: "attraction",
    area: "Shell Camp",
    address: "B65 Shell Camp, Off Orlu Road, Owerri, Imo State, Nigeria",
    summary: "NCMM national museum serving Owerri and Imo State with cultural and historical collections.",
    cost: "Confirm current museum admission directly with NCMM",
    hours: "Confirm current opening hours before visiting.",
    mapQuery: "National Museum Owerri Shell Camp",
    source: { label: "National Commission for Museums and Monuments — National Museums", href: "https://museum.ng/museums/national-museums/" },
    checkedAt: "2026-10-07",
    tags: ["museum", "culture", "history", "Owerri"]
  },
  {
    slug: "mbari-cultural-centre-owerri",
    guideSlug: "owerri",
    name: "Mbari Cultural Centre",
    kind: "attraction",
    area: "Ikenegbu",
    address: "Mbari Cultural Centre, Ikenegbu, Owerri, Imo State, Nigeria",
    summary: "Owerri cultural centre associated with Imo art, artefacts and performance heritage.",
    cost: "Confirm current visitor or event charges before travelling",
    hours: "Programme and public access can vary; confirm current opening.",
    mapQuery: "Mbari Cultural Centre Ikenegbu Owerri",
    source: { label: "Imo State Investment Promotion Agency — tourism profile", href: "https://isipa.im.gov.ng/industryprofile.html" },
    checkedAt: "2026-10-07",
    tags: ["culture", "art", "heritage", "Owerri"]
  },
  {
    slug: "imo-state-zoological-garden-nekede",
    guideSlug: "owerri",
    name: "Imo State Zoological Garden",
    kind: "attraction",
    area: "Nekede",
    address: "Nekede, Owerri West, Imo State, Nigeria",
    summary: "State zoological/wildlife facility in the Owerri area; rehabilitation has appeared in Imo State tourism budgets.",
    cost: "Confirm current admission and operating status before travelling",
    hours: "Verify current public access before visiting.",
    mapQuery: "Imo State Zoological Garden Nekede",
    source: { label: "Imo State budget — tourism rehabilitation programme", href: "https://axxpoint.imostate.gov.ng/pdf/IMSG_2024_Q2_Budget_Report.pdf?ver=056" },
    checkedAt: "2026-10-07",
    tags: ["zoo", "wildlife", "family", "Owerri"]
  },
  {
    slug: "flower-garden-ilorin",
    guideSlug: "ilorin",
    name: "Kwara Flower Garden",
    kind: "nature",
    area: "GRA",
    address: "Adeloun Road, GRA, Ilorin, Kwara State, Nigeria",
    summary: "Government-listed 2.8-hectare green and recreation asset in Ilorin GRA.",
    cost: "Confirm current public access and activity charges before visiting",
    hours: "Current visitor hours are not stated on the government tourism page.",
    mapQuery: "Flower Garden Adeloun Road Ilorin",
    source: { label: "Kwara State Government — Tourism", href: "https://kwarastate.gov.ng/do-business/tourism/" },
    checkedAt: "2026-10-07",
    tags: ["garden", "park", "GRA", "Ilorin"]
  },
  {
    slug: "sobi-hills-ilorin",
    guideSlug: "ilorin",
    name: "Sobi Hills",
    kind: "nature",
    area: "Ilorin East",
    address: "Sobi area, Ilorin East, Kwara State, Nigeria",
    summary: "Hill landscape identified by Kwara State's Ilorin East local-government profile as a visitor attraction.",
    cost: "No standard official admission fee is published — confirm local access before visiting",
    hours: "Visit in daylight and confirm current access locally before hiking or climbing.",
    mapQuery: "Sobi Hills Ilorin Kwara State",
    source: { label: "Kwara State Government — Ilorin East LGA", href: "https://kwarastate.gov.ng/government/lgas/" },
    checkedAt: "2026-10-07",
    tags: ["hill", "nature", "viewpoint", "Ilorin"]
  },
  {
    slug: "kwara-hotel-ilorin",
    guideSlug: "ilorin",
    name: "Kwara Hotel",
    kind: "hotel",
    area: "GRA",
    address: "GRA, Ilorin, Kwara State, Nigeria",
    summary: "Long-established Ilorin hospitality property highlighted by Kwara State's tourism page for retreats, vacations and city stays.",
    cost: "Live room rates vary — confirm directly for your dates",
    hours: "Hotel operations are daily; facilities may have separate hours.",
    mapQuery: "Kwara Hotel Ilorin GRA",
    source: { label: "Kwara State Government — Tourism", href: "https://kwarastate.gov.ng/do-business/tourism/" },
    checkedAt: "2026-10-07",
    tags: ["hotel", "GRA", "stay", "Ilorin"]
  },
  {
    slug: "national-museum-makurdi",
    guideSlug: "makurdi",
    name: "National Museum Makurdi",
    kind: "attraction",
    area: "Ahmadu Bello Way",
    address: "GP 4, Ahmadu Bello, opposite Deputy Governor's Office, Makurdi, Benue State, Nigeria",
    summary: "NCMM museum in Makurdi with state and regional heritage collections.",
    cost: "Confirm current museum admission directly with NCMM",
    hours: "Confirm current opening hours before visiting.",
    phone: "+234 808 937 7622",
    mapQuery: "National Museum Makurdi Ahmadu Bello",
    source: { label: "National Commission for Museums and Monuments — National Museums", href: "https://museum.ng/museums/national-museums/" },
    checkedAt: "2026-10-07",
    tags: ["museum", "history", "culture", "Makurdi"]
  },
  {
    slug: "river-benue-makurdi",
    guideSlug: "makurdi",
    name: "River Benue Waterfront",
    kind: "nature",
    area: "Makurdi riverfront",
    address: "River Benue waterfront, Makurdi, Benue State, Nigeria",
    summary: "The river defines Makurdi's landscape and supports waterfront views, leisure and the city's bridge identity.",
    cost: "Public viewpoints may be free; organised leisure or boat activities vary",
    hours: "Use daylight and verify current local access before river activities.",
    mapQuery: "River Benue Makurdi",
    source: { label: "VisitBenue — official tourism platform", href: "https://visitbenue.ng/" },
    checkedAt: "2026-10-07",
    tags: ["river", "waterfront", "nature", "Makurdi"]
  },
  {
    slug: "wurukum-roundabout-makurdi",
    guideSlug: "makurdi",
    name: "Wurukum Roundabout",
    kind: "landmark",
    area: "Wurukum",
    address: "Wurukum Roundabout, Makurdi, Benue State, Nigeria",
    summary: "Prominent Makurdi urban landmark and navigation point near one of the city's major commercial areas.",
    cost: "Free public landmark",
    hours: "Open public road landmark; use normal road-safety precautions.",
    mapQuery: "Wurukum Roundabout Makurdi",
    source: { label: "VisitBenue — official tourism platform", href: "https://visitbenue.ng/" },
    checkedAt: "2026-10-07",
    tags: ["landmark", "city", "Wurukum", "Makurdi"]
  },
  {
    slug: "omu-resort-lagos",
    guideSlug: "ibeju-lekki-resorts-nature",
    name: "Omu Resort Lagos",
    kind: "attraction",
    area: "Bogije / Ibeju-Lekki",
    address: "Bogije Town, almost opposite Lakowe Lakes Golf Course, Ibeju-Lekki, Lagos State, Nigeria",
    summary: "Large family resort combining zoo, water park, rides, mini golf, creek activities, museum and outdoor recreation.",
    cost: "Ticket tiers and upgrades vary; official site currently lists separate activity prices such as kayaking and go-karting",
    costNote: "Check the official ticket page because packages and prices can change.",
    hours: "Official site lists Monday–Saturday 9:00 AM–6:00 PM and Sunday 12:00 PM–6:00 PM; reconfirm before travelling.",
    phone: "+234 814 281 2406",
    website: "https://omuresort.com/lagos/",
    mapQuery: "Omu Resort Bogije Ibeju Lekki Lagos",
    source: { label: "Omu Resort Lagos official site", href: "https://omuresort.com/lagos/" },
    checkedAt: "2026-10-07",
    tags: ["family", "zoo", "water park", "Ibeju-Lekki"]
  },
  {
    slug: "la-campagne-tropicana",
    guideSlug: "ibeju-lekki-resorts-nature",
    name: "La Campagne Tropicana Beach Resort",
    kind: "hotel",
    area: "Ikegun / Ibeju-Lekki",
    address: "Ikegun, Ibeju-Lekki Area, off Lekki-Epe Expressway, Lagos State, Nigeria",
    summary: "African-themed forest, river and beach resort with day experiences, nature, chalets and overnight stays.",
    cost: "Day access, activities and chalet rates vary — confirm the current package directly with the resort",
    hours: "Resort access and check-in rules vary by booking type.",
    phone: "+234 807 775 2827",
    website: "https://www.lacampagnetropicana.com/",
    mapQuery: "La Campagne Tropicana Ikegun Ibeju Lekki",
    source: { label: "La Campagne Tropicana official site", href: "https://www.lacampagnetropicana.com/" },
    checkedAt: "2026-10-07",
    tags: ["beach", "resort", "nature", "Ibeju-Lekki"]
  },
  {
    slug: "lufasi-nature-park",
    guideSlug: "ibeju-lekki-resorts-nature",
    name: "LUFASI Nature Park",
    kind: "nature",
    area: "Lekki-Epe corridor",
    address: "LUFASI Nature Park, Lekki-Epe Expressway axis, Lagos State, Nigeria",
    summary: "20-hectare urban farm-forest with nature trails, lakes, picnic areas, sports spaces and an animal sanctuary.",
    cost: "Confirm current entrance, activity and excursion charges directly with LUFASI",
    hours: "Check the official park page for current visitor hours before travelling.",
    website: "https://lufasi.org/lufasi-nature-park/",
    mapQuery: "LUFASI Nature Park Lagos",
    source: { label: "LUFASI Nature Park official page", href: "https://lufasi.org/lufasi-nature-park/" },
    checkedAt: "2026-10-07",
    tags: ["nature", "forest", "animal sanctuary", "Lekki"]
  }
];
