export type GrowthHub = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  intro: string[];
  searches: Array<{ query: string; serviceSlug: string }>;
  serviceSlugs: string[];
};

export const growthHubs: GrowthHub[] = [
  {
    slug: "nigerian-passport",
    title: "Nigerian Passport Application & Renewal Guide 2026",
    shortTitle: "Nigerian passport",
    description: "Renew, replace, correct or apply for a Nigerian passport with source-linked requirements, current fees and official NIS routes.",
    intro: [
      "Use this hub when you need a Nigerian passport and are not sure which process applies to your situation. It separates fresh applications, renewals, applications from abroad, lost passports and data changes so you can start with the right NIS route.",
      "Each linked guide shows the current fee or status, what to prepare, the official application portal and what happens after submission or biometric enrolment."
    ],
    searches: [{ query: "renew Nigerian passport", serviceSlug: "passport-renewal" }, { query: "Nigerian passport requirements", serviceSlug: "first-nigerian-passport" }, { query: "passport renewal fee", serviceSlug: "passport-renewal" }, { query: "track Nigerian passport application", serviceSlug: "passport-application-tracking" }, { query: "lost Nigerian passport", serviceSlug: "lost-nigerian-passport" }, { query: "change data on Nigerian passport", serviceSlug: "passport-change-of-data" }, { query: "correct name on Nigerian passport", serviceSlug: "passport-name-change" }, { query: "renew Nigerian passport abroad", serviceSlug: "passport-application-abroad" }, { query: "contactless Nigerian passport renewal", serviceSlug: "diaspora-contactless-passport-renewal" }, { query: "book Nigerian passport appointment", serviceSlug: "passport-appointment" }, { query: "passport centre availability", serviceSlug: "passport-centre-availability" }, { query: "Nigerian passport photo requirements", serviceSlug: "passport-photo-compliance" }, { query: "Nigeria emergency travel certificate", serviceSlug: "emergency-travel-certificate" }],
    serviceSlugs: ["passport-renewal", "first-nigerian-passport", "passport-application-tracking", "passport-appointment", "passport-centre-availability", "passport-photo-compliance", "passport-application-abroad", "diaspora-contactless-passport-renewal", "lost-nigerian-passport", "emergency-travel-certificate", "passport-name-change", "passport-change-of-data"]
  },
  {
    slug: "nin-corrections",
    title: "NIN Portal Guide 2026: Enrolment, Verification & Corrections",
    shortTitle: "NIN services",
    description: "Find the correct NIMC route for NIN enrolment, verification, slip reissue, SIM linkage and date-of-birth, name, phone or address changes.",
    intro: [
      "Use this hub when you need to enrol for a NIN, verify or replace your NIN record, link it to a SIM, or correct information already attached to your identity record. These tasks do not all use the same NIMC route.",
      "Choose the exact task below before paying or submitting documents. Each linked guide keeps its own official sources, current status and last-checked date."
    ],
    searches: [
      { query: "check my NIN", serviceSlug: "check-nin-number" },
      { query: "code to check NIN", serviceSlug: "check-nin-number" },
      { query: "NIN portal", serviceSlug: "nin-enrolment" },
      { query: "NIN enrolment", serviceSlug: "nin-enrolment" },
      { query: "NIN verification", serviceSlug: "ninauth-nin-verification" },
      { query: "replace NIN slip", serviceSlug: "nin-slip-reissue" },
      { query: "NIN SIM linkage", serviceSlug: "nin-sim-linkage" },
      { query: "check NIN SIM linkage status", serviceSlug: "check-nin-sim-linkage-status" },
      { query: "NIN modification portal", serviceSlug: "nin-date-of-birth-modification" },
      { query: "change date of birth on NIN", serviceSlug: "nin-date-of-birth-modification" },
      { query: "change name on NIN", serviceSlug: "nin-name-modification" },
      { query: "change phone number on NIN", serviceSlug: "nin-phone-modification" },
      { query: "change address on NIN", serviceSlug: "nin-address-modification" }
    ],
    serviceSlugs: [
      "check-nin-number",
      "nin-enrolment",
      "ninauth-nin-verification",
      "nin-slip-reissue",
      "nin-sim-linkage",
      "check-nin-sim-linkage-status",
      "fix-failed-nin-sim-linkage",
      "nin-date-of-birth-modification",
      "nin-name-modification",
      "nin-phone-modification",
      "nin-address-modification"
    ]
  },
  {
    slug: "bvn",
    title: "How to Check BVN 2026: Retrieval, Validation & Correction",
    shortTitle: "BVN services",
    description: "Check or retrieve your BVN, validate a BVN, correct BVN details, enrol for the first time or use the official non-resident BVN route.",
    intro: [
      "Use this hub when you need to find an existing BVN, confirm it, correct its details or enrol. MyNigeriaGuide does not collect BVN data; the linked guides explain the official bank, NIBSS or approved route for each task.",
      "If you simply want to know your existing BVN, start with BVN retrieval. Validation and data correction are separate tasks and should not be confused with retrieval."
    ],
    searches: [
      { query: "how to check BVN", serviceSlug: "bvn-retrieval" },
      { query: "check my BVN", serviceSlug: "bvn-retrieval" },
      { query: "BVN retrieval", serviceSlug: "bvn-retrieval" },
      { query: "how to retrieve BVN number", serviceSlug: "bvn-retrieval" },
      { query: "forgot my BVN", serviceSlug: "bvn-retrieval" },
      { query: "validate BVN", serviceSlug: "bvn-validation" },
      { query: "BVN correction", serviceSlug: "bvn-data-update" },
      { query: "change BVN details", serviceSlug: "bvn-data-update" },
      { query: "BVN enrolment", serviceSlug: "bvn-enrolment" },
      { query: "BVN for Nigerians abroad", serviceSlug: "non-resident-bvn" }
    ],
    serviceSlugs: ["bvn-retrieval", "bvn-validation", "bvn-data-update", "bvn-enrolment", "non-resident-bvn"]
  },
  {
    slug: "jamb-2026",
    title: "JAMB Portal 2026: CAPS, Registration, Results & Admission",
    shortTitle: "JAMB 2026",
    description: "Use the right JAMB portal route for 2026 registration, CAPS, admission status, results, profile codes, corrections and admission documents.",
    intro: [
      "This is an independent JAMB task hub for candidates who know what they need to do but are not sure which official JAMB route applies. It groups registration, CAPS, results, admission documents, profile-code issues and corrections without pretending to be the JAMB portal.",
      "Choose the exact task below. Each MyNigeriaGuide page explains the official route and links you to the responsible JAMB service."
    ],
    searches: [
      { query: "JAMB portal", serviceSlug: "jamb-2026-utme-registration" },
      { query: "JAMB portal login", serviceSlug: "jamb-2026-utme-registration" },
      { query: "JAMB registration 2026", serviceSlug: "jamb-2026-utme-registration" },
      { query: "JAMB Direct Entry 2026", serviceSlug: "jamb-direct-entry-2026" },
      { query: "JAMB profile code", serviceSlug: "jamb-profile-code" },
      { query: "JAMB CAPS", serviceSlug: "jamb-caps" },
      { query: "JAMB CAPS login", serviceSlug: "jamb-caps" },
      { query: "check JAMB admission status", serviceSlug: "jamb-caps" },
      { query: "JAMB reprint portal", serviceSlug: "jamb-examination-slip-2026" },
      { query: "JAMB examination slip", serviceSlug: "jamb-examination-slip-2026" },
      { query: "JAMB result checker", serviceSlug: "jamb-print-result" },
      { query: "print JAMB result", serviceSlug: "jamb-print-result" },
      { query: "JAMB admission letter", serviceSlug: "jamb-admission-letter" },
      { query: "JAMB matriculation list", serviceSlug: "jamb-matriculation-list" },
      { query: "JAMB regularization", serviceSlug: "jamb-regularization-condonement" },
      { query: "JAMB change of institution", serviceSlug: "jamb-change-course-institution" },
      { query: "JAMB name correction", serviceSlug: "jamb-change-name" },
      { query: "JAMB date of birth correction", serviceSlug: "jamb-correct-date-of-birth" }
    ],
    serviceSlugs: [
      "jamb-2026-utme-registration",
      "jamb-direct-entry-2026",
      "jamb-profile-code",
      "jamb-retrieve-profile-code",
      "jamb-retrieve-lost-epin",
      "jamb-caps",
      "jamb-examination-slip-2026",
      "jamb-print-result",
      "jamb-admission-letter",
      "jamb-matriculation-list",
      "jamb-regularization-condonement",
      "jamb-change-course-institution",
      "jamb-change-name",
      "jamb-correct-date-of-birth",
      "jamb-correct-gender",
      "jamb-correct-state-lga"
    ]
  },
  {
    slug: "nysc",
    title: "NYSC Portal 2026: Login, Registration, Senate List & Call-Up",
    shortTitle: "NYSC",
    description: "Use the correct NYSC portal route for registration, senate-list checks, call-up letters, relocation, revalidation, remobilization, corrections and exemption guidance.",
    intro: [
      "Use this independent NYSC task hub from mobilisation through post-registration issues. It maps common NYSC portal and login searches to the exact verified guide instead of creating separate thin pages for every login wording.",
      "Each guide explains what to prepare, where the official action happens and what to do next if your record, call-up, relocation or certificate process needs attention."
    ],
    searches: [
      { query: "NYSC portal", serviceSlug: "nysc-registration-local" },
      { query: "NYSC portal login", serviceSlug: "nysc-registration-local" },
      { query: "NYSC login", serviceSlug: "nysc-registration-local" },
      { query: "NYSC registration", serviceSlug: "nysc-registration-local" },
      { query: "NYSC foreign trained registration", serviceSlug: "nysc-foreign-trained-registration" },
      { query: "NYSC senate list", serviceSlug: "nysc-senate-list" },
      { query: "NYSC call up letter", serviceSlug: "nysc-call-up-letter" },
      { query: "NYSC relocation", serviceSlug: "nysc-relocation" },
      { query: "NYSC revalidation", serviceSlug: "nysc-revalidation" },
      { query: "NYSC remobilization", serviceSlug: "nysc-remobilization" },
      { query: "NYSC date of birth correction", serviceSlug: "nysc-correct-date-of-birth" },
      { query: "NYSC course correction", serviceSlug: "nysc-correct-course-of-study" },
      { query: "NYSC exemption certificate", serviceSlug: "nysc-exemption-certificate" }
    ],
    serviceSlugs: [
      "nysc-registration-local",
      "nysc-foreign-trained-registration",
      "nysc-senate-list",
      "nysc-call-up-letter",
      "nysc-relocation",
      "nysc-revalidation",
      "nysc-remobilization",
      "nysc-correct-date-of-birth",
      "nysc-correct-course-of-study",
      "nysc-exemption-certificate",
      "nysc-lost-discharge-certificate",
      "nysc-lost-exemption-certificate"
    ]
  },
  {
    slug: "waec",
    title: "WAEC Result Checker 2026: Results, Certificates & Timetable",
    shortTitle: "WAEC",
    description: "Check WAEC result guidance, digital certificates, certificate collection and corrections, result confirmation, complaints and current timetable information.",
    intro: [
      "Use this WAEC hub to reach the correct result or certificate task without confusing MyNigeriaGuide with WAEC's own result-checking service. The result guide explains what you need and then sends you to the official WAEC route.",
      "Certificate collection, digital certificates, confirmation, corrections and withheld-result complaints are different processes, so choose the exact task below."
    ],
    searches: [
      { query: "WAEC result checker", serviceSlug: "waec-check-result" },
      { query: "how to check WAEC result", serviceSlug: "waec-check-result" },
      { query: "WAEC result", serviceSlug: "waec-check-result" },
      { query: "WAEC digital certificate", serviceSlug: "waec-digital-certificate" },
      { query: "collect WAEC certificate", serviceSlug: "waec-collect-certificate" },
      { query: "WAEC result confirmation", serviceSlug: "waec-confirm-result-nigeria" },
      { query: "correct WAEC certificate error", serviceSlug: "waec-correct-certificate-error" },
      { query: "WAEC withheld result complaint", serviceSlug: "waec-withheld-result-complaint" },
      { query: "WAEC timetable 2026", serviceSlug: "waec-2026-private-candidates-timetable" }
    ],
    serviceSlugs: [
      "waec-check-result",
      "waec-digital-certificate",
      "waec-collect-certificate",
      "waec-confirm-result-nigeria",
      "waec-lost-certificate",
      "waec-correct-certificate-error",
      "waec-result-confirmation-overseas",
      "waec-withheld-result-complaint",
      "waec-2026-private-candidates-timetable"
    ]
  },
  {
    slug: "neco",
    title: "NECO Result Checker 2026: Results, Token, Certificate & Timetable",
    shortTitle: "NECO",
    description: "Use the official NECO routes for result checking, result tokens, certificate services, e-Verify, institutional verification, payments and timetable information.",
    intro: [
      "Use this NECO hub to choose the exact result, token, certificate or verification task. MyNigeriaGuide explains the process and links to the responsible NECO service rather than collecting result credentials.",
      "If you want to see a result, start with the result-checker guide. Token purchase, institutional verification and certificate services are separate tasks."
    ],
    searches: [
      { query: "NECO result checker", serviceSlug: "neco-check-result" },
      { query: "check NECO result", serviceSlug: "neco-check-result" },
      { query: "NECO result token", serviceSlug: "neco-purchase-result-token" },
      { query: "NECO token purchase", serviceSlug: "neco-purchase-result-token" },
      { query: "NECO e Verify", serviceSlug: "neco-e-verify" },
      { query: "NECO certificate", serviceSlug: "neco-certificate-service" },
      { query: "NECO institutional verification", serviceSlug: "neco-institution-verification" },
      { query: "NECO payment", serviceSlug: "neco-payment" },
      { query: "NECO timetable 2026", serviceSlug: "neco-2026-timetable" }
    ],
    serviceSlugs: [
      "neco-check-result",
      "neco-purchase-result-token",
      "neco-e-verify",
      "neco-certificate-service",
      "neco-institution-verification",
      "neco-payment",
      "neco-2026-ssce-internal-registration",
      "neco-2026-timetable"
    ]
  },
  {
    slug: "nelfund",
    title: "NELFUND Portal Guide 2026: Student Loan, Login, Status & Repayment",
    shortTitle: "NELFUND",
    description: "Use the correct NELFUND student-loan route for applications, status and upkeep, then understand repayment when it becomes relevant.",
    intro: [
      "Use this independent NELFUND task hub if you are looking for the student-loan portal, application steps, loan status or upkeep information. It routes each search to an existing source-linked MyNigeriaGuide guide and then to NELFUND's official service.",
      "Application, disbursement/status and repayment are different stages. Choose the stage that matches what you need now."
    ],
    searches: [
      { query: "NELFUND", serviceSlug: "nelfund-student-loan-application" },
      { query: "NELFUND portal", serviceSlug: "nelfund-student-loan-application" },
      { query: "NELFUND login", serviceSlug: "nelfund-student-loan-application" },
      { query: "student loan portal Nigeria", serviceSlug: "nelfund-student-loan-application" },
      { query: "NELFUND application", serviceSlug: "nelfund-student-loan-application" },
      { query: "NELFUND loan status", serviceSlug: "nelfund-loan-status-and-upkeep" },
      { query: "NELFUND upkeep", serviceSlug: "nelfund-loan-status-and-upkeep" },
      { query: "NELFUND repayment", serviceSlug: "nelfund-loan-repayment" }
    ],
    serviceSlugs: ["nelfund-student-loan-application", "nelfund-loan-status-and-upkeep", "nelfund-loan-repayment"]
  },
  {
    slug: "cac-business",
    title: "CAC Registration Nigeria 2026: Cost, Portal, Business Name & Company",
    shortTitle: "CAC business",
    description: "CAC registration in Nigeria: use the official portal for business-name or company registration, then find public search, fees and post-registration filings.",
    intro: [
      "This hub groups the CAC tasks most business owners need from choosing a name through registration and later compliance documents.",
      "Use the exact guide for your task because business-name registration, company incorporation, annual returns and certified documents have different requirements and fees."
    ],
    searches: [
      { query: "CAC registration", serviceSlug: "cac-business-name-registration" },
      { query: "CAC registration cost", serviceSlug: "cac-business-name-registration" },
      { query: "CAC official website", serviceSlug: "cac-public-search" },
      { query: "CAC registration portal", serviceSlug: "cac-business-name-registration" },
      { query: "register business name CAC", serviceSlug: "cac-business-name-registration" },
      { query: "register company CAC", serviceSlug: "cac-company-registration" },
      { query: "CAC public search", serviceSlug: "cac-public-search" },
      { query: "CAC company search", serviceSlug: "cac-public-search" },
      { query: "CAC name reservation", serviceSlug: "cac-name-reservation" },
      { query: "CAC annual returns", serviceSlug: "cac-annual-returns" },
      { query: "CAC certified true copy", serviceSlug: "cac-certified-true-copy" },
      { query: "CAC status report", serviceSlug: "cac-status-report" },
      { query: "CAC change company name", serviceSlug: "cac-change-company-name" },
      { query: "increase share capital CAC", serviceSlug: "cac-increase-issued-share-capital" },
      { query: "CAC letter of good standing", serviceSlug: "cac-letter-good-standing" },
      { query: "change company secretary CAC", serviceSlug: "cac-company-secretary-change" },
      { query: "alter memorandum and articles CAC", serviceSlug: "cac-alter-memorandum-articles" },
      { query: "convert private company to public CAC", serviceSlug: "cac-private-to-public-reregistration" },
      { query: "convert public company to private CAC", serviceSlug: "cac-public-to-private-reregistration" },
      { query: "reduce share capital CAC", serviceSlug: "cac-reduce-issued-share-capital" },
      { query: "CAC return of allotment", serviceSlug: "cac-return-of-allotment" },
      { query: "register company charge CAC", serviceSlug: "cac-register-company-charge" },
      { query: "CAC satisfaction of charge", serviceSlug: "cac-satisfy-company-charge" },
      { query: "CAC voluntary striking off", serviceSlug: "cac-voluntary-striking-off" }
    ],
    serviceSlugs: ["cac-business-name-registration", "cac-company-registration", "cac-public-search", "cac-name-reservation", "cac-annual-returns", "cac-certified-true-copy", "cac-status-report", "cac-change-company-name", "cac-increase-issued-share-capital", "cac-letter-good-standing", "cac-company-secretary-change", "cac-alter-memorandum-articles", "cac-private-to-public-reregistration", "cac-public-to-private-reregistration", "cac-reduce-issued-share-capital", "cac-return-of-allotment", "cac-register-company-charge", "cac-satisfy-company-charge", "cac-voluntary-striking-off"]
  },
  {
    slug: "drivers-licence",
    title: "Nigerian Driver’s Licence Guide",
    shortTitle: "Driver’s licence",
    description: "Apply for, renew, replace or change classes on a Nigerian driver’s licence with the official FRSC route.",
    intro: [
      "Use this hub to identify the right driver’s-licence process before visiting a centre or paying. New applications, renewals, lost licences and class changes are separate tasks.",
      "The linked guides explain the official route, preparation steps and current fee/status information available from FRSC sources."
    ],
    searches: [{ query: "renew Nigerian driver\'s licence", serviceSlug: "renew-drivers-licence" }, { query: "new driver\'s licence Nigeria", serviceSlug: "new-drivers-licence" }, { query: "verify Nigerian driver\'s licence", serviceSlug: "drivers-licence-verification" }, { query: "replace lost driver\'s licence", serviceSlug: "replace-lost-drivers-licence" }, { query: "driver\'s licence fee Nigeria", serviceSlug: "renew-drivers-licence" }, { query: "upgrade driver\'s licence class", serviceSlug: "upgrade-drivers-licence-class" }],
    serviceSlugs: ["renew-drivers-licence", "new-drivers-licence", "drivers-licence-verification", "replace-lost-drivers-licence", "upgrade-drivers-licence-class"]
  },
  {
    slug: "birth-records",
    title: "Nigeria Birth Certificate & NPC Records Guide",
    shortTitle: "Birth records",
    description: "Birth registration, adult attestation, digital certificate reissuance, reprints and record modifications through NPC.",
    intro: [
      "This hub separates child birth registration from adult attestation and from later certificate or record changes. Choose the task that matches the record you already have.",
      "Each guide points to the NPC route used for that service and explains the documents, steps and follow-up involved."
    ],
    searches: [{ query: "birth certificate Nigeria", serviceSlug: "npc-child-birth-registration" }, { query: "NPC birth attestation", serviceSlug: "npc-birth-attestation" }, { query: "check NPC attestation status", serviceSlug: "npc-check-attestation-status" }, { query: "reprint birth certificate", serviceSlug: "npc-birth-certificate-reprint" }, { query: "digital birth certificate Nigeria", serviceSlug: "npc-digital-birth-certificate-reissuance" }, { query: "correct birth record Nigeria", serviceSlug: "npc-modify-birth-record" }],
    serviceSlugs: ["npc-child-birth-registration", "npc-birth-attestation", "npc-check-attestation-status", "npc-digital-birth-certificate-reissuance", "npc-birth-certificate-reprint", "npc-modify-birth-record"]
  },
  {
    slug: "visitor-visas",
    title: "Visitor Visa Guides for Nigerians",
    shortTitle: "Visitor visas",
    description: "Official visitor-visa routes for Nigerians applying to the UK, Canada, United States, France/Schengen and Australia.",
    intro: [
      "Use this hub to compare the official starting points for popular visitor-visa destinations without mixing requirements between countries.",
      "Open the destination guide for country-specific fees, documents, biometrics, financial evidence and application steps. Visa rules differ, so the destination authority remains the final source."
    ],
    searches: [{ query: "UK visitor visa Nigeria", serviceSlug: "uk-standard-visitor-visa" }, { query: "Canada visitor visa Nigeria", serviceSlug: "canada-visitor-visa" }, { query: "US B1 B2 visa Nigeria", serviceSlug: "us-b1-b2-visitor-visa" }, { query: "Schengen visa Nigeria", serviceSlug: "france-schengen-short-stay-visa" }, { query: "Australia visitor visa Nigeria", serviceSlug: "australia-visitor-visa-600" }],
    serviceSlugs: ["uk-standard-visitor-visa", "canada-visitor-visa", "us-b1-b2-visitor-visa", "france-schengen-short-stay-visa", "australia-visitor-visa-600", "uae-tourist-visa", "south-africa-holiday-visa", "ireland-short-stay-visit-visa", "germany-schengen-tourist-visa", "italy-schengen-tourist-visa", "spain-schengen-tourist-visa", "netherlands-schengen-visa", "turkiye-tourist-visa", "china-tourist-visa-nigeria"]
  },
  {
    slug: "schengen-visas-nigeria",
    title: "Schengen Visa Guides for Nigerians 2026",
    shortTitle: "Schengen visas",
    description: "Compare Schengen visa routes from Nigeria for Germany, France, Italy, Spain and the Netherlands, with official requirements, fees and submission centres.",
    intro: [
      "Use this hub when your trip is to the Schengen area and you need to identify the correct destination guide. Each country page keeps its own Nigeria-specific submission route, documents, fee guidance and official sources.",
      "Apply through the country responsible for your trip under Schengen rules rather than choosing a visa centre only because it is convenient. Open the destination guide below for the current Nigerian application route."
    ],
    searches: [
      { query: "Germany visa from Nigeria", serviceSlug: "germany-schengen-tourist-visa" },
      { query: "France Schengen visa Nigeria", serviceSlug: "france-schengen-short-stay-visa" },
      { query: "Italy tourist visa Nigeria", serviceSlug: "italy-schengen-tourist-visa" },
      { query: "Spain Schengen visa Nigeria", serviceSlug: "spain-schengen-tourist-visa" },
      { query: "Netherlands visa Nigeria", serviceSlug: "netherlands-schengen-visa" }
    ],
    serviceSlugs: ["germany-schengen-tourist-visa", "france-schengen-short-stay-visa", "italy-schengen-tourist-visa", "spain-schengen-tourist-visa", "netherlands-schengen-visa"]
  },
  {
    slug: "product-certification-nigeria",
    title: "Product Registration & Certification in Nigeria",
    shortTitle: "Product certification",
    description: "Find the right NAFDAC or SON route for product registration, verification, MANCAP and SONCAP certification in Nigeria.",
    intro: [
      "Product regulation in Nigeria depends on what you make, sell or import. This hub separates NAFDAC registration from SON product registration, local-manufacturing MANCAP and import-focused SONCAP so businesses can start with the correct regulator.",
      "Open the exact guide before paying or shipping goods. Each page keeps the official source, current fee/status guidance, required documents and the next step after submission."
    ],
    searches: [
      { query: "NAFDAC product registration", serviceSlug: "nafdac-product-registration" },
      { query: "NAFDAC food registration", serviceSlug: "nafdac-food-product-registration" },
      { query: "NAFDAC cosmetics registration", serviceSlug: "nafdac-cosmetics-registration" },
      { query: "NAFDAC medical device registration", serviceSlug: "nafdac-medical-device-registration" },
      { query: "NAFDAC drug registration", serviceSlug: "nafdac-drug-product-registration" },
      { query: "verify NAFDAC number", serviceSlug: "nafdac-product-verification" },
      { query: "SONCAP certificate Nigeria", serviceSlug: "soncap-import-certification" },
      { query: "MANCAP certification", serviceSlug: "son-mancap-certification" },
      { query: "SON product registration", serviceSlug: "son-product-registration" },
      { query: "NAFDAC herbal medicine registration", serviceSlug: "nafdac-herbal-supplement-registration" },
      { query: "NAFDAC pesticide registration", serviceSlug: "nafdac-pesticide-registration" },
      { query: "NAFDAC animal feed registration", serviceSlug: "nafdac-animal-feed-registration" }
    ],
    serviceSlugs: ["nafdac-product-registration", "nafdac-food-product-registration", "nafdac-cosmetics-registration", "nafdac-medical-device-registration", "nafdac-drug-product-registration", "nafdac-product-verification", "nafdac-product-renewal", "soncap-import-certification", "son-mancap-certification", "son-product-registration", "nafdac-herbal-supplement-registration", "nafdac-pesticide-registration", "nafdac-animal-feed-registration"]
  },
  {
    slug: "business-compliance-nigeria",
    title: "Business Registration, IP, Export & Compliance Guide",
    shortTitle: "Business compliance",
    description: "CAC registration, trademarks and patents, SMEDAN, NEPC exporter registration, BPP contractor registration and core compliance routes in one hub.",
    intro: [
      "Starting a business legally is only the first layer. Depending on what the business does, it may also need intellectual-property protection, exporter registration, MSME onboarding, procurement registration or social-insurance compliance.",
      "Use this collection to move from CAC registration into the next official service that matches the business activity instead of assuming one certificate covers every requirement."
    ],
    searches: [
      { query: "register business CAC", serviceSlug: "cac-business-name-registration" },
      { query: "change director CAC", serviceSlug: "cac-change-director" },
      { query: "change registered address CAC", serviceSlug: "cac-change-registered-address" },
      { query: "CAC beneficial ownership PSC", serviceSlug: "cac-beneficial-ownership-psc" },
      { query: "trademark registration Nigeria", serviceSlug: "nipo-trademark-registration" },
      { query: "register exporter NEPC", serviceSlug: "nepc-exporter-registration" },
      { query: "SMEDAN registration", serviceSlug: "smedan-msme-registration" },
      { query: "BPP contractor registration", serviceSlug: "bpp-contractor-registration" }, { query: "SCUML registration", serviceSlug: "scuml-certificate-registration" }, { query: "pension clearance certificate", serviceSlug: "pencom-pension-clearance-certificate" }, { query: "ITF compliance certificate", serviceSlug: "itf-compliance-certificate" }
    ],
    serviceSlugs: ["cac-business-name-registration", "cac-company-registration", "cac-change-director", "cac-change-registered-address", "cac-beneficial-ownership-psc", "nipo-trademark-registration", "nipo-patent-registration", "nipo-industrial-design-registration", "copyright-work-registration", "smedan-msme-registration", "nepc-exporter-registration", "nepc-exporter-certificate-renewal-verification", "scuml-certificate-registration", "scuml-certificate-verification", "bpp-contractor-registration", "pencom-pension-clearance-certificate", "itf-compliance-certificate", "nsitf-employer-registration", "nsitf-compliance-certificate"]
  },
  {
    slug: "pension-services-nigeria",
    title: "Pension Registration Nigeria 2026: RSA, PFA Transfer & Micro Pension",
    shortTitle: "Pension services",
    description: "Open or transfer an RSA, resolve missing pension contributions, use Micro Pension and understand the 25% job-loss withdrawal route.",
    intro: [
      "This hub groups the pension tasks workers and self-employed Nigerians most often need, from opening an RSA through transfers, contribution problems and access to permitted benefits.",
      "Each guide separates what the PFA handles from what PenCom regulates, so you can use the correct route and avoid unofficial pension-withdrawal offers."
    ],
    searches: [
      { query: "open RSA Nigeria", serviceSlug: "pencom-open-rsa" },
      { query: "open RSA online", serviceSlug: "pencom-open-rsa" },
      { query: "pension registration Nigeria", serviceSlug: "pencom-open-rsa" },
      { query: "open pension account Nigeria", serviceSlug: "pencom-open-rsa" },
      { query: "register for RSA online", serviceSlug: "pencom-open-rsa" },
      { query: "NIN for RSA registration", serviceSlug: "pencom-open-rsa" },
      { query: "change PFA Nigeria", serviceSlug: "pencom-transfer-rsa" },
      { query: "how to transfer pension PFA", serviceSlug: "pencom-transfer-rsa" },
      { query: "RSA transfer process", serviceSlug: "pencom-transfer-rsa" },
      { query: "employer not paying pension", serviceSlug: "pencom-unremitted-contributions" },
      { query: "25 percent pension withdrawal", serviceSlug: "pencom-job-loss-25-percent-withdrawal" },
      { query: "micro pension Nigeria", serviceSlug: "pencom-micro-pension-registration" },
      { query: "micro pension account registration", serviceSlug: "pencom-micro-pension-registration" }
    ],
    serviceSlugs: ["pencom-open-rsa", "pencom-transfer-rsa", "pencom-unremitted-contributions", "pencom-job-loss-25-percent-withdrawal", "pencom-micro-pension-registration"]
  },
  {
    slug: "consumer-complaints-nigeria",
    title: "Consumer Complaint & Dispute Routes in Nigeria",
    shortTitle: "Consumer complaints",
    description: "Escalate unresolved bank, telecom, electricity and general consumer complaints to the correct Nigerian regulator.",
    intro: [
      "Many complaints fail because they are sent to the wrong regulator or escalated before the provider has been given the first opportunity to resolve them. This hub separates bank, telecom, electricity and broader consumer-protection routes.",
      "Keep the provider ticket, transaction evidence and complaint chronology before escalating. The linked guides explain the correct regulator and what evidence to retain."
    ],
    searches: [
      { query: "report bank to CBN", serviceSlug: "cbn-bank-complaint" },
      { query: "NCC complaint", serviceSlug: "ncc-telecom-complaint" },
      { query: "electricity complaint NERC", serviceSlug: "electricity-complaint-escalation" },
      { query: "FCCPC consumer complaint", serviceSlug: "fccpc-consumer-complaint" }
    ],
    serviceSlugs: ["cbn-bank-complaint", "ncc-telecom-complaint", "electricity-complaint-escalation", "electricity-estimated-billing-dispute", "fccpc-consumer-complaint"]
  },
  {
    slug: "vehicle-services-nigeria",
    title: "Nigeria Vehicle Registration & Verification Guide",
    shortTitle: "Vehicle services",
    description: "Register and verify a Nigerian vehicle, check ownership, insurance and Customs clearance, and reach the correct driver's-licence guide.",
    intro: [
      "A vehicle can have a valid-looking plate while ownership, insurance or Customs clearance still needs separate verification. This hub groups those checks so buyers and owners can verify the right record.",
      "Driver's-licence services are also linked here because licensing the driver and registering the vehicle are separate processes handled through different official records."
    ],
    searches: [
      { query: "register vehicle Nigeria", serviceSlug: "vehicle-registration-nvis" },
      { query: "verify number plate Nigeria", serviceSlug: "verify-vehicle-number-plate" },
      { query: "verify vehicle ownership Nigeria", serviceSlug: "vehicle-proof-of-ownership-verification" },
      { query: "check vehicle insurance Nigeria", serviceSlug: "vehicle-insurance-validation-ussd" },
      { query: "verify customs duty car Nigeria", serviceSlug: "customs-vehicle-duty-verification" },
      { query: "846 customs", serviceSlug: "customs-846-non-standard-vin" },
      { query: "846 e application verification portal NCS", serviceSlug: "customs-846-non-standard-vin" }
    ],
    serviceSlugs: ["vehicle-registration-nvis", "verify-vehicle-number-plate", "vehicle-proof-of-ownership-verification", "vehicle-insurance-validation-ussd", "customs-vehicle-duty-verification", "customs-846-non-standard-vin", "new-drivers-licence", "renew-drivers-licence"]
  },
  {
    slug: "housing-finance-nigeria",
    title: "NHF & FMBN Housing Finance Guide",
    shortTitle: "Housing finance",
    description: "Register for NHF, verify contributions, apply for an FMBN mortgage or renovation loan, and understand contribution refunds.",
    intro: [
      "Use this hub for the main Federal Mortgage Bank and National Housing Fund processes instead of treating NHF contribution, mortgage approval and refunds as the same transaction.",
      "The linked guides explain contribution history, eligibility, current product terms and which official FMBN route to use for each housing-finance task."
    ],
    searches: [
      { query: "NHF registration Nigeria", serviceSlug: "nhf-registration-and-contributions" },
      { query: "FMBN mortgage loan", serviceSlug: "nhf-mortgage-loan" },
      { query: "FMBN home renovation loan", serviceSlug: "fmbn-home-renovation-loan" },
      { query: "NHF refund", serviceSlug: "nhf-contribution-refund" }
    ],
    serviceSlugs: ["nhf-registration-and-contributions", "nhf-mortgage-loan", "fmbn-home-renovation-loan", "nhf-contribution-refund"]
  },
  {
    slug: "employment-support-nigeria",
    title: "Employment, Skills & Worker Protection Services in Nigeria",
    shortTitle: "Employment support",
    description: "Find NDE job-creation programmes and NSITF employer registration, compensation claims and compliance services.",
    intro: [
      "This hub separates employment and skills programmes from workplace social insurance. NDE supports job creation and skills pathways, while NSITF administers the Employees' Compensation Scheme for registered employers and workers.",
      "Use the specific guide for registration, a workplace claim or an employer compliance certificate so the correct evidence reaches the correct agency."
    ],
    searches: [
      { query: "NDE registration 2026", serviceSlug: "nde-rhei-registration" },
      { query: "ITF employer registration", serviceSlug: "itf-employer-registration" }, { query: "ITF compliance certificate", serviceSlug: "itf-compliance-certificate" }, { query: "NSITF registration", serviceSlug: "nsitf-employer-registration" },
      { query: "workplace injury compensation Nigeria", serviceSlug: "nsitf-workplace-injury-claim" },
      { query: "NSITF compliance certificate", serviceSlug: "nsitf-compliance-certificate" }
    ],
    serviceSlugs: ["nde-rhei-registration", "itf-employer-registration", "itf-compliance-certificate", "nsitf-employer-registration", "nsitf-workplace-injury-claim", "nsitf-compliance-certificate"]
  },
  {
    slug: "state-services-nigeria",
    title: "State Government Services in Nigeria",
    shortTitle: "State services",
    description: "Official state-level tax, resident identity, property and compliance guides for Lagos, FCT, Ogun, Rivers, Edo and Anambra.",
    intro: [
      "State-government services are not interchangeable across Nigeria. A Lagos Payer ID, FCT tax record, Ogun S-TIN, Rivers RIVTIN, Edo Tax ID and Anambra ASIN belong to different state systems.",
      "Use this hub to start with the correct state portal for resident registration, tax clearance, property charges and related state services instead of applying through a federal or another state's system."
    ],
    searches: [
      { query: "LASRRA registration", serviceSlug: "lagos-lasrra-registration" },
      { query: "Lagos Land Use Charge", serviceSlug: "lagos-land-use-charge" },
      { query: "Lagos tax clearance verification", serviceSlug: "lagos-tax-clearance-verification" },
      { query: "ASIN registration", serviceSlug: "anambra-asin-registration" },
      { query: "ASIN registration online", serviceSlug: "anambra-asin-registration" },
      { query: "FCT tax clearance certificate", serviceSlug: "fct-tax-clearance-application" },
      { query: "Ogun tax clearance certificate", serviceSlug: "ogun-tax-clearance-certificate" },
      { query: "RIVTIN registration", serviceSlug: "rivers-rivtin-registration" },
      { query: "Rivers tax clearance certificate", serviceSlug: "rivers-tax-clearance-certificate" }
    ],
    serviceSlugs: ["lagos-lasrra-registration", "lagos-payer-id", "lagos-land-use-charge", "lagos-tax-clearance-verification", "lagos-building-completion-certificate", "fct-file-individual-tax-return", "fct-tax-clearance-application", "fct-verify-tax-clearance", "ogun-taxpayer-registration", "ogun-tax-clearance-certificate", "rivers-rivtin-registration", "rivers-tax-clearance-certificate", "edo-tax-id-access", "anambra-asin-registration"]
  },
  {
    slug: "waec-neco-results",
    title: "WAEC, NECO & NABTEB Result Checker and Certificate Guide",
    shortTitle: "Exam results",
    description: "Check WAEC, NECO or NABTEB results, get the right result-checking credential, access certificates and use official verification routes.",
    intro: [
      "Result checking, certificate collection and institutional verification are different tasks. This hub separates them so students, graduates and institutions can start with the correct WAEC or NECO service.",
      "Use the linked guide for the exact task you need, especially when a school, employer or foreign institution asks for formal confirmation rather than a normal online result check."
    ],
    searches: [
      { query: "check WAEC result", serviceSlug: "waec-check-result" },
      { query: "WAEC digital certificate", serviceSlug: "waec-digital-certificate" },
      { query: "collect WAEC certificate", serviceSlug: "waec-collect-certificate" },
      { query: "WAEC result confirmation", serviceSlug: "waec-confirm-result-nigeria" },
      { query: "lost WAEC certificate", serviceSlug: "waec-lost-certificate" },
      { query: "check NECO result", serviceSlug: "neco-check-result" },
      { query: "buy NECO result token", serviceSlug: "neco-purchase-result-token" },
      { query: "verify NECO result", serviceSlug: "neco-e-verify" },
      { query: "WAEC timetable 2026", serviceSlug: "waec-2026-private-candidates-timetable" },
      { query: "NECO timetable 2026", serviceSlug: "neco-2026-timetable" },
      { query: "NABTEB result checker", serviceSlug: "nabteb-result-checker" }
    ],
    serviceSlugs: ["waec-check-result", "waec-digital-certificate", "waec-collect-certificate", "waec-confirm-result-nigeria", "waec-lost-certificate", "waec-correct-certificate-error", "waec-withheld-result-complaint", "waec-2026-private-candidates-timetable", "neco-check-result", "neco-purchase-result-token", "neco-e-verify", "neco-institution-verification", "neco-2026-timetable", "nabteb-result-checker"]
  },
  {
    slug: "electricity-meter-billing",
    title: "Electricity Meter, Billing and NERC Complaint Guide",
    shortTitle: "Electricity help",
    description: "Apply for a prepaid meter, challenge estimated billing, escalate unresolved DisCo complaints and check electricity tariff bands.",
    intro: [
      "Meter applications, billing disputes and regulatory complaints follow different routes. Start with the exact issue so you do not send a meter problem to the wrong complaint channel.",
      "The guides below keep the official NERC or electricity-industry route, evidence to keep and the escalation step to use when a DisCo does not resolve the problem."
    ],
    searches: [
      { query: "prepaid meter application Nigeria", serviceSlug: "electricity-prepaid-meter-application" },
      { query: "paid for meter but not installed", serviceSlug: "electricity-meter-paid-not-installed" },
      { query: "estimated bill complaint Nigeria", serviceSlug: "electricity-estimated-billing-dispute" },
      { query: "NERC complaint", serviceSlug: "electricity-complaint-escalation" },
      { query: "check electricity tariff band", serviceSlug: "electricity-tariff-band" }
    ],
    serviceSlugs: ["electricity-prepaid-meter-application", "electricity-meter-paid-not-installed", "electricity-estimated-billing-dispute", "electricity-complaint-escalation", "electricity-tariff-band"]
  },
  {
    slug: "nin-sim-linkage",
    title: "NIN-SIM Linkage, Status and Failed Verification Guide",
    shortTitle: "NIN-SIM linkage",
    description: "Link NIN to a Nigerian SIM, check linkage status, fix failed verification and escalate unresolved telecom complaints.",
    intro: [
      "A SIM can remain restricted even after a customer submits a NIN if the record has not verified successfully. This hub separates first-time linkage from status checks and failed-linkage troubleshooting.",
      "If the network does not resolve the issue after the required first complaint, use the NCC complaint guide for the escalation route and evidence to keep."
    ],
    searches: [
      { query: "link NIN to SIM", serviceSlug: "nin-sim-linkage" },
      { query: "check NIN SIM linkage status", serviceSlug: "check-nin-sim-linkage-status" },
      { query: "SIM still barred after linking NIN", serviceSlug: "fix-failed-nin-sim-linkage" },
      { query: "NCC telecom complaint", serviceSlug: "ncc-telecom-complaint" }
    ],
    serviceSlugs: ["nin-sim-linkage", "check-nin-sim-linkage-status", "fix-failed-nin-sim-linkage", "ncc-telecom-complaint"]
  },
  {
    slug: "inec-voter-services",
    title: "INEC Voter Registration, PVC, Transfer and Polling Unit Guide",
    shortTitle: "INEC voter services",
    description: "Find the correct INEC route for voter registration, PVC status, transfer, record correction, replacement and polling-unit lookup.",
    intro: [
      "INEC voter services change by electoral timetable, so registration availability and PVC collection should always be checked against the current official portal.",
      "Use this hub to separate a new registration from transfer, information correction, replacement, pickup and polling-unit lookup before you start."
    ],
    searches: [
      { query: "INEC voter registration", serviceSlug: "inec-new-voter-registration" },
      { query: "check PVC status", serviceSlug: "inec-pvc-status" },
      { query: "transfer voter registration", serviceSlug: "inec-voter-transfer" },
      { query: "correct PVC details", serviceSlug: "inec-update-voter-information" },
      { query: "replace lost PVC", serviceSlug: "inec-replace-lost-damaged-pvc" },
      { query: "where to collect PVC", serviceSlug: "inec-find-pvc-pickup-location" },
      { query: "find polling unit", serviceSlug: "inec-polling-unit-locator" }
    ],
    serviceSlugs: ["inec-pvc-status", "inec-new-voter-registration", "inec-voter-transfer", "inec-update-voter-information", "inec-replace-lost-damaged-pvc", "inec-find-pvc-pickup-location", "inec-polling-unit-locator"]
  },
  {
    slug: "bank-transfer-complaints",
    title: "Failed Bank Transfer, NIP Status and CBN Complaint Guide",
    shortTitle: "Bank transfer help",
    description: "Check an NIP transfer, understand delayed reversals and use the CBN complaint route after first reporting the issue to your bank.",
    intro: [
      "A failed, pending or reversed transfer can involve the sending bank, receiving bank and the NIP transaction record. Start by checking the transaction status and keeping the reference details.",
      "If the bank does not resolve a complaint through its own channel, the CBN guide below explains the escalation route and the evidence you should retain."
    ],
    searches: [
      { query: "check bank transfer status Nigeria", serviceSlug: "nip-transfer-status" },
      { query: "NIP status checker", serviceSlug: "nip-transfer-status" },
      { query: "NIP transfer status", serviceSlug: "nip-transfer-status" },
      { query: "failed bank transfer reversal", serviceSlug: "nip-transfer-status" },
      { query: "report bank to CBN", serviceSlug: "cbn-bank-complaint" },
      { query: "CBN bank complaint", serviceSlug: "cbn-bank-complaint" }
    ],
    serviceSlugs: ["nip-transfer-status", "cbn-bank-complaint"]
  },

  {
    slug: "nigeria-travel-documents",
    title: "Nigeria Travel Documents, ECOWAS Certificate & Yellow Card Guide",
    shortTitle: "Travel documents",
    description: "Find the correct Nigerian travel-document route for an ECOWAS Travel Certificate, Yellow Card, landing/exit card and related cross-border travel requirements.",
    intro: [
      "Travel documents are not interchangeable. A Nigerian passport, ECOWAS Travel Certificate, Yellow Card and landing or exit card each serve a different purpose.",
      "Use this hub to start with the exact document you need, confirm the official fee and requirements, and avoid paying for the wrong service."
    ],
    searches: [
      { query: "ECOWAS travel certificate Nigeria", serviceSlug: "ecowas-travel-certificate" },
      { query: "ECOWAS travel certificate price", serviceSlug: "ecowas-travel-certificate" },
      { query: "ECOWAS travel certificate application form", serviceSlug: "ecowas-travel-certificate" },
      { query: "ECOWAS certificate", serviceSlug: "ecowas-travel-certificate" },
      { query: "ECOWAS passport Nigeria", serviceSlug: "ecowas-travel-certificate" },
      { query: "Yellow Card Nigeria", serviceSlug: "yellow-card" },
      { query: "Nigeria landing card", serviceSlug: "nigeria-landing-exit-card" },
      { query: "Nigeria exit card", serviceSlug: "nigeria-landing-exit-card" },
      { query: "Nigeria emergency travel certificate", serviceSlug: "emergency-travel-certificate" }
    ],
    serviceSlugs: ["ecowas-travel-certificate", "emergency-travel-certificate", "yellow-card", "nigeria-landing-exit-card"]
  },
  {
    slug: "nelfund-student-loan",
    title: "NELFUND Portal Guide: Student Loan, Status, Upkeep & Repayment",
    shortTitle: "NELFUND",
    description: "Use the official NELFUND portal for student-loan applications, status checks, upkeep payments and repayment guidance.",
    intro: [
      "This hub separates the main NELFUND tasks so students can move from application to verification, status tracking and upkeep without confusing the different stages.",
      "Use the linked guide that matches your current stage, and sign in only through the official NELFUND portal rather than third-party loan agents."
    ],
    searches: [
      { query: "NELFUND portal", serviceSlug: "nelfund-student-loan-application" },
      { query: "NELFUND student loan", serviceSlug: "nelfund-student-loan-application" },
      { query: "NELFUND loan status", serviceSlug: "nelfund-loan-status-and-upkeep" },
      { query: "NELFUND upkeep", serviceSlug: "nelfund-loan-status-and-upkeep" },
      { query: "NELFUND repayment", serviceSlug: "nelfund-loan-repayment" }
    ],
    serviceSlugs: ["nelfund-student-loan-application", "nelfund-loan-status-and-upkeep", "nelfund-loan-repayment"]
  },
  {
    slug: "federal-tax-services",
    title: "Nigeria Federal Tax Registration, Filing, Payment & Refund Guide",
    shortTitle: "Federal tax services",
    description: "Use the NRS route for individual or corporate tax registration, tax clearance, self-filing, tax payment and refund tracking.",
    intro: [
      "Federal taxpayer registration, filing, payment, tax-clearance requests and refund tracking are separate tasks inside the Nigeria Revenue Service system.",
      "Choose the exact task below so you can prepare the correct taxpayer information and use the official NRS self-service route."
    ],
    searches: [
      { query: "retrieve Nigerian Tax ID", serviceSlug: "nrs-tax-id-retrieval" },
      { query: "NRS tax registration", serviceSlug: "nrs-individual-tax-registration" },
      { query: "NRS corporate tax registration", serviceSlug: "nrs-corporate-tax-registration" },
      { query: "NRS tax clearance certificate", serviceSlug: "nrs-tax-clearance-certificate" },
      { query: "file tax return Nigeria NRS", serviceSlug: "nrs-self-tax-filing" },
      { query: "pay tax online Nigeria NRS", serviceSlug: "nrs-tax-payment" },
      { query: "track NRS tax refund", serviceSlug: "nrs-refund-tracking" }
    ],
    serviceSlugs: ["nrs-tax-id-retrieval", "nrs-individual-tax-registration", "nrs-corporate-tax-registration", "nrs-tax-clearance-certificate", "nrs-self-tax-filing", "nrs-tax-payment", "nrs-refund-tracking"]
  },
  {
    slug: "private-services-nigeria",
    title: "Private Services in Nigeria: Banking, Telecoms, TV, Flights, Logistics & Tests",
    shortTitle: "Private services",
    description: "Verified private-provider service guides for telecoms, banking, pay-TV, airlines, logistics and private examination booking in Nigeria.",
    intro: [
      "Private-service pages on MyNigeriaGuide follow the same evidence rule as government guides: a provider task is published only when the provider exposes a stable official route or help source with enough detail to verify what the customer should do.",
      "Use the exact provider task below rather than a generic third-party tutorial. Fees, eligibility and timing can change, so each guide keeps its own last-verified date, provider links and visible conflict state when official pages disagree."
    ],
    searches: [
      { query: "MTN eSIM Nigeria", serviceSlug: "mtn-esim-activation" },
      { query: "Airtel eSIM Nigeria", serviceSlug: "airtel-esim-activation" },
      { query: "Glo eSIM Nigeria", serviceSlug: "glo-esim-activation" },
      { query: "open Moniepoint account", serviceSlug: "moniepoint-personal-account" },
      { query: "Moniepoint USSD code", serviceSlug: "moniepoint-ussd-banking" },
      { query: "open FirstBank account online", serviceSlug: "firstbank-open-account" },
      { query: "open UBA account online", serviceSlug: "uba-open-account" },
      { query: "Access Bank Solo Account", serviceSlug: "access-bank-solo-account" },
      { query: "pay and reconnect DStv", serviceSlug: "dstv-pay-reconnect" },
      { query: "change DStv package", serviceSlug: "dstv-change-package" },
      { query: "pay and reconnect GOtv", serviceSlug: "gotv-pay-reconnect" },
      { query: "book Air Peace flight", serviceSlug: "air-peace-book-flight" },
      { query: "Air Peace online check in", serviceSlug: "air-peace-online-check-in" },
      { query: "reschedule Air Peace flight", serviceSlug: "air-peace-reschedule-flight" },
      { query: "Air Peace extra baggage", serviceSlug: "air-peace-extra-baggage" },
      { query: "Air Peace lost baggage", serviceSlug: "air-peace-lost-baggage" },
      { query: "send parcel DHL Nigeria", serviceSlug: "dhl-send-parcel-nigeria" },
      { query: "DHL tracking Nigeria", serviceSlug: "dhl-track-shipment-nigeria" },
      { query: "British Council IELTS registration Nigeria", serviceSlug: "british-council-ielts-registration-nigeria" },
      { query: "IDP IELTS registration Nigeria", serviceSlug: "idp-ielts-registration-nigeria" },
      { query: "book GIGM bus online", serviceSlug: "gigm-book-bus-nigeria" },
      { query: "pay EKEDP bill or buy token", serviceSlug: "ekedp-pay-bill-buy-token" },
      { query: "apply for EKEDP prepaid meter", serviceSlug: "ekedp-prepaid-meter-application" },
      { query: "activate Starlink Nigeria", serviceSlug: "starlink-activate-kit-nigeria" },
      { query: "reactivate Starlink Nigeria", serviceSlug: "starlink-reactivate-service-nigeria" },
      { query: "SYNLAB home collection Nigeria", serviceSlug: "synlab-home-sample-collection" },
      { query: "check SYNLAB results online", serviceSlug: "synlab-pathprovider-results" },
      { query: "book Evercare Hospital appointment", serviceSlug: "evercare-book-appointment" },
      { query: "activate Paystack business Nigeria", serviceSlug: "paystack-business-activation-nigeria" },
      { query: "request Paystack terminal", serviceSlug: "paystack-physical-terminal-nigeria" },
      { query: "buy Leadway motor insurance online", serviceSlug: "leadway-buy-motor-insurance-online" },
      { query: "Uber driver signup Nigeria", serviceSlug: "uber-driver-signup-nigeria" },
      { query: "Bolt driver signup Nigeria", serviceSlug: "bolt-driver-signup-nigeria" },
      { query: "Smile data recharge Nigeria", serviceSlug: "smile-recharge-data-nigeria" },
      { query: "Spectranet recharge Nigeria", serviceSlug: "spectranet-recharge-renew-plan" },
      { query: "Konga return and refund", serviceSlug: "konga-return-refund" },
      { query: "sell on Konga Nigeria", serviceSlug: "konga-seller-registration" },
      { query: "sell on Jumia Nigeria", serviceSlug: "jumia-seller-registration-nigeria" },
      { query: "open GTBank account with 737", serviceSlug: "gtbank-737-open-account" },
      { query: "block GTBank debit card", serviceSlug: "gtbank-block-debit-card" },
      { query: "open Zenith Bank account online", serviceSlug: "zenith-online-account-opening" },
      { query: "open Stanbic Biz Smart account", serviceSlug: "stanbic-bizsmart-account" },
      { query: "open Fidelity business account online", serviceSlug: "fidelity-business-account-online" },
      { query: "Flutterwave business account Nigeria", serviceSlug: "flutterwave-business-account-nigeria" },
      { query: "open OPay account Nigeria", serviceSlug: "opay-account-opening-nigeria" },
      { query: "lock OPay account or card", serviceSlug: "opay-emergency-lock-account-card" },
      { query: "open Kuda account", serviceSlug: "kuda-personal-account-opening" },
      { query: "upgrade Kuda account tier", serviceSlug: "kuda-account-tier-upgrade" },
      { query: "Ikeja Electric buy token", serviceSlug: "ikeja-electric-pay-bill-buy-token" },
      { query: "Ikeja Electric prepaid meter application", serviceSlug: "ikeja-electric-prepaid-meter-application" },
      { query: "TOEFL registration Nigeria", serviceSlug: "toefl-registration-nigeria" },
      { query: "GRE registration Nigeria", serviceSlug: "gre-registration-nigeria" },
      { query: "PTE registration Nigeria", serviceSlug: "pte-registration-nigeria" },
      { query: "GMAT registration Nigeria", serviceSlug: "gmat-registration-nigeria" },
      { query: "AXA Mansard third party motor insurance", serviceSlug: "axa-mansard-third-party-motor-insurance" },
      { query: "send parcel with GIG Logistics", serviceSlug: "gigl-send-parcel-nigeria" },
      { query: "track GIGL shipment", serviceSlug: "gigl-track-shipment" },
      { query: "GIGL international shipping Nigeria", serviceSlug: "gigl-international-export-nigeria" },
      { query: "book GUO Transport online", serviceSlug: "guo-book-bus-online" },
      { query: "change GUO travel date", serviceSlug: "guo-change-travel-date" },
      { query: "open PalmPay account", serviceSlug: "palmpay-account-registration" },
      { query: "open Kuda Business account", serviceSlug: "kuda-business-account-opening" },
      { query: "AEDC buy token", serviceSlug: "aedc-pay-bill-buy-token" },
      { query: "AEDC prepaid meter application", serviceSlug: "aedc-map-meter-application" },
      { query: "AEDC MAP refund", serviceSlug: "aedc-map-refund" },
      { query: "IBEDC pay bill", serviceSlug: "ibedc-pay-bill-buy-token" },
      { query: "IBEDC prepaid meter application", serviceSlug: "ibedc-map-meter-application" },
      { query: "IBEDC MAP refund", serviceSlug: "ibedc-map-refund" },
      { query: "IBEDC Band A compensation token", serviceSlug: "ibedc-band-a-compensation-token" },
      { query: "Ecobank Xpress account", serviceSlug: "ecobank-xpress-account" },
      { query: "open Ecobank savings account Nigeria", serviceSlug: "ecobank-classic-savings-account" },
      { query: "become Ecobank Xpress Point agent", serviceSlug: "ecobank-xpress-point-agent" },
      { query: "reactivate Ecobank dormant account", serviceSlug: "ecobank-dormant-account-reactivation" },
      { query: "FCMB online savings account", serviceSlug: "fcmb-online-savings-account" },
      { query: "FCMB business account online", serviceSlug: "fcmb-business-account-online" },
      { query: "open ALAT account", serviceSlug: "alat-account-opening" },
      { query: "request ALAT debit card", serviceSlug: "alat-debit-card-request-activation" },
      { query: "open Sterling OneBank account", serviceSlug: "sterling-onebank-account-opening" },
      { query: "upgrade OneBank account", serviceSlug: "sterling-onebank-tier-upgrade" },
      { query: "buy Hygeia HMO plan", serviceSlug: "hygeia-health-plan-purchase" },
      { query: "find Hygeia hospital", serviceSlug: "hygeia-provider-directory" },
      { query: "PHED buy token", serviceSlug: "phed-pay-bill-buy-token" },
      { query: "PHED prepaid meter application", serviceSlug: "phed-map-meter-application" },
      { query: "Kaduna Electric buy token", serviceSlug: "kaduna-electric-pay-bill-buy-token" },
      { query: "Kaduna Electric prepaid meter application", serviceSlug: "kaduna-electric-map-meter-application" },
      { query: "MTN SIM swap", serviceSlug: "mtn-sim-swap-replacement" },
      { query: "port number to MTN", serviceSlug: "mtn-port-number-to-mtn" },
      { query: "Airtel 4G SIM swap", serviceSlug: "airtel-4g-sim-swap" },
      { query: "Glo SIM replacement", serviceSlug: "glo-sim-replacement" },
      { query: "port number to Glo", serviceSlug: "glo-port-number-to-glo" },
      { query: "Glo international roaming", serviceSlug: "glo-international-roaming" },
      { query: "Glo data roaming bundle", serviceSlug: "glo-data-roaming-bundle" },
      { query: "EEDC pay bill online", serviceSlug: "eedc-pay-bill-online" },
      { query: "EEDC Connect self service", serviceSlug: "eedc-connect-self-service" },
      { query: "EEDC new electricity connection", serviceSlug: "eedc-new-service-connection" },
      { query: "KEDCO prepaid meter application", serviceSlug: "kedco-map-meter-application" },
      { query: "KEDCO new electricity connection", serviceSlug: "kedco-new-electricity-connection" },
      { query: "KEDCO pay bill or buy token", serviceSlug: "kedco-pay-bill-buy-token" },
      { query: "file Leadway insurance claim", serviceSlug: "leadway-file-insurance-claim" },
      { query: "block Sterling account lost phone", serviceSlug: "sterling-emergency-block-account" },
      { query: "YEDC buy units", serviceSlug: "yedc-pay-bill-buy-units" },
      { query: "YEDC prepaid meter application", serviceSlug: "yedc-map-meter-application" },
      { query: "YEDC new connection", serviceSlug: "yedc-new-electricity-connection" },
      { query: "YEDC complaint online", serviceSlug: "yedc-online-complaint" },
      { query: "JED prepaid meter recharge", serviceSlug: "jed-prepaid-meter-recharge" },
      { query: "JED prepaid meter application", serviceSlug: "jed-map-meter-application" },
      { query: "JED new connection", serviceSlug: "jed-new-electricity-connection" },
      { query: "open Union Bank savings account", serviceSlug: "union-bank-basic-savings-account" },
      { query: "Union Bank debit card request", serviceSlug: "union-bank-debit-card-management" },
      { query: "Union Bank USSD code", serviceSlug: "union-bank-826-ussd" },
      { query: "Keystone Bank USSD code", serviceSlug: "keystone-7111-ussd" },
      { query: "Keystone emergency account block", serviceSlug: "keystone-emergency-account-block" },
      { query: "buy Avon HMO plan", serviceSlug: "avon-individual-health-plan" },
      { query: "Avon HMO hospital list", serviceSlug: "avon-provider-directory" },
      { query: "Union Bank current account", serviceSlug: "union-bank-basic-current-account" },
      { query: "Union Bank domiciliary account", serviceSlug: "union-bank-domiciliary-account" },
      { query: "activate Keystone debit card", serviceSlug: "keystone-debit-card-activation" },
      { query: "Avon HMO business plan", serviceSlug: "avon-business-health-plan" },
      { query: "check YEDC tariff band", serviceSlug: "yedc-check-tariff-band" },
      { query: "transfer JED old meter units", serviceSlug: "jed-transfer-old-meter-units" },
      { query: "book Ibom Air flight", serviceSlug: "ibom-air-book-flight" },
      { query: "Ibom Air online check in", serviceSlug: "ibom-air-online-check-in" },
      { query: "change Ibom Air flight", serviceSlug: "ibom-air-change-flight" },
      { query: "Ibom Air baggage allowance", serviceSlug: "ibom-air-baggage-allowance" },
      { query: "book Arik Air flight", serviceSlug: "arik-air-book-flight" },
      { query: "Arik Air online check in", serviceSlug: "arik-air-online-check-in" },
      { query: "book Green Africa flight", serviceSlug: "green-africa-book-flight" },
      { query: "Green Africa web check in", serviceSlug: "green-africa-online-check-in" },
      { query: "Union Bank current account", serviceSlug: "union-bank-basic-current-account" },
      { query: "Union Bank domiciliary account", serviceSlug: "union-bank-domiciliary-account" },
      { query: "activate Keystone debit card", serviceSlug: "keystone-debit-card-activation" },
      { query: "Avon HMO business plan", serviceSlug: "avon-business-health-plan" },
      { query: "check YEDC tariff band", serviceSlug: "yedc-check-tariff-band" },
      { query: "transfer JED old meter units", serviceSlug: "jed-transfer-old-meter-units" },
      { query: "book Ibom Air flight", serviceSlug: "ibom-air-book-flight" },
      { query: "Ibom Air online check in", serviceSlug: "ibom-air-online-check-in" },
      { query: "change Ibom Air flight", serviceSlug: "ibom-air-change-flight" },
      { query: "Ibom Air baggage allowance", serviceSlug: "ibom-air-baggage-allowance" },
      { query: "book Arik Air flight", serviceSlug: "arik-air-book-flight" },
      { query: "Arik Air online check in", serviceSlug: "arik-air-online-check-in" },
      { query: "book Green Africa flight", serviceSlug: "green-africa-book-flight" },
      { query: "Green Africa web check in", serviceSlug: "green-africa-online-check-in" },
      { query: "UBA USSD code", serviceSlug: "uba-919-ussd-banking" },
      { query: "block UBA debit card", serviceSlug: "uba-block-debit-card" },
      { query: "freeze UBA account", serviceSlug: "uba-freeze-account" },
      { query: "Stanbic IBTC USSD code", serviceSlug: "stanbic-909-ussd-banking" },
      { query: "Stanbic instant account", serviceSlug: "stanbic-instant-account-909" },
      { query: "block Stanbic account", serviceSlug: "stanbic-emergency-account-block" },
      { query: "Access Bank USSD code", serviceSlug: "access-bank-901-ussd" },
      { query: "block Access Bank account", serviceSlug: "access-bank-block-account" },
      { query: "Access Money Account", serviceSlug: "access-money-account" },
      { query: "FirstBank USSD code", serviceSlug: "firstbank-894-ussd" },
      { query: "MTN airtime transfer", serviceSlug: "mtn-share-airtime" },
      { query: "MTN data gifting", serviceSlug: "mtn-data-gifting" },
      { query: "Airtel data gifting", serviceSlug: "airtel-data-gifting" },
      { query: "clear DStv error", serviceSlug: "dstv-clear-error-code" },
      { query: "change GOtv package", serviceSlug: "gotv-change-package" },
      { query: "clear GOtv error", serviceSlug: "gotv-clear-error-code" },
      { query: "track Jumia order", serviceSlug: "jumia-track-order" },
      { query: "return Jumia order", serviceSlug: "jumia-return-refund" },
      { query: "BEDC prepaid meter application", serviceSlug: "bedc-map-meter-application" },
      { query: "BEDC complaint", serviceSlug: "bedc-customer-complaint" },
      { query: "BEDC token not loading", serviceSlug: "bedc-token-resolution" },
      { query: "block Zenith Bank account", serviceSlug: "zenith-emergency-account-block" },
      { query: "Fidelity Bank USSD code", serviceSlug: "fidelity-770-ussd-banking" },
      { query: "block Fidelity card or account", serviceSlug: "fidelity-emergency-block" },
      { query: "SAT registration Nigeria", serviceSlug: "sat-registration-nigeria" },
      { query: "Reliance HMO hospital list", serviceSlug: "reliance-provider-directory" },
      { query: "Reliance HMO small business plan", serviceSlug: "reliance-small-business-plan" },
      { query: "buy T2 airtime or data", serviceSlug: "t2-buy-airtime-data-online" },
      { query: "T2 data transfer", serviceSlug: "t2-data-transfer" },
      { query: "T2 data gifting", serviceSlug: "t2-data-gifting" },
      { query: "recharge StarTimes decoder", serviceSlug: "startimes-recharge-smartcard" },
      { query: "change StarTimes bouquet", serviceSlug: "startimes-change-bouquet" },
      { query: "renew ipNX subscription", serviceSlug: "ipnx-renew-subscription" },
      { query: "change ipNX plan", serviceSlug: "ipnx-change-service-plan" },
      { query: "report ipNX internet fault", serviceSlug: "ipnx-report-fault" },
      { query: "get FiberOne broadband", serviceSlug: "fiberone-new-service-installation" },
      { query: "renew FiberOne subscription", serviceSlug: "fiberone-renew-subscription" },
      { query: "relocate FiberOne service", serviceSlug: "fiberone-relocate-service" },
      { query: "open Moniepoint business account", serviceSlug: "moniepoint-business-account" },
      { query: "get Moniepoint POS", serviceSlug: "moniepoint-pos-terminal" },
      { query: "open Nomba business account", serviceSlug: "nomba-business-account" },
      { query: "get Nomba POS", serviceSlug: "nomba-pos-terminal" },
      { query: "open Standard Chartered account with SC Mobile", serviceSlug: "standard-chartered-sc-mobile-account-opening" },
      { query: "register Standard Chartered online banking", serviceSlug: "standard-chartered-online-banking-registration" },
      { query: "activate Standard Chartered Mobile Key", serviceSlug: "standard-chartered-mobile-key" },
      { query: "book United Nigeria Airlines", serviceSlug: "united-nigeria-book-flight" },
      { query: "United Nigeria online check in", serviceSlug: "united-nigeria-online-check-in" },
      { query: "change United Nigeria booking", serviceSlug: "united-nigeria-change-booking" },
      { query: "United Nigeria refund", serviceSlug: "united-nigeria-refund" },
      { query: "book ValueJet flight", serviceSlug: "valuejet-book-flight" },
      { query: "ValueJet online check in", serviceSlug: "valuejet-online-check-in" },
      { query: "ValueJet baggage allowance", serviceSlug: "valuejet-baggage-allowance" },
      { query: "book Aero Contractors flight", serviceSlug: "aero-contractors-book-flight" },
      { query: "Aero Contractors manage booking check in", serviceSlug: "aero-contractors-manage-check-in" },
      { query: "Aero Contractors refund", serviceSlug: "aero-contractors-refund" },
      { query: "open Jaiz Bank account online", serviceSlug: "jaiz-online-account-opening" },
      { query: "reset Jaiz digital banking password", serviceSlug: "jaiz-digital-banking-password-reset" },
      { query: "open Unity Bank business account", serviceSlug: "unity-business-account-opening" },
      { query: "Unity Bank *7799#", serviceSlug: "unity-7799-ussd-banking" },
      { query: "create Paga account", serviceSlug: "paga-personal-account-registration" },
      { query: "verify Paga transaction", serviceSlug: "paga-transaction-verification" },
      { query: "Paga verified business", serviceSlug: "paga-verified-business" },
      { query: "Quickteller pay bills", serviceSlug: "quickteller-pay-bills" },
      { query: "Quickteller bank transfer", serviceSlug: "quickteller-transfer-money" },
      { query: "UPS Nigeria shipping", serviceSlug: "ups-create-shipment-nigeria" },
      { query: "UPS tracking Nigeria", serviceSlug: "ups-track-package-nigeria" },
      { query: "book Max Air flight", serviceSlug: "max-air-book-flight" },
      { query: "Max Air online check in", serviceSlug: "max-air-online-check-in" },
      { query: "Max Air baggage allowance", serviceSlug: "max-air-baggage-allowance" },
      { query: "open Carbon account Nigeria", serviceSlug: "carbon-personal-account-opening" },
      { query: "apply for Carbon loan", serviceSlug: "carbon-loan-application" },
      { query: "repay Carbon loan", serviceSlug: "carbon-loan-repayment" },
      { query: "open FairMoney account", serviceSlug: "fairmoney-personal-account-opening" },
      { query: "open FairMoney Business account", serviceSlug: "fairmoney-business-account-opening" },
      { query: "ABC Transport booking", serviceSlug: "abc-transport-book-bus-online" },
      { query: "Remita pay RRR or biller", serviceSlug: "remita-pay-biller-or-rrr" },
      { query: "send parcel Red Star Express", serviceSlug: "red-star-send-parcel-nigeria" },
      { query: "track Red Star Express", serviceSlug: "red-star-track-shipment" },
      { query: "buy AIICO motor insurance", serviceSlug: "aiico-buy-motor-insurance-online" },
      { query: "AIICO motor insurance claim", serviceSlug: "aiico-motor-insurance-claim" },
      { query: "link BVN NIN Polaris Bank", serviceSlug: "polaris-bvn-nin-linking" },
      { query: "request Polaris cheque book", serviceSlug: "polaris-cheque-book-request" },
      { query: "open ProvidusBank account online", serviceSlug: "providus-online-account-opening" },
      { query: "Providus diaspora account", serviceSlug: "providus-diaspora-account-opening" },
      { query: "book Overland Airways", serviceSlug: "overland-airways-book-flight" },
      { query: "Overland Airways refund", serviceSlug: "overland-airways-refund" },
      { query: "Overland baggage allowance", serviceSlug: "overland-airways-baggage" },
      { query: "book Chisco Transport", serviceSlug: "chisco-book-bus-online" },
      { query: "rebook Chisco ticket", serviceSlug: "chisco-rebook-ticket" },
      { query: "Chisco baggage allowance", serviceSlug: "chisco-baggage-allowance" },
      { query: "book Rano Air", serviceSlug: "rano-air-book-flight" },
      { query: "Aramex shipping Nigeria", serviceSlug: "aramex-send-shipment-nigeria" },
      { query: "Aramex tracking Nigeria", serviceSlug: "aramex-track-shipment-nigeria" },
      { query: "Aramex Shop and Ship Nigeria", serviceSlug: "aramex-shop-and-ship-nigeria" },
      { query: "book Reddington appointment", serviceSlug: "reddington-book-appointment" },
      { query: "book Lagoon Hospital appointment", serviceSlug: "lagoon-hospital-book-appointment" },
      { query: "inDrive driver signup Nigeria", serviceSlug: "indrive-driver-signup-nigeria" },
      { query: "AXA Mansard motor claim", serviceSlug: "axa-mansard-motor-claim" }
    ],
    serviceSlugs: [
      "mtn-esim-activation",
      "airtel-esim-activation",
      "glo-esim-activation",
      "moniepoint-personal-account",
      "moniepoint-ussd-banking",
      "firstbank-open-account",
      "uba-open-account",
      "access-bank-solo-account",
      "dstv-pay-reconnect",
      "dstv-change-package",
      "gotv-pay-reconnect",
      "air-peace-book-flight",
      "air-peace-online-check-in",
      "air-peace-reschedule-flight",
      "air-peace-extra-baggage",
      "air-peace-lost-baggage",
      "dhl-send-parcel-nigeria",
      "dhl-track-shipment-nigeria",
      "british-council-ielts-registration-nigeria",
      "idp-ielts-registration-nigeria",
      "gigm-book-bus-nigeria",
      "ekedp-pay-bill-buy-token",
      "ekedp-prepaid-meter-application",
      "starlink-activate-kit-nigeria",
      "starlink-reactivate-service-nigeria",
      "synlab-home-sample-collection",
      "synlab-pathprovider-results",
      "evercare-book-appointment",
      "paystack-business-activation-nigeria",
      "paystack-physical-terminal-nigeria",
      "leadway-buy-motor-insurance-online",
      "uber-driver-signup-nigeria",
      "bolt-driver-signup-nigeria",
      "smile-recharge-data-nigeria",
      "spectranet-recharge-renew-plan",
      "konga-return-refund",
      "konga-seller-registration",
      "jumia-seller-registration-nigeria",
      "gtbank-737-open-account",
      "gtbank-block-debit-card",
      "zenith-online-account-opening",
      "stanbic-bizsmart-account",
      "fidelity-business-account-online",
      "flutterwave-business-account-nigeria",
      "opay-account-opening-nigeria",
      "opay-emergency-lock-account-card",
      "kuda-personal-account-opening",
      "kuda-account-tier-upgrade",
      "ikeja-electric-pay-bill-buy-token",
      "ikeja-electric-prepaid-meter-application",
      "toefl-registration-nigeria",
      "gre-registration-nigeria",
      "pte-registration-nigeria",
      "gmat-registration-nigeria",
      "axa-mansard-third-party-motor-insurance",
      "gigl-send-parcel-nigeria",
      "gigl-track-shipment",
      "gigl-international-export-nigeria",
      "guo-book-bus-online",
      "guo-change-travel-date",
      "palmpay-account-registration",
      "kuda-business-account-opening",
      "aedc-pay-bill-buy-token",
      "aedc-map-meter-application",
      "aedc-map-refund",
      "ibedc-pay-bill-buy-token",
      "ibedc-map-meter-application",
      "ibedc-map-refund",
      "ibedc-band-a-compensation-token",
      "ecobank-xpress-account",
      "ecobank-classic-savings-account",
      "ecobank-xpress-point-agent",
      "ecobank-dormant-account-reactivation",
      "fcmb-online-savings-account",
      "fcmb-business-account-online",
      "alat-account-opening",
      "alat-debit-card-request-activation",
      "sterling-onebank-account-opening",
      "sterling-onebank-tier-upgrade",
      "hygeia-health-plan-purchase",
      "hygeia-provider-directory",
      "phed-pay-bill-buy-token",
      "phed-map-meter-application",
      "kaduna-electric-pay-bill-buy-token",
      "kaduna-electric-map-meter-application",
      "mtn-sim-swap-replacement",
      "mtn-port-number-to-mtn",
      "airtel-4g-sim-swap",
      "glo-sim-replacement",
      "glo-port-number-to-glo",
      "glo-international-roaming",
      "glo-data-roaming-bundle",
      "eedc-pay-bill-online",
      "eedc-connect-self-service",
      "eedc-new-service-connection",
      "kedco-map-meter-application",
      "kedco-new-electricity-connection",
      "kedco-pay-bill-buy-token",
      "leadway-file-insurance-claim",
      "sterling-emergency-block-account",
      "yedc-pay-bill-buy-units",
      "yedc-map-meter-application",
      "yedc-new-electricity-connection",
      "yedc-online-complaint",
      "jed-prepaid-meter-recharge",
      "jed-map-meter-application",
      "jed-new-electricity-connection",
      "union-bank-basic-savings-account",
      "union-bank-debit-card-management",
      "union-bank-826-ussd",
      "keystone-7111-ussd",
      "keystone-emergency-account-block",
      "avon-individual-health-plan",
      "avon-provider-directory",
      "union-bank-basic-current-account",
      "union-bank-domiciliary-account",
      "keystone-debit-card-activation",
      "avon-business-health-plan",
      "yedc-check-tariff-band",
      "jed-transfer-old-meter-units",
      "ibom-air-book-flight",
      "ibom-air-online-check-in",
      "ibom-air-change-flight",
      "ibom-air-baggage-allowance",
      "arik-air-book-flight",
      "arik-air-online-check-in",
      "green-africa-book-flight",
      "green-africa-online-check-in",
      "uba-919-ussd-banking",
      "uba-block-debit-card",
      "uba-freeze-account",
      "stanbic-909-ussd-banking",
      "stanbic-instant-account-909",
      "stanbic-emergency-account-block",
      "access-bank-901-ussd",
      "access-bank-block-account",
      "access-money-account",
      "firstbank-894-ussd",
      "mtn-share-airtime",
      "mtn-data-gifting",
      "airtel-data-gifting",
      "dstv-clear-error-code",
      "gotv-change-package",
      "gotv-clear-error-code",
      "jumia-track-order",
      "jumia-return-refund",
      "bedc-map-meter-application",
      "bedc-customer-complaint",
      "bedc-token-resolution",
      "zenith-emergency-account-block",
      "fidelity-770-ussd-banking",
      "fidelity-emergency-block",
      "sat-registration-nigeria",
      "reliance-provider-directory",
      "reliance-small-business-plan",
      "t2-buy-airtime-data-online",
      "t2-data-transfer",
      "t2-data-gifting",
      "startimes-recharge-smartcard",
      "startimes-change-bouquet",
      "ipnx-renew-subscription",
      "ipnx-change-service-plan",
      "ipnx-report-fault",
      "fiberone-new-service-installation",
      "fiberone-renew-subscription",
      "fiberone-relocate-service",
      "moniepoint-business-account",
      "moniepoint-pos-terminal",
      "nomba-business-account",
      "nomba-pos-terminal",
      "standard-chartered-sc-mobile-account-opening",
      "standard-chartered-online-banking-registration",
      "standard-chartered-mobile-key",
      "united-nigeria-book-flight",
      "united-nigeria-online-check-in",
      "united-nigeria-change-booking",
      "united-nigeria-refund",
      "valuejet-book-flight",
      "valuejet-online-check-in",
      "valuejet-baggage-allowance",
      "aero-contractors-book-flight",
      "aero-contractors-manage-check-in",
      "aero-contractors-refund",
      "jaiz-online-account-opening",
      "jaiz-digital-banking-password-reset",
      "unity-business-account-opening",
      "unity-7799-ussd-banking",
      "paga-personal-account-registration",
      "paga-transaction-verification",
      "paga-verified-business",
      "quickteller-pay-bills",
      "quickteller-transfer-money",
      "ups-create-shipment-nigeria",
      "ups-track-package-nigeria",
      "max-air-book-flight",
      "max-air-online-check-in",
      "max-air-baggage-allowance",
      "carbon-personal-account-opening",
      "carbon-loan-application",
      "carbon-loan-repayment",
      "fairmoney-personal-account-opening",
      "fairmoney-business-account-opening",
      "abc-transport-book-bus-online",
      "remita-pay-biller-or-rrr",
      "red-star-send-parcel-nigeria",
      "red-star-track-shipment",
      "aiico-buy-motor-insurance-online",
      "aiico-motor-insurance-claim",
      "polaris-bvn-nin-linking",
      "polaris-cheque-book-request",
      "providus-online-account-opening",
      "providus-diaspora-account-opening",
      "overland-airways-book-flight",
      "overland-airways-refund",
      "overland-airways-baggage",
      "chisco-book-bus-online",
      "chisco-rebook-ticket",
      "chisco-baggage-allowance",
      "rano-air-book-flight",
      "aramex-send-shipment-nigeria",
      "aramex-track-shipment-nigeria",
      "aramex-shop-and-ship-nigeria",
      "reddington-book-appointment",
      "lagoon-hospital-book-appointment",
      "indrive-driver-signup-nigeria",
      "axa-mansard-motor-claim"
    ]
  },

];

export function getGrowthHub(slug: string) {
  return growthHubs.find((hub) => hub.slug === slug);
}

export function getGrowthHubsForService(serviceSlug: string) {
  return growthHubs.filter((hub) => hub.serviceSlugs.includes(serviceSlug));
}
