import type { Service } from "@/lib/types";

export type StepDetail = {
  stage: string;
  instruction: string;
  prepare: string[];
  checkpoint: string;
  keep: string;
};

const stopWords = new Set([
  "this","that","with","from","your","into","through","official","service","application",
  "process","using","used","required","where","when","then","before","after","complete",
]);

function tokens(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").split(/\s+/)
    .filter((token) => token.length > 3 && !stopWords.has(token));
}

function relevantRequirements(service: Service, step: string) {
  const words = tokens(step);
  return service.requirements
    .map((item) => {
      const lower = item.toLowerCase();
      const score = words.reduce((sum, word) => sum + (lower.includes(word) ? 1 : 0), 0);
      return { item, score };
    })
    .filter((row) => row.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3)
    .map((row) => row.item);
}

function stageFor(step: string, index: number) {
  if (/collect|download|print|receive|issued|available/i.test(step)) return "Collect / finish";
  if (/track|status|monitor|follow up|follow-up|wait for|approval|decision/i.test(step)) return "Follow up";
  if (/attend|visit|centre|center|office|biometric|fingerprint|capture|school|institution|branch/i.test(step)) return "Physical / assisted stage";
  if (/pay|payment|fee|checkout|remita|rrr/i.test(step)) return "Payment";
  if (/upload|attach|document|evidence|certificate|affidavit|passport photograph|photo/i.test(step)) return "Documents / upload";
  if (/verify|confirm|review|check|match/i.test(step)) return "Verify details";
  if (/submit|send|apply|request|register|file|enrol/i.test(step)) return "Submit / register";
  if (/sign in|login|log in|create account|open|start/i.test(step)) return "Start";
  return index === 0 ? "Start" : "Continue";
}

function checkpointFor(step: string) {
  if (/pay|payment|fee|checkout|remita|rrr/i.test(step)) return "Confirm the service, applicant/entity details and amount on the official payment screen before paying. Do not continue from an unsolicited payment link.";
  if (/upload|attach|document|evidence|certificate|affidavit|photo/i.test(step)) return "Check that every file belongs to the correct applicant/record, is readable and matches the portal prompt before upload.";
  if (/attend|visit|centre|center|office|biometric|fingerprint|capture/i.test(step)) return "Confirm the correct office/centre, date or appointment instruction before travelling, and take the originals where the guide or agency explicitly requires them.";
  if (/submit|send|apply|request|register|file|enrol/i.test(step)) return "Review names, numbers, dates, contact details and selections before final submission because corrections may require a separate official process.";
  if (/collect|download|print|receive|issued/i.test(step)) return "Check the finished document/result for spelling, identity details, reference numbers and status before relying on it.";
  if (/verify|confirm|review|check|match/i.test(step)) return "Make sure the displayed record is the correct person/entity and that the information matches the evidence you are using.";
  if (/sign in|login|log in|create account|open|start/i.test(step)) return "Use the official route linked on this guide and make sure you are working in the correct applicant/entity account before entering data.";
  return "Read the next screen or office instruction before moving on; do not assume an extra payment, document or visit is required unless the responsible agency asks for it.";
}

function keepFor(step: string, service: Service) {
  if (/pay|payment|fee|checkout|remita|rrr/i.test(step)) return "Keep the official receipt, payment reference or transaction ID.";
  if (/submit|send|apply|request|register|file|enrol/i.test(step)) return "Keep the application/reference number, acknowledgement or confirmation generated after submission.";
  if (/appointment|attend|visit|centre|center|office|biometric|capture/i.test(step)) return "Keep the appointment, acknowledgement or reference you may need at the physical stage.";
  if (/collect|download|print|receive|issued/i.test(step)) return "Keep the final document/result plus any receipt or reference used to obtain it.";
  if (/sms|phone|sim|code|pin/i.test(step)) return "Keep the linked phone/SIM and any official code or confirmation message private and accessible.";
  return service.agencySlug === "cac"
    ? "Keep the entity/application reference shown in CAC's portal."
    : "Keep any reference, confirmation, screenshot or acknowledgement generated by the official route.";
}

export function getStepDetails(service: Service): StepDetail[] {
  return service.steps.map((instruction, index) => ({
    stage: stageFor(instruction, index),
    instruction,
    prepare: relevantRequirements(service, instruction),
    checkpoint: checkpointFor(instruction),
    keep: keepFor(instruction, service),
  }));
}
